### ISSUE TITLE
Could not create PIO Core Virtual Environment

### ISSUE THREAD

**Issue by damonyu1989** [platformio/platformio-core-installer#102]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.50.0-insider
  PIO IDE: v2.0.1
  System: Linux, 5.3.0-53-generic, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 0.3.4
Platform: Linux-5.3.0-53-generic-x86_64-with-glibc2.25
Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/yulj/.platformio/penv

	at /home/yulj/.vscode-server-insiders/extensions/platformio.platformio-ide-2.0.1/node_modules/platformio-node-helpers/dist/index.js:1:4849
	at ChildProcess.c (/home/yulj/.vscode-server-insiders/extensions/platformio.platformio-ide-2.0.1/node_modules/platformio-node-helpers/dist/index.js:1:4745)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
  ```

**Comment by ivankravets** [comment]
Please run the next command in your system terminal and provide an output of:

```
python3 ~.platformio/.cache/tmp/get-platformio-0.3.4.py --verbose
```
