### ISSUE TITLE
AssertionError: SRE module mismatch

### ISSUE THREAD

**Issue by a888882** [platformio/platformio-core-installer#104]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.49.0
  PIO IDE: v2.0.1
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "D:\Users\ao\.platformio\.cache\tmp\get-platformio-0.3.4.py", line 19, in <module>
    import shutil
  File "D:\Program Files\WindowsApps\64343GTDocStudio.OfficeDocOpener_3.2.19.0_x86__3h5nez1g3qt2c\program\python-core-3.5.7\lib\shutil.py", line 10, in <module>
    import fnmatch
  File "D:\Program Files\WindowsApps\64343GTDocStudio.OfficeDocOpener_3.2.19.0_x86__3h5nez1g3qt2c\program\python-core-3.5.7\lib\fnmatch.py", line 14, in <module>
    import re
  File "D:\Program Files\WindowsApps\64343GTDocStudio.OfficeDocOpener_3.2.19.0_x86__3h5nez1g3qt2c\program\python-core-3.5.7\lib\re.py", line 123, in <module>
    import sre_compile
  File "D:\Program Files\WindowsApps\64343GTDocStudio.OfficeDocOpener_3.2.19.0_x86__3h5nez1g3qt2c\program\python-core-3.5.7\lib\sre_compile.py", line 17, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
AssertionError: SRE module mismatch

	at d:\Users\ao\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\platformio-node-helpers\dist\index.js:1:4911
	at ChildProcess.c (d:\Users\ao\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\platformio-node-helpers\dist\index.js:1:4807)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.cp.emit (d:\Users\ao\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Do you see `D:\Users\ao\.platformio\python3` folder?
