### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by zuglar** [platformio/platformio-core-installer#1108]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.0
  PIO IDE: v2.3.3
  System: Linux, 5.10.0-8-amd64, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.0.3
Platform: Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Python path: /usr/bin/python3
Creating a virtual environment at /media/zoltanuglar/ExData/PlatformIO/penv
/usr/bin/python3

	at /home/zoltanuglar/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771390
	at ChildProcess.a (/home/zoltanuglar/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771284)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by zuglar** [comment]
Dear Support!

When I set the 
[platformio]
core_dir = /path/to/custom/pio-core/storage
in the /etc/enviroment file I cannot use PlatformIO.
This is an internal (in my PC) SDD with exFat partisiton.

Do you have any advice to solve this issue?

Thanks in advance.
Zoltan Uglar
