### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by timaker** [platformio/platformio-core-installer#1112]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.57.1
  PIO IDE: v2.3.3
  System: Linux, 4.9.112-perf-g35c9f36, arm64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/home/tcke/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "/home/tcke/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "/home/tcke/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "/home/tcke/.platformio/.cache/tmp/.piocore-installer-do_qv3xr/tmppenzjj1q/pioinstaller.zip/pioinstaller/__main__.py", line 131, in main
  File "/home/tcke/.platformio/.cache/tmp/.piocore-installer-do_qv3xr/tmppenzjj1q/pioinstaller.zip/click/core.py", line 1137, in __call__
  File "/home/tcke/.platformio/.cache/tmp/.piocore-installer-do_qv3xr/tmppenzjj1q/pioinstaller.zip/click/core.py", line 1043, in main
  File "/home/tcke/.platformio/.cache/tmp/.piocore-installer-do_qv3xr/tmppenzjj1q/pioinstaller.zip/click/_unicodefun.py", line 100, in _verify_python_env
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

	at /home/tcke/.local/share/code-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771328
	at ChildProcess.a (/home/tcke/.local/share/code-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771222)
	at ChildProcess.emit (events.js:376:20)
	at ChildProcess.emit (domain.js:470:12)
	at maybeClose (internal/child_process.js:1055:16)
	at Socket.<anonymous> (internal/child_process.js:441:11)
	at Socket.emit (events.js:376:20)
	at Socket.emit (domain.js:470:12)
	at Pipe.<anonymous> (net.js:673:12)
  ```

**Comment by timaker** [comment]
Solved, just set the language of the system to LANGUAGE="en_US:en" in /etc/default/locale
