### ISSUE TITLE
Installation Manager Python version issue

### ISSUE THREAD

**Issue by JamesNewton** [platformio/platformio-core-installer#1127]
%23 Description of problem
Can't install PlatformIO version 2.3.3 unless I change the system version of Python3, which then causes the OS to fail to update and not open terminal from the launch bar. I can install version 2.2.1 just fine. 

Apparently the developer decided to stop supporting Python3.5x. And Ubuntu 16.04 won't work with 3.9 as the default. I can't find a way to let PlatformIO use the Python3.9 I've installed without setting it at as the default. 
If you go to terminal and enter python3 --version and get anything before 3.6, that's the issue. PlatformIO stopped supporting 3.5 and better. Now, installing 3.9 is a nightmare and setting it as the default for python3 is also a pain.

I have Ubuntu 16.04

ll /usr/bin/python* will show you what versions of python you actually have installed.

To install the latest Python, what worked for me was:

sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.9 python3.9-venv python3.9-dev
And then python3.9 -V should show the version, but python3 --version will still show the old version.

You are supposed to be able to see all the version with
sudo update-alternatives --config python3
but it showed update-alternatives: error: no alternatives for python

So a bit more googling found that we can do:
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
And then since I had 3.5 I also did
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
setting it to the lower priority. Now
sudo update-alternatives --config python3
works but it's already configured to 3.9

And... now PlatformIO installs the latest version! Woo Hoo!

But... Now the OS won't update. 

So I've had to set the default Python back to 3.5

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 
I actually did that, and there are butt tons. I made some comments on the first one, but figured I should add my own so I can keep track of what works and doesn't. 

  %23 Configuration

  VSCode: 1.60.1
  PIO IDE: v2.3.3
  System: Linux, 4.15.0-142-generic, x64

  %23 Exception
  ```
  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
	at /home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771390
	at a (/home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771284)
	at w (/home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771035)
	at u (/home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:770559)
	at /home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771343
	at new Promise (<anonymous>)
	at l (/home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771322)
	at e.callInstallerScript (/home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:7215)
	at async H.value (/home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:763673)
	at async t.default.install (/home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/dist/extension.js:1:6773)
	at async /home/jamesn/.vscode/extensions/platformio.platformio-ide-2.3.3/dist/extension.js:1:12776
  ```

**Comment by JamesNewton** [comment]
Problem is the default installed version of Python3.

If you go to terminal and enter python3 --version and get anything before 3.6, that's the issue. PlatformIO stopped supporting 3.5 and better. Now, installing 3.9 is a nightmare and setting it as the default for python3 is also a pain.

I have Ubuntu 16.04

ll /usr/bin/python* will show you what versions of python you actually have installed.

To install the latest Python, what worked for me was:

sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.9 python3.9-venv python3.9-dev
And then python3.9 -V should show the version, but python3 --version will still show the old version.

You are supposed to be able to see all the version with
sudo update-alternatives --config python3
but it showed update-alternatives: error: no alternatives for python

So a bit more googling found that we can do:
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
And then since I had 3.5 I also did
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
setting it to the lower priority. Now
sudo update-alternatives --config python3
works but it's already configured to 3.9

And... now PlatformIO installs the latest version!

However... doing that change on the default python screwed up my OS... it wouldn't check for updates any more. Had to set it back to 3.5. 

On Ubuntu 16.04, if I change the default python version, the OS has issues (can't find updates, etc...) so it may be that PlatformIO no longer supports the older OS's. (16.04 is near EOL) and I may have to upgrade to 18 or even 20.

If there is some way to get PlatformIO to use the later version e.g. not the default, and let the OS use the older version?
