### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by briancrouch** [platformio/platformio-core-installer#116]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.49.0
  PIO IDE: v2.1.0
  System: Darwin, 19.6.0, x64

  %23 Exception
  ```
  Error: ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type '   name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type '   name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type '   name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type '   name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type '   name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type '   name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/Users/bcrouch/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "/Users/bcrouch/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "/Users/bcrouch/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 45, in bootstrap
    import pioinstaller.__main__
  File "/Users/bcrouch/.platformio/.cache/tmp/.piocore-installer-SaQc3J/tmpPZZLKs/pioinstaller.zip/pioinstaller/__main__.py", line 22, in <module>
  File "/Users/bcrouch/.platformio/.cache/tmp/.piocore-installer-SaQc3J/tmpPZZLKs/pioinstaller.zip/pioinstaller/core.py", line 25, in <module>
  File "/Users/bcrouch/.platformio/.cache/tmp/.piocore-installer-SaQc3J/tmpPZZLKs/pioinstaller.zip/pioinstaller/home.py", line 19, in <module>
  File "/Users/bcrouch/.platformio/.cache/tmp/.piocore-installer-SaQc3J/tmpPZZLKs/pioinstaller.zip/requests/__init__.py", line 43, in <module>
  File "/Users/bcrouch/.platformio/.cache/tmp/.piocore-installer-SaQc3J/tmpPZZLKs/pioinstaller.zip/urllib3/__init__.py", line 7, in <module>
  File "/Users/bcrouch/.platformio/.cache/tmp/.piocore-installer-SaQc3J/tmpPZZLKs/pioinstaller.zip/urllib3/connectionpool.py", line 29, in <module>
  File "/Users/bcrouch/.platformio/.cache/tmp/.piocore-installer-SaQc3J/tmpPZZLKs/pioinstaller.zip/urllib3/connection.py", line 41, in <module>
  File "/Users/bcrouch/.platformio/.cache/tmp/.piocore-installer-SaQc3J/tmpPZZLKs/pioinstaller.zip/urllib3/util/__init__.py", line 7, in <module>
  File "/Users/bcrouch/.platformio/.cache/tmp/.piocore-installer-SaQc3J/tmpPZZLKs/pioinstaller.zip/urllib3/util/ssl_.py", line 9, in <module>
ImportError: cannot import name md5

	at /Users/bcrouch/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4911
	at ChildProcess.s (/Users/bcrouch/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4807)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Please install the latest Python 3 https://docs.platformio.org/en/latest/faq.html#install-python-interpreter and restart VSCode.
