### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by asconint2019** [platformio/platformio-core-installer#1189]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.59.1
  PIO IDE: v2.3.3
  System: Linux, 4.15.0-142-generic, x64

  %23 Exception
  ```
  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at cmd (/home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:187:25)
    at a (/home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:177:7)
    at options (/home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:162:3)
    at stderr (/home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:116:41)
    at /home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:183:42
    at new Promise (<anonymous>)
    at envClone (/home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:183:11)
    at withProgress (/home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/installer/get-platformio.js:110:14)
    at H.value (/home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/installer/stages/platformio-core.js:104:7)
    at t.default.install (/home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/dist/webpack:/platformio-ide/src/installer/manager.js:86:57)
    at /home/bilal/.vscode/extensions/platformio.platformio-ide-2.3.3/dist/webpack:/platformio-ide/src/main.js:209:36
  ```

**Comment by asconint2019** [comment]
Yes it did,Thanks.
