### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by justinVNN** [platformio/platformio-core-installer#1207]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Linux, 3.10.0-1160.42.2.el7.x86_64, x64

  %23 Exception
  ```
  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
	at /home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771328
	at a (/home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771222)
	at w (/home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:770973)
	at u (/home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:770497)
	at /home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771281
	at new Promise (<anonymous>)
	at l (/home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771260)
	at e.callInstallerScript (/home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:7153)
	at async H.value (/home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:763611)
	at async t.default.install (/home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/dist/extension.js:1:6711)
	at async /home/cadets/justin.nguyen/.vscode-server/extensions/platformio.platformio-ide-2.3.3/dist/extension.js:1:12714
  ```

**Comment by ivankravets** [comment]
Fixed in [PlatformIO IDE for VSCode v2.3.4](https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog). Please update PlatformIO IDE extension to the 2.3.4 version and restart VSCode.

Does it work for you now?
