### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by 7emotions** [platformio/platformio-core-installer#1236]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not import PlatformIO module. Error: 

	at c:\Users\Administrator\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771390
	at ChildProcess.a (c:\Users\Administrator\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771284)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\Administrator\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
