### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by mawarop** [platformio/platformio-core-installer#1256]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python39\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "C:\Python39\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Odmowa dost�pu
Traceback (most recent call last):
  File "C:\Users\opraw\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "C:\Users\opraw\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "C:\Users\opraw\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\pioinstaller\__main__.py", line 131, in main
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\click\core.py", line 1137, in __call__
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\click\core.py", line 1062, in main
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\click\core.py", line 1646, in invoke
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\click\core.py", line 1404, in invoke
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\click\core.py", line 763, in invoke
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\pioinstaller\core.py", line 67, in install_platformio_core
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\pioinstaller\core.py", line 95, in _install_platformio_core
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\pioinstaller\penv.py", line 71, in create_core_penv
  File "C:\Users\opraw\.platformio\.cache\tmp\.piocore-installer-zgfmdkw3\tmpsjjjwoot\pioinstaller.zip\pioinstaller\penv.py", line 141, in add_state_info
  File "C:\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] Parametr jest niepoprawny
 -> Installer version: 1.0.3
Platform: Windows-10
Python version: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Python39\python.exe
Creating a virtual environment at C:\Users\opraw\.platformio\penv

    at cmd (c:\Users\opraw\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:187:25)
    at ChildProcess.a (c:\Users\opraw\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:177:7)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at ChildProcess.cp.emit (c:\Users\opraw\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
