### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by joole** [platformio/platformio-core-installer#1302]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.56.1
  PIO IDE: v2.3.3
  System: Linux, 3.10.0-1160.el7.x86_64, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.0.3
Platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.26
Python version: 3.7.5 (default, Feb 23 2021, 13:22:40) 
[GCC 8.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /config/.platformio/penv
/usr/bin/python3

	at /config/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771328
	at ChildProcess.a (/config/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771222)
	at ChildProcess.emit (events.js:314:20)
	at ChildProcess.EventEmitter.emit (domain.js:483:12)
	at maybeClose (internal/child_process.js:1022:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
