### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by aleksandr23uam23** [platformio/platformio-core-installer#131]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.49.1
  PIO IDE: v2.1.0
  System: Windows_NT, 10.0.17763, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\User\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "C:\Users\User\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "C:\Users\User\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\pioinstaller\__main__.py", line 122, in main
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\click\core.py", line 829, in __call__
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\click\core.py", line 782, in main
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\click\core.py", line 1236, in invoke
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\click\core.py", line 1066, in invoke
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\click\core.py", line 610, in invoke
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\click\decorators.py", line 21, in new_func
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\pioinstaller\__main__.py", line 52, in cli
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\User\.platformio\.cache\tmp\.piocore-installer-lp8sc2qn\tmpagh_374p\pioinstaller.zip\pioinstaller\home.py", line 43, in shutdown_pio_home_servers
  File "C:\Users\User\.platformio\python3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\User\.platformio\python3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\User\.platformio\python3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\User\.platformio\python3\lib\multiprocessing\popen_spawn_win32.py", line 72, in __init__
    None, None, False, 0, env, None, None)
PermissionError: [WinError 5] �������� � �������
 -> Installer version: 0.3.5
Platform: Windows-10
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Python path: C:\Users\User\.platformio\python3\python.exe

	at c:\Users\User\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:4911
	at ChildProcess.s (c:\Users\User\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:4807)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.cp.emit (c:\Users\User\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by aleksandr23uam23** [comment]
Антивирус проблемой был.
