### ISSUE TITLE
Installation Manager: VS Code pio update and reinstall fails (glibc)

### ISSUE THREAD

**Issue by joba-1** [platformio/platformio-core-installer#132]
%23 Description of problem
  Pio update during vscode start fails -> no pio available :(
  Pio extension uninstall and reinstall fails, too. No coding today :((

There was no major update of my opensuse distro - not sure where this glibc change comes from or why it is a problem...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 
done (no mention of glibc)

  %23 Configuration

  VSCode: 1.49.1
  PIO IDE: v2.1.0
  System: Linux, 4.12.14-lp151.28.67-default, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO installed using another platform `Linux-4.12.14-lp151.28.67-default-x86_64-with-glibc2.2.5`. Your platform: Linux-4.12.14-lp151.28.67-default-x86_64-with-glibc2.3.4

	at /home/joachim/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4911
	at ChildProcess.s (/home/joachim/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4807)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by joba-1** [comment]
Strange: after ~5-8 attempts and VSCode restarts, pio is active again.
But VSCode continues to try to install pio extension at every start and fails with the same message.
