### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by TinkleDee** [platformio/platformio-core-installer#1348]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.1.0
  System: Windows_NT, 6.1.7601, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `C:\Users\DesignPC\.platformio\penv\Scripts\platformio.exe --version`.
Error: Error: Python 3.6 or later is required for this operation. 

Please check a migration guide:

https://docs.platformio.org/en/latest/core/migration.html%23drop-support-for-python-2-and-3-5



	at c:\Users\DesignPC\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:4911
	at ChildProcess.s (c:\Users\DesignPC\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:4807)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.cp.emit (c:\Users\DesignPC\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
