### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by jpolcek** [platformio/platformio-core-installer#1355]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Linux, 5.0.0-13-generic, x64

  %23 Exception
  ```
  Error: Error: Could not find compatible Python 3.6 or above in your system.Please install the latest official Python 3 and restart installation:
https://docs.platformio.org/page/faq.html%23install-python-interpreter
 -> Installer version: 1.0.3
Platform: Linux-5.0.0-13-generic-x86_64-with-glibc2.29
Python version: 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/jpolcek/.platformio/penv

    at cmd (/home/jpolcek/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:187:25)
    at ChildProcess.a (/home/jpolcek/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:177:7)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
