### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by DanylB** [platformio/platformio-core-installer#1360]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\bbogo\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "C:\Users\bbogo\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "C:\Users\bbogo\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 45, in bootstrap
    import pioinstaller.__main__
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\bbogo\.platformio\.cache\tmp\.piocore-installer-yt6r4e7d\tmpb87q_8l0\pioinstaller.zip\pioinstaller\__init__.py", line 15, in <module>
  File "C:\Users\bbogo\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 212, in <module>
    _lock = threading.RLock()
AttributeError: module 'threading' has no attribute 'RLock'
Exception ignored in: <module 'threading' from 'C:\\Users\\bbogo\\AppData\\Local\\Programs\\Python\\Python39\\lib\\threading.py'>
AttributeError: module 'threading' has no attribute '_shutdown'

	at c:\Users\bbogo\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771390
	at ChildProcess.a (c:\Users\bbogo\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771284)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\bbogo\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
