### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by GodayMax** [platformio/platformio-core-installer#1378]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Darwin, 20.1.0, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO Core version 4.0.3 does not match version requirements >=5.1.

	at /Users/Max-Goday/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771390
	at ChildProcess.a (/Users/Max-Goday/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771284)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at Pipe.<anonymous> (net.js:673:12)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
