### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by GDRPrint** [platformio/platformio-core-installer#1459]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Windows_NT, 10.0.18363, x64

  %23 Exception
  ```
  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
	at c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771390
	at a (c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771284)
	at w (c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771035)
	at u (c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:770559)
	at c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771343
	at new Promise (<anonymous>)
	at l (c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771322)
	at e.callInstallerScript (c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:7215)
	at async H.value (c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:763673)
	at async t.default.install (c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\dist\extension.js:1:6773)
	at async c:\Users\GDR Trading\.vscode\extensions\platformio.platformio-ide-2.3.3\dist\extension.js:1:12776
  ```

**Comment by GDRPrint** [comment]
I have uninstalled VS Code, installed Python, re-opened VS Code issue unresolved. Hoping for another solution, thanks for any help. VS Code working fine before latest update, 1.60.2

**Comment by GDRPrint** [comment]
Older versions of VS code report the same error when trying to add Platform IDE as extension.

**Comment by GDRPrint** [comment]
OK here is the tip some may be looking for:
Completely uninstall VS Code, instructions here : https://debug.to/1074/how-to-uninstall-vs-code-completely
Reload VS Code, close the program.
Install Python and BE SURE TO CHECK THE PATHWAYS CHECKBOX during install, very impt.
Open VS Code, add Platform ext, let it run until complete, close VS and restart.
Hope this helps someone along the way.
