### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by mikefinnan** [platformio/platformio-core-installer#1474]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\mike\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "C:\Users\mike\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "C:\Users\mike\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\pioinstaller\__main__.py", line 131, in main
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\click\core.py", line 1137, in __call__
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\click\core.py", line 1062, in main
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\click\core.py", line 1646, in invoke
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\click\core.py", line 1404, in invoke
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\click\core.py", line 763, in invoke
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\pioinstaller\core.py", line 67, in install_platformio_core
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\pioinstaller\core.py", line 95, in _install_platformio_core
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\pioinstaller\penv.py", line 71, in create_core_penv
  File "C:\Users\mike\.platformio\.cache\tmp\.piocore-installer-9x4n9c2w\tmp1cn9tqas\pioinstaller.zip\pioinstaller\penv.py", line 141, in add_state_info
  File "C:\Program Files\Inkscape\lib\python3.8\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Inkscape\lib\python3.8\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Inkscape\lib\python3.8\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Inkscape\lib\python3.8\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
 -> Installer version: 1.0.3
Platform: Windows-10
Python version: 3.8.5 (default, Sep  4 2020, 09:26:39)  [GCC 10.2.0 64 bit (AMD64)]
Python path: C:\Program Files\Inkscape\bin\python.exe
Creating a virtual environment at C:\Users\mike\.platformio\penv

	at c:\Users\mike\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771390
	at ChildProcess.a (c:\Users\mike\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771284)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\mike\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
