### ISSUE TITLE
Installation Manager - Traceback error - FileNotFoundError

### ISSUE THREAD

**Issue by Heptoxide** [platformio/platformio-core-installer#154]
**Description of problem**
New installation of platformIO with latest VS Code and Anaconda (64bit): get traceback error while trying to install.
Things tried so far:
* Uninstalling and reinstalling VS Code and Anaconda
* Deleting the platformIO working folder (C:\Users\wande\.platformio)
* Running VSCode as admin for installation

**Configuration**

  VSCode: 1.49.2
  PIO IDE: v2.1.0
  System: Windows_NT, 10.0.18362, x64

**Exception**
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\wande\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "C:\Users\wande\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "C:\Users\wande\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\pioinstaller\__main__.py", line 122, in main
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\click\core.py", line 829, in __call__
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\click\core.py", line 782, in main
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\click\core.py", line 1236, in invoke
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\click\core.py", line 1066, in invoke
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\click\core.py", line 610, in invoke
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\click\decorators.py", line 21, in new_func
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\pioinstaller\__main__.py", line 52, in cli
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\pioinstaller\penv.py", line 75, in create_core_penv
  File "C:\Users\wande\.platformio\.cache\tmp\.piocore-installer-iebc74hf\tmpiaghqzc7\pioinstaller.zip\pioinstaller\penv.py", line 144, in add_state_info
  File "C:\Users\wande\.platformio\python3\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\wande\.platformio\python3\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\wande\.platformio\python3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\wande\.platformio\python3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
 -> Installer version: 0.3.5
Platform: Windows-10
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Python path: C:\Users\wande\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\wande\.platformio\penv

	at c:\Users\wande\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:4911
	at ChildProcess.s (c:\Users\wande\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:4807)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.cp.emit (c:\Users\wande\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by Heptoxide** [comment]
Related to #130

**Comment by Heptoxide** [comment]
Related to #65 

Running the following in Windows Command Prompt
```
C:\Users\wande\.platformio\python3\python.exe C:\Users\wande\.platformio\.cache\tmp\get-platformio-0.3.5.py
```

Output:
```
C:\Users>C:\Users\wande\.platformio\python3\python.exe C:\Users\wande\.platformio\.cache\tmp\get-platformio-0.3.5.py
Installer version: 0.3.5
Platform: Windows-10
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Python path: C:\Users\wande\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\wande\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Downloading platformio-5.0.1.tar.gz (211 kB)
     |████████████████████████████████| 211 kB 1.7 MB/s
Collecting bottle<0.13
  Downloading bottle-0.12.18-py3-none-any.whl (89 kB)
     |████████████████████████████████| 89 kB 1.8 MB/s
Collecting click!=7.1,!=7.1.1,<8,>=5
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 6.1 MB/s
Collecting colorama
  Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting pyserial!=3.3,<4,>=3
  Using cached pyserial-3.4-py2.py3-none-any.whl (193 kB)
Collecting requests<3,>=2.4.0
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 4.5 MB/s
Collecting semantic_version<3,>=2.8.1
  Downloading semantic_version-2.8.5-py2.py3-none-any.whl (15 kB)
Collecting tabulate<1,>=0.8.3
  Downloading tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting pyelftools<1,>=0.25
  Downloading pyelftools-0.26-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 6.8 MB/s
Collecting marshmallow>=2
  Downloading marshmallow-3.8.0-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 1.7 MB/s
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 6.8 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB ...
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB ...
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 3.8 MB/s
Building wheels for collected packages: platformio
  Building wheel for platformio (setup.py) ... done
  Created wheel for platformio: filename=platformio-5.0.1-py3-none-any.whl size=328103 sha256=6f153534566ca5d258e47e2bda5b4ed3f16c07edc192018500210946f2893883
  Stored in directory: c:\users\wande\appdata\local\pip\cache\wheels\14\67\d1\514a8d3bceee0a64c409c7810fe64295c3c2561d73eaa90b8d
Successfully built platformio
Installing collected packages: bottle, click, colorama, pyserial, chardet, certifi, urllib3, idna, requests, semantic-version, tabulate, pyelftools, marshmallow, platformio
Successfully installed bottle-0.12.18 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 colorama-0.4.3 idna-2.10 marshmallow-3.8.0 platformio-5.0.1 pyelftools-0.26 pyserial-3.4 requests-2.24.0 semantic-version-2.8.5 tabulate-0.8.7 urllib3-1.25.10

PlatformIO Core has been successfully installed into an isolated environment `C:\Users\wande\.platformio\penv`!

The full path to `platformio.exe` is `C:\Users\wande\.platformio\penv\Scripts\platformio.exe`

If you need an access to `platformio.exe` from other applications, please install Shell Commands
(add PlatformIO Core binary directory `C:\Users\wande\.platformio\penv\Scripts` to the system environment PATH variable):

See https://docs.platformio.org/page/installation.html#install-shell-commands
```

**Comment by Heptoxide** [comment]
Added the scripts to user path:
```
C:\Users\wande\.platformio\penv\Scripts
```

**Comment by Heptoxide** [comment]
Restarted VSCode and it worked
[Solution is to manually execute installation py script with platformio python executable](https://github.com/platformio/platformio-core-installer/issues/154#issuecomment-699666575)
