### ISSUE TITLE
Installation Manager - Error installing on Windows [SOLVED]

### ISSUE THREAD

**Issue by nyckidryan** [platformio/platformio-core-installer#1540]
%23 Description of problem

1. URL below, "before submitting, please search..." does not work. 404.
2. Fresh install of VSCode
3. Fresh install of PlatformIO
4. 47GB free space

"OUTPUT" tab
```
Installing PlatformIO IDE...
It may take a few minutes depending on your connection speed
Please do not close this window and do not open other folders until this process is completed.

Debugging information is available via VSCode > Help > Toggle Developer Tools > Console.
Failed to install PlatformIO IDE.

```

Console shows streams of errors: 

`[Extension Host] RequestError: certificate has expired
	at ClientRequest.<anonymous> (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\got\dist\source\core\index.js:956:111)
	at Object.onceWrapper (events.js:422:26)
	at ClientRequest.emit (events.js:327:22)
	at ClientRequest.EventEmitter.emit (domain.js:467:12)
	at ClientRequest.origin.emit (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket.EventEmitter.emit (domain.js:467:12)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket.EventEmitter.emit (domain.js:467:12)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
`

`Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null 	at d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771390 	at a (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771284) 	at w (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771035) 	at u (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:770559) 	at d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node...
`
  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Windows_NT, 10.0.16299, x64

  %23 Exception
  ```
  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
	at d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771390
	at a (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771284)
	at w (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771035)
	at u (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:770559)
	at d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771343
	at new Promise (<anonymous>)
	at l (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771322)
	at e.callInstallerScript (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:7215)
	at async H.value (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:763673)
	at async t.default.install (d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\dist\extension.js:1:6773)
	at async d:\Users\ryan\.vscode\extensions\platformio.platformio-ide-2.3.3\dist\extension.js:1:12776
  ```

**Comment by nyckidryan** [comment]
The solution is to upgrade your Python installation to the current release, at this time 3.10.

- Remove PlatformIO
- Exit VSCode
- Download the [Windows installer](https://www.python.org/downloads/release/python-3100/) _(download links are at the **end of the page**)_
- Install Python and be sure to check the box that says "Add to path"
- Restart VSCode
- Reinstall PlatformIO
