### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by saitros** [platformio/platformio-core-installer#1627]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Linux, 4.4.0-176-generic, x64

  %23 Exception
  ```
  Error: Error: Could not find compatible Python 3.6 or above in your system.Please install the latest official Python 3 and restart installation:
https://docs.platformio.org/page/faq.html%23install-python-interpreter
 -> Installer version: 1.0.3
Platform: Linux-4.4.0-176-generic-x86_64-with-glibc2.9
Python version: 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) 
[GCC 7.3.0]
Python path: /home/ubuntu/anaconda3/bin/python3
Creating a virtual environment at /home/ubuntu/.platformio/penv

	at /home/ubuntu/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771328
	at ChildProcess.a (/home/ubuntu/.vscode-server/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771222)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Fixed in [PlatformIO IDE for VSCode v2.3.4](https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog). Please update PlatformIO IDE extension to the 2.3.4 version and restart VSCode.

Does it work for you now?
