### ISSUE TITLE
Installation fails with error "path argument must be of type string. Received null"

### ISSUE THREAD

**Issue by btw04** [platformio/platformio-core-installer#1649]
%23 Description of problem
  It seems like a lot of people are having this problem, and it seems to be a problem with the Python version. But I'm running Python 3.9.7, so that shouldn't be the problem here. VS Code is also started with adminstration privileges
%23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
	at c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771390
	at a (c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771284)
	at w (c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771035)
	at u (c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:770559)
	at c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771343
	at new Promise (<anonymous>)
	at l (c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771322)
	at e.callInstallerScript (c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:7215)
	at async H.value (c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:763673)
	at async t.default.install (c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\dist\extension.js:1:6773)
	at async c:\Users\<Name>\.vscode\extensions\platformio.platformio-ide-2.3.3\dist\extension.js:1:12776
  ```

**Comment by btw04** [comment]
After trying some things I managed to resolve this issue. The Python installation   I installed via the Windows Store seems to have caused the issue, after installing Python 3.10 manually it worked fine.
