### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by jevey** [platformio/platformio-core-installer#1736]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.1
  PIO IDE: v2.3.3
  System: Darwin, 20.6.0, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/Users/Jevey/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "/Users/Jevey/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "/Users/Jevey/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/pioinstaller/__main__.py", line 131, in main
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/click/core.py", line 1137, in __call__
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/click/core.py", line 1062, in main
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/click/core.py", line 1646, in invoke
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/click/core.py", line 1404, in invoke
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/click/core.py", line 763, in invoke
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/click/decorators.py", line 26, in new_func
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/pioinstaller/__main__.py", line 61, in cli
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/pioinstaller/core.py", line 70, in install_platformio_core
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/pioinstaller/core.py", line 95, in _install_platformio_core
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/pioinstaller/penv.py", line 71, in create_core_penv
  File "/Users/Jevey/.platformio/.cache/tmp/.piocore-installer-g_8uaq_w/tmp4zsrqsu2/pioinstaller.zip/pioinstaller/penv.py", line 142, in add_state_info
  File "/Users/Jevey/anaconda3/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/Users/Jevey/anaconda3/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/Jevey/anaconda3/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/Users/Jevey/anaconda3/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Jevey/.platformio/penv/bin/python': '/Users/Jevey/.platformio/penv/bin/python'
 -> Installer version: 1.0.3
Platform: Darwin-20.6.0
Python version: 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 12:58:59) 
[GCC Clang 10.0.0 ]
Python path: /Users/Jevey/anaconda3/bin/python3
Creating a virtual environment at /Users/Jevey/.platformio/penv

	at /Users/Jevey/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771390
	at ChildProcess.a (/Users/Jevey/.vscode/extensions/platformio.platformio-ide-2.3.3/node_modules/platformio-node-helpers/dist/index.js:1:771284)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Fixed in [PlatformIO IDE for VSCode v2.3.4](https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog). Please update PlatformIO IDE extension to the 2.3.4 version and restart VSCode.

Does it work for you now?
