### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by TheStami** [platformio/platformio-core-installer#177]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.49.3
  PIO IDE: v2.1.0
  System: Linux, 5.4.0-48-generic, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 0.3.5
Platform: Linux-5.4.0-48-generic-x86_64-with-glibc2.25
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/a15/.platformio/penv

	at /home/a15/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4911
	at ChildProcess.s (/home/a15/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4807)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
  ```

**Comment by TheStami** [comment]
Okay,
For me help reinstall PlatformIO extension **with remove ~/.platformio folder**. Uninstallation in VS Code doesn't delete this folder, but that's where the problem lies.
(Sorry for my English if I made mistakes)
