### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by soaref22** [platformio/platformio-core-installer#1775]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.57.1
  PIO IDE: v2.3.4
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: Can not find Python Interpreter. Please install Python 3.6 or above manually
	at H.value (c:\Users\admin\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:765899)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async H.value (c:\Users\admin\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:764349)
	at async t.default.install (c:\Users\admin\.vscode\extensions\platformio.platformio-ide-2.3.4\dist\extension.js:1:6773)
	at async c:\Users\admin\.vscode\extensions\platformio.platformio-ide-2.3.4\dist\extension.js:1:12776
  ```

**Comment by ivankravets** [comment]
See the solution in https://github.com/platformio/platformio-core-installer/issues/1774
