### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'name'

### ISSUE THREAD

**Issue by LIHUAWRITER** [platformio/platformio-core-installer#1778]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\pioinstaller\__main__.py", line 131, in main
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\click\core.py", line 1137, in __call__
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\click\core.py", line 1062, in main
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\click\core.py", line 1646, in invoke
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\click\core.py", line 1404, in invoke
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\click\core.py", line 763, in invoke
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\pioinstaller\core.py", line 67, in install_platformio_core
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\pioinstaller\core.py", line 95, in _install_platformio_core
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\pioinstaller\penv.py", line 58, in create_core_penv
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\pioinstaller\python.py", line 70, in fetch_portable_python
  File "C:\Users\HUAWEI\.platformio\.cache\tmp\.piocore-installer-kmjc_g_i\tmp5lg9tgzl\pioinstaller.zip\pioinstaller\python.py", line 109, in get_portable_python_url
AttributeError: 'dict' object has no attribute 'name'
 -> Installer version: 1.0.3
Platform: Windows-10
Python version: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Python path: D:\python3.8.6\python.exe
Creating a virtual environment at C:\Users\HUAWEI\.platformio\penv
D:\python3.8.6\python.exe

	at c:\Users\HUAWEI\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:769806
	at ChildProcess.a (c:\Users\HUAWEI\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:771396)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\HUAWEI\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core-installer/commit/5939924001bd6dc1c6893581a8f17fa73894d692
