### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by xudesheng** [platformio/platformio-core-installer#1781]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Darwin, 20.6.0, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/Users/xxx/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "/Users/xxx/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "/Users/xxx/.platformio/.cache/tmp/get-platformio-1.0.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/pioinstaller/__main__.py", line 131, in main
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/click/core.py", line 1137, in __call__
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/click/core.py", line 1062, in main
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/click/core.py", line 1646, in invoke
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/click/core.py", line 1404, in invoke
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/click/core.py", line 763, in invoke
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/click/decorators.py", line 26, in new_func
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/pioinstaller/__main__.py", line 61, in cli
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/pioinstaller/core.py", line 67, in install_platformio_core
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/pioinstaller/core.py", line 95, in _install_platformio_core
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/pioinstaller/penv.py", line 71, in create_core_penv
  File "/Users/xxx/.platformio/.cache/tmp/.piocore-installer-7tbwwykw/tmpsxfd4ypl/pioinstaller.zip/pioinstaller/penv.py", line 141, in add_state_info
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/.platformio/penv/bin/python'
 -> Installer version: 1.0.3
Platform: macOS-11.6
Python version: 3.8.9 (default, Aug 21 2021, 15:53:23) 
[Clang 13.0.0 (clang-1300.0.29.3)]
Python path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
Creating a virtual environment at /Users/xxx/.platformio/penv

    at /Users/xxx/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:187:25
    at ChildProcess.a (/Users/xxx/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:771396)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12)
  ```

**Comment by ivankravets** [comment]
_Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?_
