### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by hsl416604093** [platformio/platformio-core-installer#1782]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Linux, 5.11.0-40-generic, x64

  %23 Exception
  ```
  Error: Can not find Python Interpreter. Please install Python 3.6 or above manually
	at H.value (/home/lodge/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:765899)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async H.value (/home/lodge/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:764349)
	at async t.default.install (/home/lodge/.vscode/extensions/platformio.platformio-ide-2.3.4/dist/extension.js:1:6773)
	at async /home/lodge/.vscode/extensions/platformio.platformio-ide-2.3.4/dist/extension.js:1:12776
  ```

**Comment by ivankravets** [comment]
See the solution in https://github.com/platformio/platformio-core-installer/issues/1774
