### ISSUE TITLE
Installation Manager - Python3 is installed already but installer does not recognise it

### ISSUE THREAD

**Issue by electrojit** [platformio/platformio-core-installer#1783]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Linux, 5.11.0-38-generic, x64

  %23 Exception
  ```
  Error: Can not find Python Interpreter. Please install Python 3.6 or above manually
	at H.value (/home/alien/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:765899)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async H.value (/home/alien/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:764349)
	at async t.default.install (/home/alien/.vscode/extensions/platformio.platformio-ide-2.3.4/dist/extension.js:1:6773)
	at async /home/alien/.vscode/extensions/platformio.platformio-ide-2.3.4/dist/extension.js:1:12776
  ```

**Comment by Slushee-a** [comment]
Have you figured it out? There are a lot of issues for this but no one has replied with any fix and they are all closed.

**Comment by Slushee-a** [comment]
It spits out this error but what it actually has missing isn't python3.8. It is missing python3-venv, because for some reason it doesn't come with ubuntu (and it's different flavors). You just have to do `sudo apt install python3-venv` in your terminal and restart vs code. Try installing Platform IO again and it should suceed.

**Comment by ivankravets** [comment]
See the solution in https://github.com/platformio/platformio-core-installer/issues/1774
