### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by SaturdayScience** [platformio/platformio-core-installer#1786]
%23 Description of problem
  1) The installation fails as  the script believes Python is not installed; but Python3.10 is installed.
2) The page pointed to below does not exist Error 404

Apologies if this problem has already been submitted

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Linux, 5.4.0-89-generic, x64

  %23 Exception
  ```
  Error: Can not find Python Interpreter. Please install Python 3.6 or above manually
	at H.value (/home/mike/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:765899)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async H.value (/home/mike/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:764349)
	at async t.default.install (/home/mike/.vscode/extensions/platformio.platformio-ide-2.3.4/dist/extension.js:1:6773)
	at async /home/mike/.vscode/extensions/platformio.platformio-ide-2.3.4/dist/extension.js:1:12776
  ```
![PythonIsInstalled](https://user-images.githubusercontent.com/61949600/138823536-52d0ba28-00b7-40a9-8e8c-96700149deb5.png)

**Comment by ivankravets** [comment]
See the solution in https://github.com/platformio/platformio-core-installer/issues/1774
