### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by nihaoshunyi2019** [platformio/platformio-core-installer#1790]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.4
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\shunyi\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "C:\Users\shunyi\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "C:\Users\shunyi\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\pioinstaller\__main__.py", line 131, in main
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\click\core.py", line 1137, in __call__
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\click\core.py", line 1062, in main
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\click\core.py", line 1668, in invoke
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\click\core.py", line 1668, in invoke
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\click\core.py", line 1404, in invoke
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\click\core.py", line 763, in invoke
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\pioinstaller\__main__.py", line 112, in core_check
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\pioinstaller\core.py", line 168, in check
  File "C:\Users\shunyi\.platformio\.cache\tmp\.piocore-installer-3ygp9t7n\tmpu2l0e9vi\pioinstaller.zip\pioinstaller\core.py", line 283, in fetch_python_state
  File "D:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

	at c:\Users\shunyi\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:769806
	at ChildProcess.a (c:\Users\shunyi\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:771396)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\shunyi\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
