### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by MorkM** [platformio/platformio-core-installer#1797]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: Can not find Python Interpreter. Please install Python 3.6 or above manually
    at H.value (c:\Users\Maddin-PC\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\installer\stages\platformio-core.js:195:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at H.value (c:\Users\Maddin-PC\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\installer\stages\platformio-core.js:109:20)
    at t.default.install (c:\Users\Maddin-PC\.vscode\extensions\platformio.platformio-ide-2.3.4\dist\webpack:\platformio-ide\src\installer\manager.js:86:57)
    at c:\Users\Maddin-PC\.vscode\extensions\platformio.platformio-ide-2.3.4\dist\webpack:\platformio-ide\src\main.js:209:36
  ```

**Comment by ivankravets** [comment]
See solution in https://github.com/platformio/platformio-core-installer/issues/1774
