### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ligenxxxx** [platformio/platformio-core-installer#1798]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Linux, 5.11.0-38-generic, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an EnvironmentError: Missing dependencies for SOCKS support.

Error: Could not install PlatformIO Core: Command '['/home/ligen/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.0.3
Platform: Linux-5.11.0-38-generic-x86_64-with-glibc2.29
Python version: 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/ligen/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at /home/ligen/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:769806
	at ChildProcess.a (/home/ligen/.vscode/extensions/platformio.platformio-ide-2.3.4/node_modules/platformio-node-helpers/dist/index.js:1:771396)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
