### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Avelle1** [platformio/platformio-core-installer#1800]
%23 Description of problem
 trying to install platformIO IDE, on Visual Studio Code, but for some unknown reason it won't install the PlatformIO core, my firewall and windows defender are disabled, but I am still getting the same error. please help me, I need this for a college project that I'm doing and I'm stuck on what to do since i can't use PlatformIO.

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.61.2
  PIO IDE: v2.3.4
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an EnvironmentError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Program Files\Total Defense\Internet Security Suite\Anti-Phishing

Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\mario\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.0.3
Platform: Windows-10
Python version: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Python path: C:\Users\mario\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\mario\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at c:\Users\mario\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:769806
	at ChildProcess.a (c:\Users\mario\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:771396)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\mario\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
