### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by cc70458** [platformio/platformio-core-installer#1802]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.60.2
  PIO IDE: v2.3.3
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\linux\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 69, in <module>
    main()
  File "C:\Users\linux\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 61, in main
    bootstrap()
  File "C:\Users\linux\.platformio\.cache\tmp\get-platformio-1.0.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\pioinstaller\__main__.py", line 131, in main
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\click\core.py", line 1137, in __call__
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\click\core.py", line 1062, in main
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\click\core.py", line 1646, in invoke
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\click\core.py", line 1404, in invoke
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\click\core.py", line 763, in invoke
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\pioinstaller\core.py", line 95, in _install_platformio_core
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\pioinstaller\penv.py", line 71, in create_core_penv
  File "C:\Users\linux\.platformio\.cache\tmp\.piocore-installer-bisfjdrd\tmpd4a9vvh8\pioinstaller.zip\pioinstaller\penv.py", line 142, in add_state_info
  File "d:\Users\linux\anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "d:\Users\linux\anaconda3\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "d:\Users\linux\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "d:\Users\linux\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
 -> Installer version: 1.0.3
Platform: Windows-10
Python version: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Python path: d:\Users\linux\anaconda3\python.exe
Creating a virtual environment at C:\Users\linux\.platformio\penv

	at c:\Users\linux\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771390
	at ChildProcess.a (c:\Users\linux\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\platformio-node-helpers\dist\index.js:1:771284)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\linux\.vscode\extensions\platformio.platformio-ide-2.3.3\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode to the latest 1.62.0 or above version, and install the latest (2.4.0 or above) PlatformIO IDE extension. See https://marketplace.visualstudio.com/items/platformio.platformio-ide/changelog

Does it work now?
