### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by fmabellan** [platformio/platformio-core-installer#1839]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.62.3
  PIO IDE: v2.4.0
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: ERROR: Exception:
Traceback (most recent call last):
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\cli\base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\commands\install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\.platformio\penv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\.platformio\penv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 349, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\.platformio\penv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\.platformio\penv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 281, in __init__
    super().__init__(
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\operations\prepare.py", line 546, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\operations\prepare.py", line 59, in _get_prepared_distribution
    return abstract_dist.get_metadata_distribution()
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\distributions\wheel.py", line 26, in get_metadata_distribution
    return get_wheel_distribution(wheel, canonicalize_name(self.req.name))
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\metadata\__init__.py", line 51, in get_wheel_distribution
    return Distribution.from_wheel(wheel, canonical_name)
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 37, in from_wheel
    with wheel.as_zipfile() as zf:
  File "C:\.platformio\penv\lib\site-packages\pip\_internal\metadata\base.py", line 321, in as_zipfile
    return zipfile.ZipFile(self.location, allowZip64=True)
  File "C:\.platformio\python3\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "C:\.platformio\python3\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 2.
 -> Installer version: 1.1.0
Platform: Windows-10
Python version: 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)]
Python path: C:\.platformio\python3\python.exe
Creating a virtual environment at C:\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Using cached platformio-5.2.3-py3-none-any.whl

	at c:\Users\fmabe\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\platformio-node-helpers\dist\index.js:1:5240
	at ChildProcess.r (c:\Users\fmabe\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\platformio-node-helpers\dist\index.js:1:5134)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\fmabe\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by fmabellan** [comment]
PlatformIO was installed and working on VSC.
It stopped showing the PlatformIO icon on letf bar of the screen, not being able to open projects.
I uninstalled everything (inc. VSC) and reinstalled it, but got this error when installing PlatformIO again.
Firewall & antivirus (defender) disabled and python aliases disabled. Also tried installing on c:\.platformio instead of c:\users\%userid%\.platformio
I can't install PlatformIO!!
