### ISSUE TITLE
vscode extension PlatformIO hangs at "Installing PlatformIO Core"

### ISSUE THREAD

**Issue by mightycoco** [platformio/platformio-core-installer#1852]
Windows 10 64bit
Python installed in c:\python310\python.exe and added to env path

VSCode settings.json has
```
"python.defaultInterpreterPath": "C:\\Python310\\python.exe",
"platformio-ide.useBuiltinPython": false
```

Python Extension hangs at "Installing PlatformIO Core"

Extension Host error
```
Error:   File "C:\Users\xxx\.platformio\.cache\tmp\get-platformio-1.1.0.py", line 24
    DEPENDENCIES = b"""
                   ^
SyntaxError: unterminated triple-quoted string literal (detected at line 25)

	at c:\Users\xxx\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\platformio-node-helpers\dist\index.js:1:5240
	at ChildProcess.r (c:\Users\xxx\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\platformio-node-helpers\dist\index.js:1:5134)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\xxx\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by mightycoco** [comment]
I needed to clear out the C:\Users\xxx\.platformio\.cache\tmp folder and restarting VSCode.
