### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by gifhuppp** [platformio/platformio-core-installer#1855]
`%23` Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.63.0
  PIO IDE: v2.4.0
  System: Windows_NT, 10.0.22000, x64

  %23 Exception
  ```
  Error: Could not find compatible PlatformIO Core. Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.
    at a.progress (c:\Users\hazme\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\installer\stages\platformio-core.js:150:9)
    at S.install (c:\Users\hazme\.vscode\extensions\platformio.platformio-ide-2.4.0\dist\webpack:\platformio-ide\src\installer\manager.js:90:5)
    at c:\Users\hazme\.vscode\extensions\platformio.platformio-ide-2.4.0\dist\webpack:\platformio-ide\src\main.js:209:36
    at S._withProgress (c:\Users\hazme\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45568)
    at S.withProgress (c:\Users\hazme\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45322)
    at Object.title [as withProgress] (c:\Users\hazme\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30872)
    at Object.startInstaller (c:\Users\hazme\.vscode\extensions\platformio.platformio-ide-2.4.0\dist\webpack:\platformio-ide\src\main.js:184:9)
    at process.handleUseDevelopmentPIOCoreConfiguration (internal/process/task_queues.js:93:5)
    at Object.activate (c:\Users\hazme\.vscode\extensions\platformio.platformio-ide-2.4.0\dist\webpack:\platformio-ide\src\main.js:61:34)
  ```

**Comment by gifhuppp** [comment]
ายละเอียดของปัญหา
ทิ้งข้อความไว้...
