### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ExiterOne** [platformio/platformio-core-installer#1881]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.63.2
  PIO IDE: v2.4.0
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\Howug\.platformio\python3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Howug\.platformio\python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Howug\.platformio\penv\lib\site-packages\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\Howug\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.0
Platform: Windows-10
Python version: 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\Howug\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\Howug\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at c:\Users\Howug\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\platformio-node-helpers\dist\index.js:1:5240
	at ChildProcess.r (c:\Users\Howug\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\platformio-node-helpers\dist\index.js:1:5134)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\Howug\.vscode\extensions\platformio.platformio-ide-2.4.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by hmf** [comment]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.63.2
  PIO IDE: v2.4.0
  System: Linux, 5.11.0-44-generic, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/home/hmf/.platformio/.cache/tmp/get-platformio-1.1.0.py", line 69, in <module>
    main()
  File "/home/hmf/.platformio/.cache/tmp/get-platformio-1.1.0.py", line 61, in main
    bootstrap()
  File "/home/hmf/.platformio/.cache/tmp/get-platformio-1.1.0.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/pioinstaller/__main__.py", line 133, in main
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/click/core.py", line 1128, in __call__
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/click/core.py", line 1053, in main
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/click/core.py", line 1637, in invoke
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/click/core.py", line 1395, in invoke
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/click/core.py", line 754, in invoke
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/click/decorators.py", line 26, in new_func
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/pioinstaller/__main__.py", line 61, in cli
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/pioinstaller/core.py", line 70, in install_platformio_core
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/pioinstaller/core.py", line 98, in _install_platformio_core
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/pioinstaller/penv.py", line 71, in create_core_penv
  File "/home/hmf/.platformio/.cache/tmp/.piocore-installer-fpntyp75/tmpjny852r8/pioinstaller.zip/pioinstaller/penv.py", line 141, in init_state
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/hmf/.platformio/penv/bin/python'
 -> Installer version: 1.1.0
Platform: Linux-5.11.0-44-generic-x86_64-with-glibc2.29
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/hmf/.platformio/penv

	at /home/hmf/.vscode/extensions/platformio.platformio-ide-2.4.0/node_modules/platformio-node-helpers/dist/index.js:1:5240
	at ChildProcess.r (/home/hmf/.vscode/extensions/platformio.platformio-ide-2.4.0/node_modules/platformio-node-helpers/dist/index.js:1:5134)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at Pipe.<anonymous> (net.js:673:12)
  ```
