### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by zhangmx** [platformio/platformio-core-installer#1883]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.63.2
  PIO IDE: v2.4.0
  System: Darwin, 21.2.0, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `/Users/mingxing/.platformio/penv/bin/platformio --version`.
Error: Traceback (most recent call last):
  File "/Users/mingxing/.platformio/penv/bin/platformio", line 5, in <module>
    from platformio.__main__ import main
  File "/Users/mingxing/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py", line 13, in <module>
    from platformio import __version__, exception, maintenance
  File "/Users/mingxing/.platformio/penv/lib/python3.8/site-packages/platformio/maintenance.py", line 13, in <module>
    from platformio import __version__, app, exception, telemetry
  File "/Users/mingxing/.platformio/penv/lib/python3.8/site-packages/platformio/app.py", line 13, in <module>
    from platformio.util import get_home_dir, is_ci
  File "/Users/mingxing/.platformio/penv/lib/python3.8/site-packages/platformio/util.py", line 50
    print line
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(line)%3F


	at /Users/mingxing/.vscode/extensions/platformio.platformio-ide-2.4.0/node_modules/platformio-node-helpers/dist/index.js:1:5240
	at ChildProcess.r (/Users/mingxing/.vscode/extensions/platformio.platformio-ide-2.4.0/node_modules/platformio-node-helpers/dist/index.js:1:5134)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by zhangmx** [comment]
Why the installer download lowest version of platformio?

I installed platformio cli by brew. the installer can not find existed platformio?

```
[Extension Host] Installer version: 1.1.0
Platform: macOS-12.1
Python version: 3.8.9 (default, Oct 26 2021, 07:25:54) 
[Clang 13.0.0 (clang-1300.0.29.30)]
Python path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
Creating a virtual environment at /Users/mingxing/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: http://pypi.douban.com/simple
Collecting platformio
  Downloading http://pypi.doubanio.com/packages/5f/15/607b673…/platformio-5.2.4.tar.gz (219 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting bottle==0.12.*
  Downloading http://pypi.doubanio.com/packages/bf/44/aeafdd6…/bottle-0.12.19-py3-none-any.whl (89 kB)
Collecting click!=8.0.2,<9,>=8
  Downloading http://pypi.doubanio.com/packages/48/58/c8aa6a8…/click-8.0.3-py3-none-any.whl (97 kB)
Collecting colorama
  Downloading http://pypi.doubanio.com/packages/44/98/5b86278…/colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting marshmallow<4,>=2
  Downloading http://pypi.doubanio.com/packages/ec/f3/6201568…/marshmallow-3.14.1-py3-none-any.whl (47 kB)
Collecting pyelftools<1,>=0.27
  Downloading http://pypi.doubanio.com/packages/6f/50/3d7729d…/pyelftools-0.27-py2.py3-none-any.whl (151 kB)
Collecting pyserial==3.*
  Downloading http://pypi.doubanio.com/packages/07/bc/587a445…/pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting requests==2.*
  Downloading http://pypi.doubanio.com/packages/47/01/f420e7a…/requests-2.27.0-py2.py3-none-any.whl (63 kB)
Collecting platformio
  Downloading http://pypi.doubanio.com/packages/47/6a/b017d99…/platformio-5.2.3.tar.gz (218 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/8a/e4/efc60be…/platformio-5.2.2.tar.gz (218 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/1a/48/cfaa9aa…/platformio-5.2.1.tar.gz (218 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/30/42/fbec5a2…/platformio-5.2.0.tar.gz (217 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/b8/f0/4e99413…/platformio-5.1.1.tar.gz (215 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting click<8,>=5
  Downloading http://pypi.doubanio.com/packages/d2/3d/fa76db8…/click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting platformio
  Downloading http://pypi.doubanio.com/packages/b2/68/63ed6a1…/platformio-5.1.0.tar.gz (214 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/ac/75/cf0307f…/platformio-5.0.4.tar.gz (213 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/d8/7b/a792803…/platformio-5.0.3.tar.gz (213 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/c5/08/2773948…/platformio-5.0.2.tar.gz (212 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/38/6e/81a76ed…/platformio-5.0.1.tar.gz (211 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/81/8a/b4d1704…/platformio-5.0.0.tar.gz (240 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/af/7a/07e5fa6…/platformio-4.3.4.tar.gz (190 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/84/30/fbeab6f…/platformio-4.3.3.tar.gz (187 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/c9/52/4a0a630…/platformio-4.3.2.tar.gz (187 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/15/58/49a7134…/platformio-4.3.1.tar.gz (169 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/0d/cd/6e7a07f…/platformio-4.3.0.tar.gz (168 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/f4/c8/8e472c2…/platformio-4.2.1.tar.gz (170 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/31/6b/6050e99…/platformio-4.2.0.tar.gz (169 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/b5/b6/832b921…/platformio-4.1.0.tar.gz (157 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/5d/59/2ba54e3…/platformio-4.0.3.tar.gz (140 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/42/d7/0e39cc1…/platformio-4.0.2.tar.gz (140 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/ad/6b/6d42601…/platformio-4.0.1.tar.gz (140 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/c6/a3/43c6cc3…/platformio-4.0.0.tar.gz (139 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Downloading http://pypi.doubanio.com/packages/dc/19/b92d62f…/platformio-3.6.7.tar.gz (113 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/66/41/797ee14…/platformio-3.6.6.tar.gz (113 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/f1/92/202b47e…/platformio-3.6.5.tar.gz (112 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/ee/4d/500a1fa…/platformio-3.6.4.tar.gz (111 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/8c/d0/99da2ec…/platformio-3.6.3.tar.gz (111 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/e2/86/40bcb28…/platformio-3.6.2.tar.gz (111 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/12/7a/02a773b…/platformio-3.6.1.tar.gz (111 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/19/ba/7a25560…/platformio-3.6.0.tar.gz (99 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/79/a5/e12f61c…/platformio-3.5.4.tar.gz (97 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/eb/6f/378c272…/platformio-3.5.3.tar.gz (96 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/7c/95/899efc1…/platformio-3.5.2.tar.gz (95 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/a4/34/c8a8ea8…/platformio-3.5.1.tar.gz (92 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/a8/e9/d052018…/platformio-3.5.0.tar.gz (91 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/e2/de/ede21c6…/platformio-3.4.1.tar.gz (87 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/89/5c/e04c950…/platformio-3.4.0.tar.gz (87 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/a9/c1/3b20a3e…/platformio-3.3.1.tar.gz (86 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/97/02/58c93ca…/platformio-3.3.0.tar.gz (86 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/01/29/5720a51…/platformio-3.2.1.tar.gz (81 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/50/d1/2d68687…/platformio-3.2.0.tar.gz (81 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/b1/16/b74f0d0…/platformio-3.1.0.tar.gz (76 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/8b/55/4567333…/platformio-3.0.1.tar.gz (74 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/a6/16/c7c818e…/platformio-3.0.0.tar.gz (74 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/6e/09/204d1e5…/platformio-2.11.2.tar.gz (102 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/31/d9/9d06e2b…/platformio-2.11.1.tar.gz (101 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/71/76/05dd805…/platformio-2.11.0.tar.gz (102 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/b7/a3/1d3a9d7…/platformio-2.10.3.tar.gz (101 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/eb/20/dcc467c…/platformio-2.10.2.tar.gz (101 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/7c/f1/77b5243…/platformio-2.10.1.tar.gz (100 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/22/65/254fc55…/platformio-2.10.0.tar.gz (102 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/4e/29/49972ba…/platformio-2.9.4.tar.gz (100 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/f8/f6/73438a8…/platformio-2.9.3.tar.gz (100 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/b2/8e/bc075a0…/platformio-2.9.2.tar.gz (100 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/4e/c6/fa03609…/platformio-2.9.1.tar.gz (100 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/2d/8e/e50f1ef…/platformio-2.9.0.tar.gz (100 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/98/13/f6cc5c5…/platformio-2.8.6.tar.gz (92 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/68/b7/7de9bef…/platformio-2.8.5.tar.gz (91 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/a2/d7/5dfaf2b…/platformio-2.8.4.tar.gz (90 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/9d/ad/c04ae42…/platformio-2.8.3.tar.gz (89 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/c6/f3/506f979…/platformio-2.8.2.tar.gz (89 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/aa/9a/9e0eac0…/platformio-2.8.1.tar.gz (89 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/bd/03/da30d54…/platformio-2.8.0.tar.gz (89 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/d6/6d/f0b61cc…/platformio-2.7.1.tar.gz (87 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/e5/d1/ffb71c7…/platformio-2.7.0.tar.gz (86 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/e7/61/4f0230f…/platformio-2.6.3.tar.gz (85 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/ed/03/38327dd…/platformio-2.6.2.tar.gz (84 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/d1/ee/7752a39…/platformio-2.6.1.tar.gz (84 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/53/95/263c8b7…/platformio-2.6.0.tar.gz (84 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/07/87/ed23686…/platformio-2.5.0.tar.gz (82 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/d2/6e/23c97f0…/platformio-2.4.1.tar.gz (81 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/df/5f/a005701…/platformio-2.4.0.tar.gz (81 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/a4/5f/73f1495…/platformio-2.3.5.tar.gz (80 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/75/1b/28c2dd7…/platformio-2.3.4.tar.gz (78 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading http://pypi.doubanio.com/packages/a1/09/075baeb…/platformio-2.3.3.tar.gz (77 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting lockfile>=0.9.1
  Downloading http://pypi.doubanio.com/packages/c8/22/9460e31…/lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Collecting SCons
  Downloading http://pypi.doubanio.com/packages/6d/41/8d65a5a…/SCons-4.3.0-py3-none-any.whl (4.2 MB)
Collecting urllib3<1.27,>=1.21.1
  Downloading http://pypi.doubanio.com/packages/af/f4/524415c…/urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting certifi>=2017.4.17
  Downloading http://pypi.doubanio.com/packages/37/45/946c027…/certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer~=2.0.0
  Downloading http://pypi.doubanio.com/packages/47/84/b06f672…/charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Downloading http://pypi.doubanio.com/packages/04/a2/d918dcd…/idna-3.3-py3-none-any.whl (61 kB)
Requirement already satisfied: setuptools in /Users/mingxing/.platformio/penv/lib/python3.8/site-packages (from SCons->platformio) (49.2.1)
Building wheels for collected packages: platformio
  Building wheel for platformio (setup.py): started
  Building wheel for platformio (setup.py): finished with status 'done'
  Created wheel for platformio: filename=platformio-2.3.3-py3-none-any.whl size=122179 sha256=afe1bab285844b1df407ad191eeaeb066a09884509d682718f12645a3ba3ec8a
  Stored in directory: /Users/mingxing/Library/Caches/pip/wheels/5a/48/69/20cc859615b9c0aaeb3aeda06744d8bd0a2cae123d311d0ed0
Successfully built platformio
Installing collected packages: urllib3, idna, charset-normalizer, certifi, SCons, requests, pyserial, lockfile, click, bottle, platformio
Successfully installed SCons-4.3.0 bottle-0.12.19 certifi-2021.10.8 charset-normalizer-2.0.9 click-8.0.3 idna-3.3 lockfile-0.12.2 platformio-2.3.3 pyserial-3.5 requests-2.27.0 urllib3-1.26.7

PlatformIO Core has been successfully installed into an isolated environment `/Users/mingxing/.platformio/penv`!

The full path to `platformio.exe` is `/Users/mingxing/.platformio/penv/bin/platformio`

If you need an access to `platformio.exe` from other applications, please install Shell Commands
(add PlatformIO Core binary directory `/Users/mingxing/.platformio/penv/bin` to the system environment PATH variable):

See https://docs.platformio.org/page/installation.html#install-shell-commands

```

**Comment by zhangmx** [comment]
Sorry, it's my fault. After changed pypi source. Installing successed! Thank you
