### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Fo170** [platformio/platformio-core-installer#1955]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.64.2
  PIO IDE: v2.4.2
  System: Windows_NT, 6.1.7601, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `C:\Users\Admin\.platformio\penv\Scripts\platformio.exe --help`.
Error: Usage: platformio [OPTIONS] COMMAND [ARGS]...

Try 'platformio -h' for help.



Error: No such command "home"



	at c:\Users\Admin\.vscode\extensions\platformio.platformio-ide-2.4.2\node_modules\platformio-node-helpers\dist\index.js:1:5240
	at ChildProcess.c (c:\Users\Admin\.vscode\extensions\platformio.platformio-ide-2.4.2\node_modules\platformio-node-helpers\dist\index.js:1:5134)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\Admin\.vscode\extensions\platformio.platformio-ide-2.4.2\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by Fo170** [comment]
platformIO not run...
