### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by FIAV1** [platformio/platformio-core-installer#2048]
# Description of problem
Installing PlatformIO extension from VSCode extensions I get an error. I have a MacBook Pro with Apple M1 chip.

# Configuration

  VSCode: 1.65.2
  PIO IDE: v2.4.3
  System: Darwin, 21.4.0, arm64

# Exception
  ```
  Error:   error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Could not install PlatformIO Core: Command '['/Users/fiav1/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.1
Platform: Darwin-21.4.0
Python version: 3.7.10 (default, Mar 10 2022, 15:45:36) 
[Clang 13.0.0 (clang-1300.0.29.30)]
Python path: /Users/fiav1/.asdf/installs/python/3.7.10/bin/python3
Creating a virtual environment at /Users/fiav1/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Using cached platformio-5.2.5.tar.gz (218 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

	at /Users/fiav1/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5240
	at ChildProcess.c (/Users/fiav1/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5134)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by FIAV1** [comment]
For future travelers: I tried to change python version I was using, from 3.7.10 to 3.10.1, restarted and it worked.
