### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by scz-u** [platformio/platformio-core-installer#2055]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.64.2
  PIO IDE: v2.4.3
  System: Darwin, 21.3.0, x64

  %23 Exception
  ```
  Error:   ERROR: HTTP error 403 while getting https://pypi.tuna.tsinghua.edu.cn/packages/9d/e6/d369eada663ba901e5a9d6783b160ca546515b112b06bbb42851792f3353/platformio-5.2.5.tar.gz%23sha256=aa0d1ff8a17ac1952eb45d37a84d4aa6e5d1aa65098bd1525db34be83c42c4ae (from https://pypi.tuna.tsinghua.edu.cn/simple/platformio/)
ERROR: Could not install requirement platformio from https://pypi.tuna.tsinghua.edu.cn/packages/9d/e6/d369eada663ba901e5a9d6783b160ca546515b112b06bbb42851792f3353/platformio-5.2.5.tar.gz%23sha256=aa0d1ff8a17ac1952eb45d37a84d4aa6e5d1aa65098bd1525db34be83c42c4ae because of HTTP error 403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/9d/e6/d369eada663ba901e5a9d6783b160ca546515b112b06bbb42851792f3353/platformio-5.2.5.tar.gz for URL https://pypi.tuna.tsinghua.edu.cn/packages/9d/e6/d369eada663ba901e5a9d6783b160ca546515b112b06bbb42851792f3353/platformio-5.2.5.tar.gz%23sha256=aa0d1ff8a17ac1952eb45d37a84d4aa6e5d1aa65098bd1525db34be83c42c4ae (from https://pypi.tuna.tsinghua.edu.cn/simple/platformio/)
Error: Could not install PlatformIO Core: Command '['/Users/lilechao/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.1
Platform: macOS-12.2
Python version: 3.8.9 (default, Feb 18 2022, 07:45:34) 
[Clang 13.1.6 (clang-1316.0.21.2)]
Python path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
Creating a virtual environment at /Users/lilechao/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting platformio

	at /Users/lilechao/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5240
	at ChildProcess.c (/Users/lilechao/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5134)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at Pipe.<anonymous> (net.js:673:12)
  ```

**Comment by ivankravets** [comment]
ERROR: HTTP error 403 while getting https://pypi.tuna.tsinghua.edu.cn/packages/

Please revert back your pip configuration to the official PyPi registry.
