### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by schlameel** [platformio/platformio-core-installer#2061]
# Description of problem
  Error on VSCode startup: ModuleNotFoundError: No module named 'pip._vendor.six'

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

# Configuration

  VSCode: 1.65.2
  PIO IDE: v2.4.3
  System: Linux, 5.4.0-107-generic, x64 (Linux Mint 20.3)

# Exception
  ```
  Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.platformio/penv/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  %23 isort:skip %23 noqa
  File "/home/user/.platformio/penv/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/user/.platformio/penv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/user/.platformio/penv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/user/.platformio/penv/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/home/user/.platformio/penv/lib/python3.8/site-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems
ModuleNotFoundError: No module named 'pip._vendor.six'
Error: Could not install PlatformIO Core: Command '['/home/user/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.1
Platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.29
Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/user/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core

	at /home/user/.vscode-oss/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5240
	at ChildProcess.c (/home/user/.vscode-oss/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5134)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by schlameel** [comment]
I opened a new VSCode window and got a message that PIO installed successfully.  I can't say what happened to make it work nor what broke it in the first place.  I'll let you decide if you want to close the issue.  I cannot recreate the error.
