### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by RobLabRat** [platformio/platformio-core-installer#208]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.49.3
  PIO IDE: v2.1.0
  System: Linux, 3.16.0-38-generic, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 0.3.5
Platform: Linux-3.16.0-38-generic-x86_64-with-glibc2.9
Python version: 3.4.3 (default, Nov 12 2018, 22:25:49) 
[GCC 4.8.4]
Python path: /usr/bin/python3
Creating a virtual environment at /home/temniy/.platformio/penv

	at /home/temniy/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4911
	at ChildProcess.s (/home/temniy/.vscode/extensions/platformio.platformio-ide-2.1.0/node_modules/platformio-node-helpers/dist/index.js:1:4807)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
> Python version: 3.4.3

The minimum supported version is Python 3.5
