### ISSUE TITLE
Installation Manager - Unable to create virtualenv for pio on linux

### ISSUE THREAD

**Issue by SechyMonkey** [platformio/platformio-core-installer#2162]
%23 Description of problem
Attempting to install via vscode extension manager on Debian linux. Reporting as the platform io installer requested it be reported. The /usr/home/\<user\>/.platformio/.cache/tmp directory exists with two files: 
-rw-r--r-- 1 \<user\> \<group\>   759687 May 24 17:01 get-platformio-1.1.1.py
-rw-r--r-- 1 \<user\> \<group\> 11394949 May 24 17:13 virtualenv.pyz

Running the get-platformio-1.1.1.py manually in verbose mode, the error occurs here:
Creating a virtual environment at /home/\<user\>/.platformio/penv
\# /usr/lib/python3.9/\_\_pycache\_\_/netrc.cpython-39.pyc matches /usr/lib/python3.9/netrc.py
\# code object from '/usr/lib/python3.9/\_\_pycache\_\_/netrc.cpython-39.pyc'
\# /usr/lib/python3.9/\_\_pycache\_\_/shlex.cpython-39.pyc matches /usr/lib/python3.9/shlex.py
\# code object from '/usr/lib/python3.9/\_\_pycache\_\_/shlex.cpython-39.pyc'
import 'shlex' \# <_frozen_importlib_external.SourceFileLoader object at 0x7f6496b20f70>
import 'netrc' \# <_frozen_importlib_external.SourceFileLoader object at 0x7f6496b20ee0>

No other directories, files, or subdirectories exist under the .platformio directory.

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.67.2
  PIO IDE: v2.4.3
  System: Linux, 5.10.0-14-amd64, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.1.1
Platform: Linux-5.10.0-14-amd64-x86_64-with-glibc2.31
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Python path: /usr/bin/python3
Creating a virtual environment at /home/<user>/.platformio/penv
/usr/bin/python3

	at /home/<user>/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5240
	at ChildProcess.c (/home/<user>/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5134)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by SechyMonkey** [comment]
Turns out I'm dumb as hell and didn't have venv installed :(

I thought I checked that, but I had not. So, problem solved.
