### ISSUE TITLE
Installation Manager |  Error: Compatible PlatformIO Core not found. | Reason: PlatformIO executable not found in PATH/TO/Scripts

### ISSUE THREAD

**Issue by SaeedRezaAmanat** [platformio/platformio-core-installer#2169]
Hi! I'm trying to install platformio for vscode but I get an error...
As far as I checked, no solution worked for me
My username does not have any escapes, I already uninstalled every python version I had except one (python 3.10)
and I disabled my antivirus  or even tried installing older version of platformio but none of them worked for me.
I've also tried installing the core as the doc said by get-platform.py but it seems  it doesn't create platformio.exe after installation
(PS: I haven't tried reinstalling my vscode yet)
________________________

  %23 Configuration

  VSCode: 1.67.2
  PIO IDE: v2.4.3
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO executable not found in `C:\Users\ParsComputer\.platformio\penv\Scripts`

    at cmd (c:\Users\ParsComputer\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:187:25)
    at ChildProcess.c (c:\Users\ParsComputer\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:177:7)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at ChildProcess.cp.emit (c:\Users\ParsComputer\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by SaeedRezaAmanat** [comment]
Actually I suppose it's my virtual environment problem that does not let installing or updating anything. And I don't know how to fix this

**Comment by SaeedRezaAmanat** [comment]
So I think the problem is not because of platformio but the main problem is that in virtual environment install in global site-packages not in penv site-package. Thus I close this issue

**Comment by SaeedRezaAmanat** [comment]
My problem is solved! See this if you think you have a problem like this: https://github.com/pypa/pip/issues/11154
