### ISSUE TITLE
Installation Manager: Could not create PIO Core Virtual Environment.

### ISSUE THREAD

**Issue by ma-lalonde** [platformio/platformio-core-installer#2179]
%23 Description of problem
  Clean fresh install. Bleh.

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.67.2
  PIO IDE: v2.4.3
  System: Linux, 5.13.0-44-generic, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.1.1
Platform: Linux-5.13.0-44-generic-x86_64-with-glibc2.29
Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/malalonde/.platformio/penv
/usr/bin/python3

	at /home/malalonde/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5240
	at ChildProcess.c (/home/malalonde/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5134)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by ma-lalonde** [comment]
I also noticed a bunch of messages like: `connect ECONNREFUSED 127.0.0.1:8012` in the Runtime Status console

**Comment by ma-lalonde** [comment]
I solved it using this thread: https://stackoverflow.com/questions/63491221/modulenotfounderror-no-module-named-virtualenv-seed-embed-via-app-data-when-i

```
sudo apt remove --purge python3-virtualenv
pip3 uninstall virtualenv
pip3 install virtualenv
```
