### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by merlinscomputing** [platformio/platformio-core-installer#2180]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.67.2
  PIO IDE: v2.4.3
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `C:\Users\jhagerman\.platformio\penv\Scripts\platformio.exe --help`.
Error: Traceback (most recent call last):

  File "C:\Users\jhagerman\.platformio\python3\lib\runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\Users\jhagerman\.platformio\python3\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "C:\Users\jhagerman\.platformio\penv\Scripts\platformio.exe\__main__.py", line 4, in <module>

  File "C:\Users\jhagerman\.platformio\penv\lib\site-packages\platformio\__main__.py", line 59, in <module>

    @cli.result_callback()

TypeError: 'NoneType' object is not callable



	at c:\Users\jhagerman\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\platformio-node-helpers\dist\index.js:1:5240
	at ChildProcess.c (c:\Users\jhagerman\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\platformio-node-helpers\dist\index.js:1:5134)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at ChildProcess.cp.emit (c:\Users\jhagerman\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by merlinscomputing** [comment]
If the @cli.result_callback() line is commented out in the __main__.py pio is able to be run both in Command Line mode and in VSCODE, however VSCODE is shows spinning blue under "core" version, new s and recent projects.

![image](https://user-images.githubusercontent.com/3476629/172054429-680196a3-3dce-45a8-9ebb-441f47b38d27.png)
