### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by nikejasonlyz** [platformio/platformio-core-installer#2188]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.68.0
  PIO IDE: v2.4.3
  System: Windows_NT, 10.0.22000, x64

  %23 Exception
  ```
  Error: Could not find compatible PlatformIO Core. Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.
	at u.value (c:\Users\yuanl\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\platformio-node-helpers\dist\index.js:1:783624)
	at S.install (c:\Users\yuanl\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:4381)
	at c:\Users\yuanl\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:28144
	at E._withProgress (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:81:44253)
	at E.withProgress (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:81:44007)
	at Object.withProgress (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:42210)
	at Object.startInstaller (c:\Users\yuanl\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:27559)
	at async Object.activate (c:\Users\yuanl\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:23007)
  ```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core-installer/issues/2284
