### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ArashIranfar** [platformio/platformio-core-installer#2203]
Hi, 
I recently moved to Ubuntu 22.04 and it seems like there are some problems regarding the installation of platformio on Vs code in this OS. I would appreciate any help 

  VSCode: 1.68.1
  PIO IDE: v2.4.3
  System: Linux, 5.15.0-39-generic, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/home/aris/.platformio/.cache/tmp/get-platformio-1.1.1.py", line 69, in <module>
    main()
  File "/home/aris/.platformio/.cache/tmp/get-platformio-1.1.1.py", line 61, in main
    bootstrap()
  File "/home/aris/.platformio/.cache/tmp/get-platformio-1.1.1.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/pioinstaller/__main__.py", line 133, in main
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/click/core.py", line 1128, in __call__
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/click/core.py", line 1053, in main
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/click/core.py", line 1637, in invoke
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/click/core.py", line 1395, in invoke
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/click/core.py", line 754, in invoke
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/click/decorators.py", line 26, in new_func
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/pioinstaller/__main__.py", line 61, in cli
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/pioinstaller/core.py", line 70, in install_platformio_core
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/pioinstaller/core.py", line 98, in _install_platformio_core
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/pioinstaller/penv.py", line 71, in create_core_penv
  File "/home/aris/.platformio/.cache/tmp/.piocore-installer-420nstos/tmp2umf9kjw/pioinstaller.zip/pioinstaller/penv.py", line 141, in init_state
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/aris/.platformio/penv/bin/python'
 -> Installer version: 1.1.1
Platform: Linux-5.15.0-39-generic-x86_64-with-glibc2.35
Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/aris/.platformio/penv

	at /home/aris/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5240
	at ChildProcess.c (/home/aris/.vscode/extensions/platformio.platformio-ide-2.4.3/node_modules/platformio-node-helpers/dist/index.js:1:5134)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by ArashIranfar** [comment]
Well there is a work around. 
I uninstalled the broken extension, Installed the platformio using pip, then installed the vscode extension. It works fine

**Comment by ArashIranfar** [comment]
The problem is that the installer looks in '/home/aris/.platformio/penv/bin/python' for the python file whereas it is in '/home/aris/.platformio/penv/local/bin/python'

How can I solve this?
