### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by KarenWest** [platformio/platformio-core-installer#222]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.50.1
  PIO IDE: v2.1.0
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\rkwes\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "C:\Users\rkwes\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "C:\Users\rkwes\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 45, in bootstrap
    import pioinstaller.__main__
  File "C:\Users\rkwes\.platformio\.cache\tmp\.piocore-installer-_oaw79ab\tmpi8s456b8\pioinstaller.zip\pioinstaller\__init__.py", line 15, in <module>
  File "C:\Users\rkwes\AppData\Local\Programs\Python\Python37-32\lib\logging\config.py", line 30, in <module>
    import logging.handlers
  File "C:\Users\rkwes\AppData\Local\Programs\Python\Python37-32\lib\logging\handlers.py", line 26, in <module>
    import logging, socket, os, pickle, struct, time, re
  File "C:\Users\rkwes\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.

    at c:\Users\rkwes\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:138:23
    at ChildProcess.s (c:\Users\rkwes\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:124:5)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at ChildProcess.cp.emit (c:\Users\rkwes\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Please install the latest Python 3.8 (not 3.9) from https://docs.platformio.org/en/latest/faq.html#install-python-interpreter
