### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Rabbible** [platformio/platformio-core-installer#2220]
VSCode: 1.68.1
  PIO IDE: v2.5.0
  System: Linux, 4.4.0-19041-Microsoft, x64

  ```
  Error: Error: Could not create PIO Core Virtual Environment.
 -> Installer version: 1.1.2
Platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/xxxxx/.platformio/penv
/usr/bin/python3

	at /home/xxxxx/.vscode-server/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/index.js:1:5165
	at ChildProcess.c (/home/xxxxx/.vscode-server/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/index.js:1:5059)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by Rabbible** [comment]
After changing another web and downloading the newest python (python3.10.5),problem is soloved.
