### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by marqueznelju** [platformio/platformio-core-installer#2226]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.68.1
  PIO IDE: v2.5.0
  System: Windows_NT, 10.0.22000, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\Marqu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Marqu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Marqu\.platformio\penv\lib\site-packages\pip\__main__.py", line 29, in <module>
  File "C:\Users\Marqu\.platformio\penv\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
  File "C:\Users\Marqu\.platformio\penv\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
  File "C:\Users\Marqu\.platformio\penv\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
  File "C:\Users\Marqu\.platformio\penv\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 21, in <module>
  File "C:\Users\Marqu\.platformio\penv\lib\site-packages\pip\_vendor\packaging\utils.py", line 8, in <module>
  File "C:\Users\Marqu\.platformio\penv\lib\site-packages\pip\_vendor\packaging\tags.py", line 23, in <module>
ImportError: cannot import name '_manylinux' from 'pip._vendor.packaging' (C:\Users\Marqu\.platformio\penv\lib\site-packages\pip\_vendor\packaging\__init__.py)
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\Marqu\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\Marqu\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\Marqu\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

    at cmd (c:\Users\Marqu\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:187:25)
    at ChildProcess.c (c:\Users\Marqu\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:177:7)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at ChildProcess.cp.emit (c:\Users\Marqu\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by ivankravets** [comment]
Could you reproduce this issue again?
