### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by henglijack** [platformio/platformio-core-installer#2233]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.68.1
  PIO IDE: v2.5.0
  System: Windows_NT, 10.0.17763, x64

  %23 Exception
  ```
  Error: Could not find compatible PlatformIO Core. Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.
	at u.value (c:\Users\jack\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\platformio-node-helpers\dist\index.js:1:801864)
	at S.install (c:\Users\jack\.vscode\extensions\platformio.platformio-ide-2.5.0\dist\extension.js:1:4373)
	at c:\Users\jack\.vscode\extensions\platformio.platformio-ide-2.5.0\dist\extension.js:1:27870
	at E._withProgress (c:\Users\jack\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:81:44253)
	at E.withProgress (c:\Users\jack\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:81:44007)
	at Object.withProgress (c:\Users\jack\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:42210)
	at Object.startInstaller (c:\Users\jack\.vscode\extensions\platformio.platformio-ide-2.5.0\dist\extension.js:1:27285)
	at async Object.activate (c:\Users\jack\.vscode\extensions\platformio.platformio-ide-2.5.0\dist\extension.js:1:22733)
  ```

**Comment by ivankravets** [comment]
Could you reproduce this issue again?
