### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Deeric1000** [platformio/platformio-core-installer#2274]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.67.2
  PIO IDE: v2.5.0
  System: Linux, 5.15.0-39-generic, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.1.2
Platform: Linux-5.15.0-39-generic-x86_64-with-glibc2.35
Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/deeric/.platformio/penv
/usr/bin/python3

    at cmd (/home/deeric/.vscode/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:187:25)
    at ChildProcess.c (/home/deeric/.vscode/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:177:7)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by ivankravets** [comment]
How did you solve it?
