### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by aryangupta0405** [platformio/platformio-core-installer#2281]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.68.1
  PIO IDE: v2.5.0
  System: Linux, 5.13.0-52-generic, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `/home/aryan/.platformio/penv/bin/platformio --help`.
Error: Traceback (most recent call last):
  File "/home/aryan/.platformio/penv/bin/platformio", line 5, in <module>
    from platformio.__main__ import main
  File "/home/aryan/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py", line 59, in <module>
    @cli.result_callback()
TypeError: 'NoneType' object is not callable


	at /home/aryan/.vscode/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/index.js:1:5227
	at ChildProcess.c (/home/aryan/.vscode/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/index.js:1:5121)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by ivankravets** [comment]
Please remove `/home/aryan/.platformio/penv` folder and restart VSCode.
