### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by zhaohj08** [platformio/platformio-core-installer#2348]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.70.0
  PIO IDE: v2.5.1
  System: Windows_NT, 6.1.7601, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO Core version 4.0.3 does not match version requirements >=6.

	at c:\Users\***\.vscode\extensions\platformio.platformio-ide-2.5.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5308
	at ChildProcess.o (c:\Users\***\.vscode\extensions\platformio.platformio-ide-2.5.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4691)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  ```

**Comment by ivankravets** [comment]
Please navigate to `c:\Users\***\.platformio` and remove `penv` folder. Restart VSCode.
