### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by chadengineer** [platformio/platformio-core-installer#2416]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.71.0
  PIO IDE: v2.5.4
  System: Windows_NT, 10.0.22000, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\ajang\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 69, in <module>
    main()
  File "C:\Users\ajang\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 61, in main
    bootstrap()
  File "C:\Users\ajang\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\click\core.py", line 1637, in invoke
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\pioinstaller\core.py", line 98, in _install_platformio_core
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\pioinstaller\penv.py", line 71, in create_core_penv
  File "C:\Users\ajang\.platformio\.cache\tmp\.piocore-installer-tzq7_2sj\tmp3se8w93h\pioinstaller.zip\pioinstaller\penv.py", line 141, in init_state
  File "C:\Users\ajang\.platformio\python3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\ajang\.platformio\python3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\ajang\.platformio\python3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ajang\.platformio\python3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\ajang\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\ajang\.platformio\penv

	at c:\Users\ajang\.vscode\extensions\platformio.platformio-ide-2.5.4-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5308
	at ChildProcess.o (c:\Users\ajang\.vscode\extensions\platformio.platformio-ide-2.5.4-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4691)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by chadengineer** [comment]
This issue was resolved by performing a Windows reset.
