### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by TinMan0023** [platformio/platformio-core-installer#2460]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.47.3
  PIO IDE: v2.3.4
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.0.3
Platform: Windows-10
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\ebenc\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\ebenc\.platformio\penv

	at c:\Users\ebenc\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:769806
	at ChildProcess.a (c:\Users\ebenc\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\platformio-node-helpers\dist\index.js:1:771396)
	at ChildProcess.emit (events.js:203:13)
	at ChildProcess.EventEmitter.emit (domain.js:476:20)
	at ChildProcess.cp.emit (c:\Users\ebenc\.vscode\extensions\platformio.platformio-ide-2.3.4\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by TinMan0023** [comment]
Note sure if this was automatically summited when an issue occurs in PlatformIO since I did not manually enter this issue but if there is a problem it should probably be reviewed. I will look at traceback myself and see if I can get more details on what happened and provide more details, if possible.
