### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ww34ww34ww34** [platformio/platformio-core-installer#247]
%23 Description of problem
Can't install PlatformIO plugin in VSCode , se log below:

  %23 Configuration

  VSCode: 1.50.1
  PIO IDE: v2.1.3
  System: Windows_NT, 10.0.18363, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\pioinstaller\python.py", line 178, in find_compatible_pythons
  File "C:\Users\whitew_fisso\.platformio\python3\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\whitew_fisso\.platformio\python3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Python27\\python2.exe', 'C:\\Users\\whitew_fisso\\.platformio\\.cache\\tmp\\get-platformio-0.3.5.py', '--no-shutdown-piohome', 'check', 'python']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\pioinstaller\__main__.py", line 122, in main
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\click\core.py", line 829, in __call__
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\click\core.py", line 782, in main
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\click\core.py", line 1236, in invoke
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\click\core.py", line 1066, in invoke
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\click\core.py", line 610, in invoke
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\click\decorators.py", line 21, in new_func
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\pioinstaller\__main__.py", line 52, in cli
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\pioinstaller\penv.py", line 52, in create_core_penv
  File "C:\Users\whitew_fisso\.platformio\.cache\tmp\.piocore-installer-mql17hpf\tmpx3smqfxs\pioinstaller.zip\pioinstaller\python.py", line 191, in find_compatible_pythons
UnboundLocalError: local variable 'error' referenced before assignment
 -> Installer version: 0.3.5
Platform: Windows-10
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Python path: C:\Users\whitew_fisso\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\whitew_fisso\.platformio\penv

	at c:\Users\whitew_fisso\.vscode\extensions\platformio.platformio-ide-2.1.3\node_modules\platformio-node-helpers\dist\index.js:1:879089
	at ChildProcess.c (c:\Users\whitew_fisso\.vscode\extensions\platformio.platformio-ide-2.1.3\node_modules\platformio-node-helpers\dist\index.js:1:878983)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.cp.emit (c:\Users\whitew_fisso\.vscode\extensions\platformio.platformio-ide-2.1.3\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Did you try this solution https://github.com/platformio/platformio-core-installer/issues/221?
