### ISSUE TITLE
Installation Manager: PlatformIO is not installing on Atom

### ISSUE THREAD

**Issue by tcoverst** [platformio/platformio-core-installer#2479]
PlatformIO is not installing on Atom

**Comment by tcoverst** [comment]
Error: Error: Compatible PlatformIO Core not found. Reason: Could not run C:\Users\T\.platformio\penv\Scripts\platformio.exe --version. Error: Traceback (most recent call last):

File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main

return _run_code(code, main_globals, None,
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code

exec(code, run_globals)
File "C:\Users\T.platformio\penv\Scripts\platformio.exe__main__.py", line 4, in

File "C:\Users\T.platformio\penv\lib\site-packages\platformio__main__.py", line 21, in

from platformio import __version__, exception, maintenance
File "C:\Users\T.platformio\penv\lib\site-packages\platformio\maintenance.py", line 20, in

import semantic_version
File "C:\Users\T.platformio\penv\lib\site-packages\semantic_version__init__.py", line 14, in

__version__ = version("semantic_version")
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\importlib\metadata.py", line 569, in version

return distribution(distribution_name).version
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\importlib\metadata.py", line 266, in version

return self.metadata['Version']
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\importlib\metadata.py", line 254, in metadata

self.read_text('METADATA')
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\importlib\metadata.py", line 529, in read_text

return self._path.joinpath(filename).read_text(encoding='utf-8')
AttributeError: 'WindowsPath' object has no attribute 'read_text'

at C:\Users\T\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5004
at ChildProcess.s (C:\Users\T\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4900)
at ChildProcess.emit (events.js:223:5)
at ChildProcess.cp.emit (C:\Users\T\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
