### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by 21317682** [platformio/platformio-core-installer#254]
%23 Description of problem
Initially had an error with missing Python. Installed python 3.8 from the store but was till unable to install. Removing C:\Users\qwe\.platformio\packages\contrib-pysite did not resolve the issue. Also reverting to previous versions did not work.

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.50.1
  PIO IDE: v2.1.3
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\pioinstaller\__main__.py", line 122, in main
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\click\core.py", line 829, in __call__
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\click\core.py", line 782, in main
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\click\core.py", line 1236, in invoke
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\click\core.py", line 1066, in invoke
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\click\core.py", line 610, in invoke
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\click\decorators.py", line 21, in new_func
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\pioinstaller\__main__.py", line 52, in cli
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\pioinstaller\penv.py", line 75, in create_core_penv
  File "C:\Users\Alex Muthua\.platformio\.cache\tmp\.piocore-installer-r2ydsoeb\tmpz49uf_i8\pioinstaller.zip\pioinstaller\penv.py", line 144, in add_state_info
  File "C:\Users\Alex Muthua\.platformio\python3\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\Alex Muthua\.platformio\python3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\Alex Muthua\\.platformio\\penv\\Scripts\\python.exe', '-c', "import sys; version=sys.version_info; print('%d.%d.%d'%(version[0],version[1],version[2]))"]' returned non-zero exit status 101.
 -> Installer version: 0.3.5
Platform: Windows-10
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Python path: C:\Users\Alex Muthua\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\Alex Muthua\.platformio\penv
	at c:\Users\Alex Muthua\.vscode\extensions\platformio.platformio-ide-2.1.3\node_modules\platformio-node-helpers\dist\index.js:1:879089	at ChildProcess.c (c:\Users\Alex Muthua\.vscode\extensions\platformio.platformio-ide-2.1.3\node_modules\platformio-node-helpers\dist\index.js:1:878983)	at ChildProcess.emit (events.js:223:5)	at ChildProcess.EventEmitter.emit (domain.js:475:20)	at ChildProcess.cp.emit (c:\Users\Alex Muthua\.vscode\extensions\platformio.platformio-ide-2.1.3\node_modules\cross-spawn\lib\enoent.js:34:29)	at maybeClose (internal/child_process.js:1021:16)	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
t.log @ workbench.desktop.main.js:sourcemap:287

**Comment by ivankravets** [comment]
Did you try this solution https://github.com/platformio/platformio-core-installer/issues/221?
