### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by harivasu25** [platformio/platformio-core-installer#2544]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.72.2
  PIO IDE: v2.5.5
  System: Darwin, 21.6.0, arm64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/harivasu/.platformio/penv/lib/python3.10/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
ModuleNotFoundError: No module named 'pip._internal'
Error: Could not install PlatformIO Core: Command '['/Users/harivasu/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.2
Platform: macOS-12.6.1
Python version: 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
Python path: /opt/homebrew/opt/python@3.10/bin/python3.10
Creating a virtual environment at /Users/harivasu/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core

	at /Users/harivasu/.vscode/extensions/platformio.platformio-ide-2.5.5-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:5311
	at ChildProcess.o (/Users/harivasu/.vscode/extensions/platformio.platformio-ide-2.5.5-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:4691)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Socket.emit (node:domain:475:12)
	at Pipe.<anonymous> (node:net:687:12)
  ```

**Comment by dzalf** [comment]
It has been working perfectly fine until about 30 minutes ago. Now the extension is broken and unusable.
I have reinstalled the extension, deleted the .platoformio folder, rebooted 3 times and NOTHING.

What is going on?

![image](https://user-images.githubusercontent.com/3759916/202827391-9cf7b669-81d3-4707-9717-b08e6ec6138d.png)

![image](https://user-images.githubusercontent.com/3759916/202827403-629891cd-6207-4674-83d7-aedca3d3c3ca.png)
