### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by AlexanderBaggett** [platformio/platformio-core-installer#2552]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.72.2
  PIO IDE: v2.5.5
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\Zadkey\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 69, in <module>
    main()
  File "C:\Users\Zadkey\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 61, in main
    bootstrap()
  File "C:\Users\Zadkey\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\click\core.py", line 1637, in invoke
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\pioinstaller\core.py", line 98, in _install_platformio_core
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\pioinstaller\penv.py", line 71, in create_core_penv
  File "C:\Users\Zadkey\.platformio\.cache\tmp\.piocore-installer-8504hn6a\tmpyg4_mrho\pioinstaller.zip\pioinstaller\penv.py", line 141, in init_state
  File "C:\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Python310\python.exe
Creating a virtual environment at C:\Users\Zadkey\.platformio\penv

	at c:\Users\Zadkey\.vscode\extensions\platformio.platformio-ide-2.5.5-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5311
	at ChildProcess.o (c:\Users\Zadkey\.vscode\extensions\platformio.platformio-ide-2.5.5-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4691)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by AlexanderBaggett** [comment]
Not fixed.
