### ISSUE TITLE
PIO Installation Manager Error Could not find a version that satisfies the requirement wsproto==1.0.0

### ISSUE THREAD

**Issue by scottmberry** [platformio/platformio-core-installer#2559]
I recently upgraded to Ventura, maybe this is related. I've been using VSCode and Platformio for a while, very intermittently, for Marlin firmware. As I went to compile a new version I started getting errors about pio bash command not being available, pio home not working, etc. This is the main error which seems to show again and again. I've deleted the .platformio directory, uninstalled Platformio from VS Code, reinstalled, tried earlier versions, etc. The one thing that gets me is the version of PIP it is reporting, which is not what I have installed, but I assume that is from the python environment that Platformio creates? 

In either case, I have Python 3.6.0 installed and the latest PIP on my machine in general. But my PIO settings were to use the included python environment so not sure if that relates or matters. I also included the debug console log which has some other tidbits in it. I use VSCode for nothing else so happy to nuke it if that is a step to take. Otherwise, all my google-fu is now coming up empty. 

[vscode-app-1667887495850.log](https://github.com/platformio/platformio-core-installer/files/9958118/vscode-app-1667887495850.log)

Configuration

  VSCode: 1.73.0
  PIO IDE: v2.5.5
  System: Darwin, 22.1.0, x64

Exception
  ```
  Error:   Could not find a version that satisfies the requirement wsproto==1.0.0 (from platformio) (from versions: 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1)
No matching distribution found for wsproto==1.0.0 (from platformio)
You are using pip version 9.0.1, however version 22.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Error: Could not install PlatformIO Core: Command '['/Users/scottberry/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.2
Platform: Darwin-22.1.0
Python version: 3.6.0 (default, Dec 30 2020, 18:58:43) 
[GCC Apple LLVM 12.0.0 (clang-1200.0.32.28)]
Python path: /Users/scottberry/.pyenv/versions/3.6.0/bin/python3
Creating a virtual environment at /Users/scottberry/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Using cached https://files.pythonhosted.org/packages/fd/e8/ed228e1bac31da9201c0fbb5f96683a370c961a67ca17a8af35a3213734a/platformio-6.1.5.tar.gz
Collecting bottle==0.12.* (from platformio)
  Using cached https://files.pythonhosted.org/packages/63/96/2713bb6e0ca10ee2b7be568d6e6d112cf0a1b604e14879fe744f48ebbed6/bottle-0.12.23-py3-none-any.whl
Collecting click==8.0.4 (from platformio)
  Using cached https://files.pythonhosted.org/packages/4a/a8/0b2ced25639fb20cc1c9784de90a8c25f9504a7f18cd8b5397bd61696d7d/click-8.0.4-py3-none-any.whl
Collecting colorama (from platformio)
  Using cached https://files.pythonhosted.org/packages/77/8b/7550e87b2d308a1b711725dfaddc19c695f8c5fa413c640b2be01662f4e6/colorama-0.4.5-py2.py3-none-any.whl
Collecting marshmallow==3.14.1 (from platformio)
  Using cached https://files.pythonhosted.org/packages/ec/f3/62015688fdb1e02779702c36e500a123e019a4f99a70fd849de2c7572748/marshmallow-3.14.1-py3-none-any.whl
Collecting pyelftools<1,>=0.27 (from platformio)
  Using cached https://files.pythonhosted.org/packages/04/7c/867630e6e6293793f838b31034aa1875e1c3bd8c1ec34a0929a2506f350c/pyelftools-0.29-py2.py3-none-any.whl
Collecting pyserial==3.5.* (from platformio)
  Using cached https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl
Collecting requests==2.* (from platformio)
  Using cached https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl
Collecting semantic_version==2.10.* (from platformio)
  Using cached https://files.pythonhosted.org/packages/6a/23/8146aad7d88f4fcb3a6218f41a60f6c2d4e3a72de72da1825dc7c8f7877c/semantic_version-2.10.0-py2.py3-none-any.whl
Collecting tabulate==0.8.10 (from platformio)
  Using cached https://files.pythonhosted.org/packages/92/4e/e5a13fdb3e6f81ce11893523ff289870c87c8f1f289a7369fb0e9840c3bb/tabulate-0.8.10-py3-none-any.whl
Collecting zeroconf<1 (from platformio)
  Using cached https://files.pythonhosted.org/packages/c7/8d/feb017d71b322a3a243ccaf5e1d1c87a6aa5b84be7aa69542453e7d338a5/zeroconf-0.38.4-py3-none-any.whl
Collecting aiofiles==0.8.0 (from platformio)
  Using cached https://files.pythonhosted.org/packages/ca/e4/b78d049f7cc7ed053ddbfdd59b2dcc7bd387458e2c2869b602975685d65e/aiofiles-0.8.0-py3-none-any.whl
Collecting ajsonrpc==1.* (from platformio)
  Using cached https://files.pythonhosted.org/packages/cf/6f/6abff7fe6813e6f94129a50c8c70bf70fb33ed2515b1037e703cef6d7a7e/ajsonrpc-1.2.0-py3-none-any.whl
Collecting starlette==0.19.1 (from platformio)
  Using cached https://files.pythonhosted.org/packages/f1/9d/1fa96008b302dd3e398f89f3fc5afb19fb0b0f341fefa05c65b3a38d64cf/starlette-0.19.1-py3-none-any.whl
Collecting uvicorn==0.16.0 (from platformio)
  Using cached https://files.pythonhosted.org/packages/a0/68/effcc7c39d79fbae86ad621ebcf28d63a3b9c111a885bc2b74c576ba8dc4/uvicorn-0.16.0-py3-none-any.whl
Collecting wsproto==1.0.0 (from platformio)

	at /Users/scottberry/.vscode/extensions/platformio.platformio-ide-2.5.5-darwin-x64/node_modules/platformio-node-helpers/dist/index.js:1:5311
	at ChildProcess.o (/Users/scottberry/.vscode/extensions/platformio.platformio-ide-2.5.5-darwin-x64/node_modules/platformio-node-helpers/dist/index.js:1:4691)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Socket.emit (node:domain:475:12)
	at Pipe.<anonymous> (node:net:687:12)
  ```

**Comment by scottmberry** [comment]
This seems to be related to the Mac OS update, xcode tools needing to be reinstalled, etc. After resolving all of those PIO installed.
