### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by oliver-eifler** [platformio/platformio-core-installer#2584]
%23 Description of problem
  Getting this error after trying to update platformio core also same error when trying to install platformio ide extension on a fresh installed vs-.code

  %23 Configuration

  VSCode: 1.73.1
  PIO IDE: v2.5.5
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `C:\Users\Darkwolf\.platformio\penv\Scripts\platformio.exe --help`.
Error: Error: Traceback (most recent call last):

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main

    cli()  %23 pylint: disable=no-value-for-parameter

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 1130, in __call__

    return self.main(*args, **kwargs)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 1054, in main

    with self.make_context(prog_name, args, **extra) as ctx:

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 920, in make_context

    self.parse_args(ctx, args)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 1613, in parse_args

    rest = super().parse_args(ctx, args)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 1378, in parse_args

    value, args = param.handle_parse_result(ctx, opts, args)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 2360, in handle_parse_result

    value = self.process_value(ctx, value)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 2322, in process_value

    value = self.callback(ctx, self, value)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 1273, in show_help

    echo(ctx.get_help(), color=ctx.color)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 699, in get_help

    return self.command.get_help(self)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 1298, in get_help

    self.format_help(ctx, formatter)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 1331, in format_help

    self.format_options(ctx, formatter)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 1533, in format_options

    self.format_commands(ctx, formatter)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\click\core.py", line 1586, in format_commands

    cmd = self.get_command(ctx, subcommand)

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\platformio\cli.py", line 80, in get_command

    module = importlib.import_module(commands[cmd_name])

  File "C:\Users\Darkwolf\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 790, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\platformio\commands\ci.py", line 24, in <module>

    from platformio.project.commands.init import project_init_cmd, validate_boards

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\platformio\project\commands\init.py", line 55, in <module>

    @click.option("--ide", type=click.Choice(ProjectGenerator.get_supported_ides()))

  File "C:\Users\Darkwolf\.platformio\penv\lib\site-packages\platformio\project\integration\generator.py", line 62, in get_supported_ides

    for name in os.listdir(tpls_dir)

FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Darkwolf\\.platformio\\penv\\lib\\site-packages\\platformio\\assets\\templates\\ide-projects'



============================================================



An unexpected error occurred. Further steps:



* Verify that you have the latest version of PlatformIO using

  `pip install -U platformio` command



* Try to find answer in FAQ Troubleshooting section

  https://docs.platformio.org/page/faq/index.html



* Report this problem to the developers

  https://github.com/platformio/platformio-core/issues



============================================================





	at c:\Users\Darkwolf\.vscode\extensions\platformio.platformio-ide-2.5.5-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5311
	at ChildProcess.o (c:\Users\Darkwolf\.vscode\extensions\platformio.platformio-ide-2.5.5-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4691)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by oliver-eifler** [comment]
Solved: after installing platromio IDE extension in vscode or upgrading it 
close VSCode
do addition platformio core installation https://docs.platformio.org/en/latest/core/installation/methods/installer-script.html#local-download-macos-linux-windows
