### ISSUE TITLE
Installation Manager: unable to start PlatformIO IDE

### ISSUE THREAD

**Issue by madmijk** [platformio/platformio-core-installer#2739]
%23 Description of problem
It has been around half a year since I last opened PlatformIO. Today I wanted to compile something again, but I am unable to start PlatformIO.

Here is what I have tried so far:
1. Disabling the portable Python interpreter and falling back to my natively installed Python 3.11.2 (confirmed via `python --version`) - then I get the `no module named 'serial'` error that I remember from a while back. I am not sure how I resolved that one back then;
2. Rolling back PlatformIO in the VS Code extensions manager to version 2.4.3;
3. Reinstalling PlatformIO, also deleting the `%userprofile%/.platformio` folder;
4. Reinstalling VS Code, also deleting `%appdata%/Code` and `%userprofile%/.vscode`;
5. Restarting my system after all of the above.

Any help is much appreciated! 😊

  %23 Configuration

  VSCode: 1.75.1
  PIO IDE: v3.0.0
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `C:\Users\Mike\.platformio\penv\Scripts\platformio.exe --help`.
Error: Traceback (most recent call last):

  File "C:\Users\Mike\.platformio\python3\lib\runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\Users\Mike\.platformio\python3\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "C:\Users\Mike\.platformio\penv\Scripts\platformio.exe\__main__.py", line 4, in <module>

  File "C:\Users\Mike\.platformio\penv\lib\site-packages\platformio\__main__.py", line 59, in <module>

    @cli.result_callback()

TypeError: 'NoneType' object is not callable



	at c:\Users\Mike\.vscode\extensions\platformio.platformio-ide-3.0.0-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5362
	at ChildProcess.o (c:\Users\Mike\.vscode\extensions\platformio.platformio-ide-3.0.0-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4660)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by madmijk** [comment]
My bad. There was something up with my packages and/or Python version compatibility.
I stumbled upon a GitHub thread for something entirely different with a similar TypeError, and it was solved by installing `click` version 8.0.3:
```
pip install click==8.0.3
```
I had to uninstall some other packages that would become incompatible, and the rest is history.
