### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by delehub** [platformio/platformio-core-installer#2858]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.77.3
  PIO IDE: v2.4.3
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error: Could not find compatible PlatformIO Core. Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.
	at u.value (c:\Users\dele\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\platformio-node-helpers\dist\index.js:1:783624)
	at S.install (c:\Users\dele\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:4381)
	at c:\Users\dele\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:28144
	at D.d (d:\VsCode\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:46171)
	at D.withProgress (d:\VsCode\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:46014)
	at Object.withProgress (d:\VsCode\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:34084)
	at Object.startInstaller (c:\Users\dele\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:27559)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.activate (c:\Users\dele\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\extension.js:1:23007)
  ```

**Comment by ivankravets** [comment]
Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.
