### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by 7-Asn** [platformio/platformio-core-installer#2862]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.77.3
  PIO IDE: v3.1.1
  System: Linux, 5.15.0-69-generic, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an EnvironmentError: Missing dependencies for SOCKS support.

Error: Could not install PlatformIO Core: Command '['/home/asn/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.2
Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.29
Python version: 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/asn/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at /home/asn/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5303
	at ChildProcess.o (/home/asn/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4601)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Socket.emit (node:domain:475:12)
	at Pipe.<anonymous> (node:net:687:12)
  ```

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by ivankravets** [comment]
See https://stackoverflow.com/questions/38794015/pythons-requests-missing-dependencies-for-socks-support-when-using-socks5-fro
