### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by CreatorLarry** [platformio/platformio-core-installer#2882]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.77.3
  PIO IDE: v3.1.1
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error: ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 262, in __init__
    cache_entry = factory.get_wheel_cache_entry(source_link, name)
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 540, in get_wheel_cache_entry
    return self._wheel_cache.get_cache_entry(
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\cache.py", line 245, in get_cache_entry
    return CacheEntry(retval, persistent=True)
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\cache.py", line 197, in __init__
    self.origin = DirectUrl.from_json(origin_direct_url_path.read_text())
  File "C:\Users\admin\.platformio\penv\lib\site-packages\pip\_internal\models\direct_url.py", line 231, in from_json
    return cls.from_dict(json.loads(s))
  File "C:\Users\admin\.platformio\python3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\admin\.platformio\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\admin\.platformio\python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\admin\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 2.
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\admin\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\admin\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core

	at c:\Users\admin\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5303
	at ChildProcess.o (c:\Users\admin\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4601)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
