### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by chrisbensen** [platformio/platformio-core-installer#2891]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.76.2
  PIO IDE: v3.1.1
  System: Darwin, 22.3.0, arm64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `/Users/cbensen/.platformio/penv/bin/platformio --help`.
Error: Traceback (most recent call last):
  File "/Users/cbensen/.platformio/penv/bin/platformio", line 5, in <module>
    from platformio.__main__ import main
  File "/Users/cbensen/.platformio/penv/lib/python3.9/site-packages/platformio/__main__.py", line 21, in <module>
    from platformio import __version__, exception, maintenance
  File "/Users/cbensen/.platformio/penv/lib/python3.9/site-packages/platformio/maintenance.py", line 22, in <module>
    from platformio import __version__, app, exception, fs, telemetry
  File "/Users/cbensen/.platformio/penv/lib/python3.9/site-packages/platformio/telemetry.py", line 28, in <module>
    import requests
  File "/Users/cbensen/.platformio/penv/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/cbensen/.platformio/penv/lib/python3.9/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1 , currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168


	at /Users/cbensen/.vscode/extensions/platformio.platformio-ide-3.1.1-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:5303
	at ChildProcess.o (/Users/cbensen/.vscode/extensions/platformio.platformio-ide-3.1.1-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:4601)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core-installer/issues/2911
