### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Gyroxp** [platformio/platformio-core-installer#2912]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.78.0
  PIO IDE: v3.1.1
  System: Linux, 5.15.77-amd64-desktop, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.1.2
Platform: Linux-5.15.77-amd64-desktop-x86_64-with-glibc2.28
Python version: 3.7.3 (default, Nov  1 2022, 10:27:39) 
[GCC 8.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/ljw/.platformio/penv
/usr/bin/python3

	at /home/ljw/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5303
	at ChildProcess.o (/home/ljw/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4601)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1093:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by Gyroxp** [comment]
#85 'apt-get install python3-venv' resolve the issue.

**Comment by ivankravets** [comment]
What was your Linux distribution and version?
