### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by miaobuao** [platformio/platformio-core-installer#2959]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.78.0
  PIO IDE: v3.1.1
  System: Linux, 6.3.4-arch1-1, x64

  %23 Exception
  ```
  Error: /home/meo/.platformio/.cache/tmp/.piocore-installer-sm0owwsf/tmpxcr4iv3q/pioinstaller.zip/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
ERROR: Could not find a version that satisfies the requirement platformio (from versions: none)
ERROR: No matching distribution found for platformio
WARNING: There was an error checking the latest version of pip.
Error: Could not install PlatformIO Core: Command '['/home/meo/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.2
Platform: Linux-6.3.4-arch1-1-x86_64-with-glibc2.37
Python version: 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
Python path: /usr/bin/python3
Creating a virtual environment at /home/meo/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: https://pypi.doubanio.com

    at spawnOptions (/home/meo/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:226:25)
    at ChildProcess.o (/home/meo/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:170:13)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1093:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by ivankravets** [comment]
Please use official PyPi index and avoid using any espionage registries such as "Looking in indexes: https://pypi.doubanio.com"
