### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by jborges42** [platformio/platformio-core-installer#2962]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.78.2
  PIO IDE: v3.1.1
  System: Linux, 5.19.0-42-generic, x64

  %23 Exception
  ```
  Error: Error: Can not install PlatformIO Core due to a missed `distutils` package in your Python installation.
Please install this package manually using the OS package manager. For example:

$ apt-get install python3-venv

(MAY require administrator access `sudo`)
 -> Installer version: 1.1.2
Platform: Linux-5.19.0-42-generic-x86_64-with-glibc2.35
Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/borges/.platformio/penv

    at spawnOptions (/home/borges/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:226:25)
    at ChildProcess.o (/home/borges/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:170:13)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1112:16)
    at Socket.<anonymous> (node:internal/child_process:470:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-core-installer/issues/1774
