### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by vashilov** [platformio/platformio-core-installer#2973]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.78.2
  PIO IDE: v3.1.1
  System: Linux, 4.15.0-46-generic, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.1.2
Platform: Linux-4.15.0-46-generic-x86_64-with-glibc2.25
Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/nik/.platformio/penv
/usr/bin/python3

	at /home/nik/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5303
	at ChildProcess.o (/home/nik/.vscode/extensions/platformio.platformio-ide-3.1.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4601)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1112:16)
	at Socket.<anonymous> (node:internal/child_process:470:11)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by ivankravets** [comment]
Please re-test with the pre-release version. Navigate to the PlatformIO IDE extension in the VSCode and "Switch to the Pre-Release". Does it work now?
<img width="1125" alt="Screenshot 2023-06-02 at 13 16 00" src="https://github.com/platformio/platformio-vscode-ide/assets/1760209/ec0157fd-147c-4117-96bc-4e73e74c2e85">
