### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by yoann4d** [platformio/platformio-core-installer#2981]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.76.2
  PIO IDE: v3.1.1
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\Yoann\.platformio\python3\lib\importlib\_common.py", line 35, in _tempfile
    os.write(fd, reader())
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yoann\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 69, in <module>
    main()
  File "C:\Users\Yoann\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 61, in main
    bootstrap()
  File "C:\Users\Yoann\.platformio\.cache\tmp\get-platformio-1.1.2.py", line 45, in bootstrap
    import pioinstaller.__main__
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\Yoann\.platformio\.cache\tmp\.piocore-installer-tn5pgmfd\tmpd3fo4si7\pioinstaller.zip\pioinstaller\__main__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\Yoann\.platformio\.cache\tmp\.piocore-installer-tn5pgmfd\tmpd3fo4si7\pioinstaller.zip\pioinstaller\core.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\Yoann\.platformio\.cache\tmp\.piocore-installer-tn5pgmfd\tmpd3fo4si7\pioinstaller.zip\pioinstaller\home.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\Yoann\.platformio\.cache\tmp\.piocore-installer-tn5pgmfd\tmpd3fo4si7\pioinstaller.zip\requests\__init__.py", line 133, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\Yoann\.platformio\.cache\tmp\.piocore-installer-tn5pgmfd\tmpd3fo4si7\pioinstaller.zip\requests\utils.py", line 42, in <module>
  File "C:\Users\Yoann\.platformio\.cache\tmp\.piocore-installer-tn5pgmfd\tmpd3fo4si7\pioinstaller.zip\certifi\core.py", line 37, in where
  File "C:\Users\Yoann\.platformio\python3\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Users\Yoann\.platformio\python3\lib\importlib\resources.py", line 176, in _path_from_reader
    with _common._tempfile(opener_reader.read, suffix=norm_resource) as res:
  File "C:\Users\Yoann\.platformio\python3\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Users\Yoann\.platformio\python3\lib\importlib\_common.py", line 40, in _tempfile
    os.remove(raw_path)
PermissionError: [WinError 32] Le processus ne peut pas acc�der au fichier car ce fichier est utilis� par un autre processus: 'C:\\Users\\Yoann\\.platformio\\.cache\\tmp\\.piocore-installer-tn5pgmfd\\tmpeuuy1edlcacert.pem'

	at c:\Users\Yoann\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5303
	at ChildProcess.o (c:\Users\Yoann\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4601)
	at ChildProcess.emit (node:events:526:28)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment]
Please re-test with the pre-release version. Navigate to the PlatformIO IDE extension in the VSCode and "Switch to the Pre-Release". Does it work now?
<img width="1125" alt="Screenshot 2023-06-02 at 13 16 00" src="https://github.com/platformio/platformio-vscode-ide/assets/1760209/ec0157fd-147c-4117-96bc-4e73e74c2e85">
