### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ComicAuthor** [platformio/platformio-core-installer#2984]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.76.2
  PIO IDE: v3.1.1
  System: Windows_NT, 10.0.22624, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO Core version 5.0.4 does not match version requirements >=6.1.6.

    at spawnOptions (c:\Users\Xin\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:226:25)
    at ChildProcess.o (c:\Users\Xin\.vscode\extensions\platformio.platformio-ide-3.1.1-win32-x64\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:170:13)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment]
Please update the PlatformIO IDE extension for VSCode to 3.2.0 https://github.com/platformio/platformio-vscode-ide/releases/tag/v3.2.0
