### ISSUE TITLE
What happened with Installation Manager?

### ISSUE THREAD

**Issue by WPluim** [platformio/platformio-core-installer#2991]
%23 Description of problem
 I see some different messages each time I try to use VSCode (with pio). Pio in a browser seems to work.

 %23 Configuration
  VSCode: 1.79.0
  PIO IDE: v3.2.0
  System: Windows_NT, 10.0.19045, x64

%23 Exception (s!)
  ```
1 WSPROTO  Error:   Could not find a version that satisfies the requirement wsproto==1.2.* (from platformio) (from versions: 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.15.0, 1.0.0)
No matching distribution found for wsproto==1.2.* (from platformio)

2  AIOFILES  Error:   Cache entry deserialization failed, entry ignored   Could not find a version that satisfies the requirement aiofiles==23.1.* (from platformio) (from versions: 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0)
No matching distribution found for aiofiles==23.1.* (from platformio)

3 TABULATE  Error:   Could not find a version that satisfies the requirement tabulate==0.9.* (from platformio) (from versions: 0.3, 0.4.2, 0.4.3, 0.4.4, 0.5, 0.5.1, 0.6, 0.7, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6b0, 0.7.6rc0, 0.7.7, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.8.10)
No matching distribution found for tabulate==0.9.* (from platformio)

4 You are using pip version 9.0.1, however version 23.1.2 is available. 
NOT true: Requirement already satisfied: pip in c:\python311\lib\site-packages (23.1.2)

5 Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
YES, I tried, but that did not help, sorry.

 Command '['C:\\Users\\Pluim\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.3
Platform: Windows-10
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\Pluim\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\Pluim\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Using cached https://files.pythonhosted.org/packages/d7/64/e606dc0a4aa68352bc2147a3f1a1fdb517af1063dcd9b908603036020396/platformio-6.1.7-py3-none-any.whl
Collecting colorama (from platformio)
  Using cached https://files.pythonhosted.org/packages/77/8b/7550e87b2d308a1b711725dfaddc19c695f8c5fa413c640b2be01662f4e6/colorama-0.4.5-py2.py3-none-any.whl
Collecting urllib3<2 (from platformio)
  Using cached https://files.pythonhosted.org/packages/c5/05/c214b32d21c0b465506f95c4f28ccbcba15022e000b043b72b3df7728471/urllib3-1.26.16-py2.py3-none-any.whl
Collecting click<9,>=8.0.4 (from platformio)
  Using cached https://files.pythonhosted.org/packages/4a/a8/0b2ced25639fb20cc1c9784de90a8c25f9504a7f18cd8b5397bd61696d7d/click-8.0.4-py3-none-any.whl
Collecting semantic-version==2.10.* (from platformio)
  Using cached https://files.pythonhosted.org/packages/6a/23/8146aad7d88f4fcb3a6218f41a60f6c2d4e3a72de72da1825dc7c8f7877c/semantic_version-2.10.0-py2.py3-none-any.whl
Collecting wsproto==1.2.* (from platformio)

	at c:\Users\Pluim\.vscode\extensions\platformio.platformio-ide-3.2.0-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.o (c:\Users\Pluim\.vscode\extensions\platformio.platformio-ide-3.2.0-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by WPluim** [comment]
Sorry, I don't understand what you mean by 'espionage'? It must be the installer that makes the choice?
I'm using MS VS Code with PlatformIO. PlatformIO wants to update itself. That does not function properly.
I can update on the CLI/Powershell and now all requirements are satisfied, but it still does not work.

PS C:\Users\Pluim\.platformio\penv\Scripts> pip install platformio
Requirement already satisfied: platformio in c:\python311\lib\site-packages (6.1.7)
Requirement already satisfied: bottle==0.12.* in c:\python311\lib\site-packages (from platformio) (0.12.25)
Requirement already satisfied: click<9,>=8.0.4 in c:\python311\lib\site-packages (from platformio) (8.1.3)
Requirement already satisfied: colorama in c:\python311\lib\site-packages (from platformio) (0.4.6)
Requirement already satisfied: marshmallow==3.* in c:\python311\lib\site-packages (from platformio) (3.19.0)
Requirement already satisfied: pyelftools<1,>=0.27 in c:\python311\lib\site-packages (from platformio) (0.29)
Requirement already satisfied: pyserial==3.5.* in c:\python311\lib\site-packages (from platformio) (3.5)
Requirement already satisfied: requests==2.* in c:\python311\lib\site-packages (from platformio) (2.31.0)
Requirement already satisfied: urllib3<2 in c:\python311\lib\site-packages (from platformio) (1.26.16)
Requirement already satisfied: semantic-version==2.10.* in c:\python311\lib\site-packages (from platformio) (2.10.0)
Requirement already satisfied: tabulate==0.9.* in c:\python311\lib\site-packages (from platformio) (0.9.0)
Requirement already satisfied: aiofiles==23.1.* in c:\python311\lib\site-packages (from platformio) (23.1.0)
Requirement already satisfied: ajsonrpc==1.* in c:\python311\lib\site-packages (from platformio) (1.2.0)
Requirement already satisfied: starlette==0.26.* in c:\python311\lib\site-packages (from platformio) (0.26.1)
Requirement already satisfied: uvicorn==0.22.* in c:\python311\lib\site-packages (from platformio) (0.22.0)
Requirement already satisfied: wsproto==1.2.* in c:\python311\lib\site-packages (from platformio) (1.2.0)
Requirement already satisfied: packaging>=17.0 in c:\python311\lib\site-packages (from marshmallow==3.*->platformio) (23.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python311\lib\site-packages (from requests==2.*->platformio) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests==2.*->platformio) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python311\lib\site-packages (from requests==2.*->platformio) (2023.5.7)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\python311\lib\site-packages (from starlette==0.26.*->platformio) (3.7.0)
Requirement already satisfied: h11>=0.8 in c:\python311\lib\site-packages (from uvicorn==0.22.*->platformio) (0.14.0)
Requirement already satisfied: sniffio>=1.1 in c:\python311\lib\site-packages (from anyio<5,>=3.4.0->starlette==0.26.*->platformio) (1.3.0)
PS C:\Users\Pluim\.platformio\penv\Scripts>
