### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by 7doctor7** [platformio/platformio-core-installer#2992]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.79.0
  PIO IDE: v3.2.0
  System: Linux, 4.15.0-212-generic, x64

  %23 Exception
  ```
  Error:   Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement aiofiles==23.1.* (from platformio) (from versions: 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0)
No matching distribution found for aiofiles==23.1.* (from platformio)
Error: Could not install PlatformIO Core: Command '['/home/doctor/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.3
Platform: Linux-4.15.0-212-generic-x86_64-with-glibc2.25
Python version: 3.6.9 (default, Mar 10 2023, 16:46:00) 
[GCC 8.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/doctor/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Using cached https://files.pythonhosted.org/packages/d7/64/e606dc0a4aa68352bc2147a3f1a1fdb517af1063dcd9b908603036020396/platformio-6.1.7-py3-none-any.whl
Collecting bottle==0.12.* (from platformio)
  Using cached https://files.pythonhosted.org/packages/bb/1f/5977ea88c6a3df6199db97d320e5da816d415d1eb75a987a1f6823d5cc9d/bottle-0.12.25-py3-none-any.whl
Collecting aiofiles==23.1.* (from platformio)

	at /home/doctor/.vscode/extensions/platformio.platformio-ide-3.2.0-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5300
	at ChildProcess.o (/home/doctor/.vscode/extensions/platformio.platformio-ide-3.2.0-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at Socket.<anonymous> (node:internal/child_process:479:11)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by ivankravets** [comment]
Please remove `~/.cache/pip` folder and restart VSCode.
