### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by LarsMygh** [platformio/platformio-core-installer#2993]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.79.0
  PIO IDE: v3.2.0
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: WARNING: 401 Error, Credentials not correct for https://artifactory.wsa.com/api/pypi/pypi/simple/platformio/
ERROR: Could not find a version that satisfies the requirement platformio (from versions: none)
ERROR: No matching distribution found for platformio
WARNING: 401 Error, Credentials not correct for https://artifactory.wsa.com/api/pypi/pypi/simple/pip/
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\AU000B7E\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.1.3
Platform: Windows-10
Python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\AU000B7E\AppData\Local\Programs\Python\Python311\python.exe
Creating a virtual environment at C:\Users\AU000B7E\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: https://au000b7e:****@artifactory.wsa.com/api/pypi/pypi/simple

	at c:\Users\AU000B7E\.vscode\extensions\platformio.platformio-ide-3.2.0-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.o (c:\Users\AU000B7E\.vscode\extensions\platformio.platformio-ide-3.2.0-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment]
> https://au000b7e:****@artifactory.wsa.com/api/pypi/pypi/simple


Please use official PyPi index https://pypi.org/
