### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by borrmi** [platformio/platformio-core-installer#3008]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.79.2
  PIO IDE: v2.0.0
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\pioinstaller\python.py", line 163, in find_compatible_pythons
  File "C:\Users\borrm\.platformio\python3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\borrm\.platformio\python3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\borrm\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe', 'C:\\Users\\borrm\\.platformio\\.cache\\tmp\\get-platformio-0.3.4.py', '--no-shutdown-piohome', 'check', 'python']' returned non-zero exit status 9009.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\borrm\.platformio\.cache\tmp\get-platformio-0.3.4.py", line 69, in <module>
    main()
  File "C:\Users\borrm\.platformio\.cache\tmp\get-platformio-0.3.4.py", line 61, in main
    bootstrap()
  File "C:\Users\borrm\.platformio\.cache\tmp\get-platformio-0.3.4.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\pioinstaller\__main__.py", line 122, in main
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\click\core.py", line 829, in __call__
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\click\core.py", line 782, in main
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\click\core.py", line 1236, in invoke
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\click\core.py", line 1066, in invoke
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\click\core.py", line 610, in invoke
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\click\decorators.py", line 21, in new_func
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\pioinstaller\__main__.py", line 52, in cli
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\pioinstaller\penv.py", line 52, in create_core_penv
  File "C:\Users\borrm\.platformio\.cache\tmp\.piocore-installer-0t_uk6xk\tmppyjfxz68\pioinstaller.zip\pioinstaller\python.py", line 176, in find_compatible_pythons
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 38: invalid start byte
 -> Installer version: 0.3.4
Platform: Windows-10
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\borrm\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\borrm\.platformio\penv

	at c:\Users\borrm\.vscode\extensions\platformio.platformio-ide-2.0.0\node_modules\platformio-node-helpers\dist\index.js:1:4911
	at ChildProcess.c (c:\Users\borrm\.vscode\extensions\platformio.platformio-ide-2.0.0\node_modules\platformio-node-helpers\dist\index.js:1:4807)
	at ChildProcess.emit (node:events:513:28)
	at cp.emit (c:\Users\borrm\.vscode\extensions\platformio.platformio-ide-2.0.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment]
> VSCode: 1.79.2
> PIO IDE: v2.0.0

Please update VSCode and PlatformIO IDE to the latest version. See https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide
