### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by RubberDuckUp** [platformio/platformio-core-installer#3011]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.79.2
  PIO IDE: v2.4.3
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: Could not find compatible PlatformIO Core. Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.
    at u.progress (c:\Users\14235\.vscode\extensions\platformio.platformio-ide-2.4.3\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\installer\stages\platformio-core.js:150:9)
    at S.install (c:\Users\14235\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\webpack:\platformio-ide\src\installer\manager.js:90:5)
    at c:\Users\14235\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\webpack:\platformio-ide\src\main.js:209:36
    at y.d (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:44972)
    at y.withProgress (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:44815)
    at Object.title [as withProgress] (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:34878)
    at Object.startInstaller (c:\Users\14235\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\webpack:\platformio-ide\src\main.js:184:9)
    at process.handleUseDevelopmentPIOCoreConfiguration (node:internal/process/task_queues:96:5)
    at Object.activate (c:\Users\14235\.vscode\extensions\platformio.platformio-ide-2.4.3\dist\webpack:\platformio-ide\src\main.js:61:34)
  ```

**Comment by ivankravets** [comment]
> Error: Could not find compatible PlatformIO Core. Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.

Please enable built-in PlatformIO Core in the VSCode settings. Also, update the VSCode and PlatformIO IDE extension to the latest versions. You use outdated PIO IDE: v2.4.3
