### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by lisheng1365** [platformio/platformio-core-installer#3022]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.79.2
  PIO IDE: v3.2.0
  System: Linux, 5.19.0-46-generic, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/home/steve/.platformio/.cache/tmp/get-platformio-1.1.3.py", line 69, in <module>
    main()
  File "/home/steve/.platformio/.cache/tmp/get-platformio-1.1.3.py", line 61, in main
    bootstrap()
  File "/home/steve/.platformio/.cache/tmp/get-platformio-1.1.3.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/pioinstaller/__main__.py", line 133, in main
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/click/core.py", line 1128, in __call__
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/click/core.py", line 1053, in main
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/click/core.py", line 1637, in invoke
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/click/core.py", line 1395, in invoke
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/click/core.py", line 754, in invoke
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/click/decorators.py", line 26, in new_func
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/pioinstaller/__main__.py", line 61, in cli
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/pioinstaller/core.py", line 70, in install_platformio_core
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/pioinstaller/core.py", line 98, in _install_platformio_core
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/pioinstaller/penv.py", line 58, in create_core_penv
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/pioinstaller/python.py", line 70, in fetch_portable_python
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/pioinstaller/python.py", line 97, in get_portable_python_url
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/requests/api.py", line 73, in get
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/requests/api.py", line 59, in request
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/requests/sessions.py", line 589, in request
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/requests/sessions.py", line 703, in send
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/requests/adapters.py", line 454, in send
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/requests/adapters.py", line 350, in get_connection
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/requests/adapters.py", line 215, in proxy_manager_for
  File "/home/steve/.platformio/.cache/tmp/.piocore-installer-i_gsgn2r/tmpasqqzfg1/pioinstaller.zip/requests/adapters.py", line 61, in SOCKSProxyManager
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
 -> Installer version: 1.1.3
Platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/steve/.platformio/penv
/usr/bin/python3

	at /home/steve/.vscode/extensions/platformio.platformio-ide-3.2.0-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5300
	at ChildProcess.o (/home/steve/.vscode/extensions/platformio.platformio-ide-3.2.0-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at Socket.<anonymous> (node:internal/child_process:479:11)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/4822
