### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Mr-MaxWang** [platformio/platformio-core-installer#3031]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.80.0
  PIO IDE: v3.3.0
  System: Darwin, 22.5.0, arm64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an OSError: Missing dependencies for SOCKS support.

WARNING: There was an error checking the latest version of pip.
Error: Could not install PlatformIO Core: Command '['/Users/max/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.0
Platform: macOS-13.4.1
Python version: 3.11.4 (main, Jun 15 2023, 07:55:38) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Python path: /opt/homebrew/opt/python@3.11/bin/python3.11
Creating a virtual environment at /Users/max/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

    at /Users/max/.vscode/extensions/platformio.platformio-ide-3.3.0-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:5300
    at ChildProcess.i (/Users/max/.vscode/extensions/platformio.platformio-ide-3.3.0-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1121:16)
    at Socket.<anonymous> (node:internal/child_process:479:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/4822
