### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by OE3MZC-Mike** [platformio/platformio-core-installer#3036]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.80.1
  PIO IDE: v2.5.0
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\oe3mzc\AppData\Local\Programs\Python\Python39\python.exe
Creating a virtual environment at C:\Users\oe3mzc\.platformio\penv
C:\Users\oe3mzc\AppData\Local\Programs\Python\Python39\python.exe

	at c:\Users\oe3mzc\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\platformio-node-helpers\dist\index.js:1:5227
	at ChildProcess.c (c:\Users\oe3mzc\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\platformio-node-helpers\dist\index.js:1:5121)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at cp.emit (c:\Users\oe3mzc\.vscode\extensions\platformio.platformio-ide-2.5.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode and PlatformIO IDE extension to the latest version https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide
