### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by xzerol** [platformio/platformio-core-installer#3040]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.80.2
  PIO IDE: v3.3.1
  System: Darwin, 22.3.0, arm64

  %23 Exception
  ```
  Error: ERROR: Could not find a version that satisfies the requirement platformio (from versions: none)
ERROR: No matching distribution found for platformio
Error: Could not install PlatformIO Core: Command '['/Users/xzerol/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: macOS-13.2.1
Python version: 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]
Python path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
Creating a virtual environment at /Users/xzerol/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: https://download.pytorch.org/whl/cu113

	at /Users/xzerol/.vscode/extensions/platformio.platformio-ide-3.3.1-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:5300
	at ChildProcess.c (/Users/xzerol/.vscode/extensions/platformio.platformio-ide-3.3.1-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at Socket.<anonymous> (node:internal/child_process:479:11)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3129
