### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ExIlIsT** [platformio/platformio-core-installer#3041]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.80.2
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\sandrog\.platformio\.cache\tmp\get-platformio-1.2.1.py", line 71, in <module>
    main()
  File "C:\Users\sandrog\.platformio\.cache\tmp\get-platformio-1.2.1.py", line 63, in main
    bootstrap()
  File "C:\Users\sandrog\.platformio\.cache\tmp\get-platformio-1.2.1.py", line 49, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\click\core.py", line 1637, in invoke
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\pioinstaller\core.py", line 98, in _install_platformio_core
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\pioinstaller\penv.py", line 71, in create_core_penv
  File "C:\Users\sandrog\.platformio\.cache\tmp\.piocore-installer-yfjauw2t\tmp_2i8nrkm\pioinstaller.zip\pioinstaller\penv.py", line 141, in init_state
  File "C:\Program Files\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 1260] Dieses Programm wurde durch eine Gruppenrichtlinie geblockt. Wenden Sie sich an den Systemadministrator, um weitere Informationen zu erhalten
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Python path: C:\Program Files\Python38\python.exe
Creating a virtual environment at C:\Users\sandrog\.platformio\penv

	at c:\Users\sandrog\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\sandrog\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ExIlIsT** [comment]
seem to be unsuffient rights
