### ISSUE TITLE
Installation Manager ERROR: HTTP error 403

### ISSUE THREAD

**Issue by vicsun0425** [platformio/platformio-core-installer#3042]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.81.0
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error:   ERROR: HTTP error 403 while getting https://pypi.tuna.tsinghua.edu.cn/packages/a9/e1/57ea5e5cce83586b7c4a5b456c77fd7154a80e1a649a79d59e9e54b06cf9/platformio-6.1.9-py3-none-any.whl%23sha256=045b1b950e7f237a56c2e6fddbd0115ea024dc9adb716d4cc35fab56a1d0eb14 (from https://pypi.tuna.tsinghua.edu.cn/simple/platformio/) (requires-python:>=3.6)
ERROR: Could not install requirement platformio from https://pypi.tuna.tsinghua.edu.cn/packages/a9/e1/57ea5e5cce83586b7c4a5b456c77fd7154a80e1a649a79d59e9e54b06cf9/platformio-6.1.9-py3-none-any.whl%23sha256=045b1b950e7f237a56c2e6fddbd0115ea024dc9adb716d4cc35fab56a1d0eb14 because of HTTP error 403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/a9/e1/57ea5e5cce83586b7c4a5b456c77fd7154a80e1a649a79d59e9e54b06cf9/platformio-6.1.9-py3-none-any.whl for URL https://pypi.tuna.tsinghua.edu.cn/packages/a9/e1/57ea5e5cce83586b7c4a5b456c77fd7154a80e1a649a79d59e9e54b06cf9/platformio-6.1.9-py3-none-any.whl%23sha256=045b1b950e7f237a56c2e6fddbd0115ea024dc9adb716d4cc35fab56a1d0eb14 (from https://pypi.tuna.tsinghua.edu.cn/simple/platformio/) (requires-python:>=3.6)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: C:\Users\Administrator\.platformio\penv\Scripts\python.exe -m pip install --upgrade pip
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\Administrator\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\Administrator\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\Administrator\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting platformio

    at c:\Users\Administrator\.vscode\extensions\platformio.platformio-ide-3.3.1\node_modules\platformio-node-helpers\dist\index.js:1:5300
    at ChildProcess.c (c:\Users\Administrator\.vscode\extensions\platformio.platformio-ide-3.3.1\node_modules\platformio-node-helpers\dist\index.js:1:4598)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1121:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core-installer/issues/3129
