### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by nicewo** [platformio/platformio-core-installer#3051]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.81.0
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\.platformio\penv\Lib\site-packages\pip\_vendor\certifi\cacert.pem

Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Program Files\Python311\python.exe
Creating a virtual environment at C:\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Obtaining dependency information for platformio from https://files.pythonhosted.org/packages/e7/76/97f6ac76cd98432b761726728c549df18f1086dbf64481bb5011e1978090/platformio-6.1.10-py3-none-any.whl.metadata
  Downloading platformio-6.1.10-py3-none-any.whl.metadata (6.9 kB)
Collecting bottle==0.12.* (from platformio)
  Using cached bottle-0.12.25-py3-none-any.whl (90 kB)

    at c:\Users\MYusufGültekin\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
    at ChildProcess.c (c:\Users\MYusufGültekin\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1121:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment]
Please remove `C:\.platformio\` folder and restart VSCode.
