### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Jaa55** [platformio/platformio-core-installer#3052]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.81.0
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19044, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\importlib\_common.py", line 89, in _tempfile
    os.write(fd, reader())
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\USER\.platformio\.cache\tmp\.piocore-installer-li11hm5u\tmpc35vngv8\pioinstaller.zip\pioinstaller\home.py", line 18, in <module>
  File "C:\Users\USER\.platformio\.cache\tmp\.piocore-installer-li11hm5u\tmpc35vngv8\pioinstaller.zip\requests\__init__.py", line 147, in <module>
  File "C:\Users\USER\.platformio\.cache\tmp\.piocore-installer-li11hm5u\tmpc35vngv8\pioinstaller.zip\requests\utils.py", line 63, in <module>
  File "C:\Users\USER\.platformio\.cache\tmp\.piocore-installer-li11hm5u\tmpc35vngv8\pioinstaller.zip\certifi\core.py", line 72, in where
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\importlib\_common.py", line 95, in _tempfile
    os.remove(raw_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USER\\.platformio\\.cache\\tmp\\.piocore-installer-li11hm5u\\tmpkbqzkkbvcacert.pem'
Error: Could not find compatible Python 3.6 or above in your system.Please install the latest official Python 3 and restart installation:
https://docs.platformio.org/page/faq.html%23install-python-interpreter
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\USER\AppData\Local\Programs\Python\Python310\python.exe
Creating a virtual environment at C:\Users\USER\.platformio\penv

    at c:\Users\USER\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
    at ChildProcess.c (c:\Users\USER\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1121:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment]
OSError: [Errno 28] No space left on device
