### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Xiaoming1212** [platformio/platformio-core-installer#3056]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.81.1
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\connection.py", line 174, in _new_conn
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\util\connection.py", line 95, in create_connection
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\util\connection.py", line 85, in create_connection
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\connectionpool.py", line 714, in urlopen
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\connectionpool.py", line 403, in _make_request
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\connectionpool.py", line 1053, in _validate_conn
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\connection.py", line 363, in connect
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\connection.py", line 179, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000017903560FD0>, 'Connection to api.registry.platformio.org timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\requests\adapters.py", line 486, in send
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\connectionpool.py", line 798, in urlopen
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.registry.platformio.org', port=443): Max retries exceeded with url: /v3/packages/platformio/tool/python-portable (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017903560FD0>, 'Connection to api.registry.platformio.org timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp\get-platformio-1.2.1.py", line 71, in <module>
    main()
  File "C:\.platformio\.cache\tmp\get-platformio-1.2.1.py", line 63, in main
    bootstrap()
  File "C:\.platformio\.cache\tmp\get-platformio-1.2.1.py", line 49, in bootstrap
    pioinstaller.__main__.main()
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\click\core.py", line 1637, in invoke
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\pioinstaller\core.py", line 98, in _install_platformio_core
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\pioinstaller\penv.py", line 58, in create_core_penv
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\pioinstaller\python.py", line 70, in fetch_portable_python
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\pioinstaller\python.py", line 97, in get_portable_python_url
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\requests\api.py", line 73, in get
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\requests\api.py", line 59, in request
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\requests\sessions.py", line 589, in request
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\requests\sessions.py", line 703, in send
  File "C:\.platformio\.cache\tmp\.piocore-installer-rumpdjcb\tmpgwas9zy2\pioinstaller.zip\requests\adapters.py", line 507, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.registry.platformio.org', port=443): Max retries exceeded with url: /v3/packages/platformio/tool/python-portable (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017903560FD0>, 'Connection to api.registry.platformio.org timed out. (connect timeout=10)'))
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\����\AppData\Local\Programs\Python\Python311\python.exe
Creating a virtual environment at C:\.platformio\penv
C:\Users\����\AppData\Local\Programs\Python\Python311\python.exe

	at c:\Users\彦明\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\彦明\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment]
It looks like a network issue. Please restart VSCode.
