### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by SoiMixi** [platformio/platformio-core-installer#3058]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.81.1
  PIO IDE: v0.0.2
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\trant\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\trant\.platformio\penv
C:\Users\trant\.platformio\python3\python.exe

	at c:\Users\trant\.vscode\extensions\leviyanx.aide1-0.0.2-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5303
	at ChildProcess.o (c:\Users\trant\.vscode\extensions\leviyanx.aide1-0.0.2-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4601)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core-installer/issues/3036
