### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Profprog87** [platformio/platformio-core-installer#3060]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.81.1
  PIO IDE: v3.3.1
  System: Linux, 6.2.0-26-generic, x64

  %23 Exception
  ```
  Error: Error: Could not install PlatformIO Core: Command '['/home/malte/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' died with <Signals.SIGSEGV: 11>.
 -> Installer version: 1.2.1
Platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.9
Python version: 3.6.3 (default, Aug 14 2023, 17:19:58) 
[GCC 11.4.0]
Python path: /usr/local/bin/python3
Creating a virtual environment at /home/malte/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at /home/malte/.vscode/extensions/platformio.platformio-ide-3.3.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5300
	at ChildProcess.c (/home/malte/.vscode/extensions/platformio.platformio-ide-3.3.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at Socket.<anonymous> (node:internal/child_process:479:11)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by ivankravets** [comment]
Have you resolved this issue after VSCode restart?
