### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by fushengshen** [platformio/platformio-core-installer#3061]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.81.1
  PIO IDE: v2.5.4
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO Core version 4.0.3 does not match version requirements >=6.

	at c:\Users\22818\.vscode\extensions\platformio.platformio-ide-2.5.4-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5308
	at ChildProcess.o (c:\Users\22818\.vscode\extensions\platformio.platformio-ide-2.5.4-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4691)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ivankravets** [comment]
Please update VSCode and PlatformIO IDE extension to the latest version https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide
