### ISSUE TITLE
python3.11.5 Prompt that the file cannot be found

### ISSUE THREAD

**Issue by aa2013** [platformio/platformio-core-installer#3063]
+ System: Windows10.
+ Python version: Python 3.11.5
+ Installation process:
I download  [platformio.py](https://docs.platformio.org/en/latest/core/installation/methods/installer-script.html)  and used the `Python get-platformio.py` command to install it, but I was prompted that I couldn't find the file. I don't know why this happened.
+ Error message:
```
C:\Users\admin\Desktop>python311 get-platformio.py
Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Python path: D:\env\Python\Python311\python311.exe
Creating a virtual environment at C:\Users\admin\.platformio\penv
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\get-platformio.py", line 70, in <module>
    main()
  File "C:\Users\admin\Desktop\get-platformio.py", line 62, in main
    bootstrap()
  File "C:\Users\admin\Desktop\get-platformio.py", line 48, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\click\core.py", line 1637, in invoke
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\pioinstaller\core.py", line 98, in _install_platformio_core
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\pioinstaller\penv.py", line 71, in create_core_penv
  File "C:\Users\admin\Desktop\.piocore-installer-6no7uise\tmpiejwyy3o\pioinstaller.zip\pioinstaller\penv.py", line 141, in init_state
  File "D:\env\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\env\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\env\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\env\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by ivankravets** [comment]
Do you use any espionage software (3rd party antivirus tools, russian software)?
