### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by jaarmstrong44** [platformio/platformio-core-installer#3064]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.81.1
  PIO IDE: v2.1.0
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  TypeError: The "path" argument must be of type string. Received undefined
	at new NodeError (node:internal/errors:387:5)
	at validateString (node:internal/validators:121:11)
	at Object.dirname (node:path:648:5)
	at t.value (c:\Users\Jason\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:29951)
	at async t.value (c:\Users\Jason\.vscode\extensions\platformio.platformio-ide-2.1.0\node_modules\platformio-node-helpers\dist\index.js:1:27882)
	at async t.default.install (c:\Users\Jason\.vscode\extensions\platformio.platformio-ide-2.1.0\dist\extension.js:1:23075)
	at async c:\Users\Jason\.vscode\extensions\platformio.platformio-ide-2.1.0\dist\extension.js:1:6210
  ```

**Comment by ivankravets** [comment]
Please update VSCode and PlatformIO IDE extension to the latest version https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide
