### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Wellywen** [platformio/platformio-core-installer#3069]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.82.0
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.22621, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\user\.platformio\.cache\tmp\get-platformio-1.2.1.py", line 71, in <module>
    main()
  File "C:\Users\user\.platformio\.cache\tmp\get-platformio-1.2.1.py", line 63, in main
    bootstrap()
  File "C:\Users\user\.platformio\.cache\tmp\get-platformio-1.2.1.py", line 49, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\click\core.py", line 1659, in invoke
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\click\core.py", line 1659, in invoke
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\pioinstaller\__main__.py", line 113, in core_check
  File "C:\Users\user\.platformio\.cache\tmp\.piocore-installer-_dnwhih9\tmpgze_6ky5\pioinstaller.zip\pioinstaller\core.py", line 169, in check
  File "C:\Users\user\.platformio\python3\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.platformio\python3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.platformio\python3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\.platformio\python3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 4551] �������� Device Guard�� ����Ͽ� �� ���� �����߽��ϴ�. �ڼ��� ������ ���� ����ڿ��� �����ϼ���

	at c:\Users\user\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\user\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core-installer/issues/3111
