### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Jinn0316** [platformio/platformio-core-installer#3070]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.82.1
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.17763, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an OSError: Missing dependencies for SOCKS support.

Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\jinn\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\jinn\AppData\Local\Programs\Python\Python310\python.exe
Creating a virtual environment at C:\Users\jinn\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at c:\Users\jinn\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\jinn\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/4822
