### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by tsheo4303** [platformio/platformio-core-installer#3081]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.82.2
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\_internal\utils\misc.py", line 40, in <module>
    from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 548, in <module>
    from pip._vendor.tenacity._asyncio import AsyncRetrying  %23 noqa:E402,I100
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tsheo4303\.platformio\penv\Lib\site-packages\pip\_vendor\tenacity\_asyncio.py", line 21, in <module>
    from asyncio import sleep
  File "c:\users\tsheo4303\appdata\roaming\python\python311\site-packages\asyncio\__init__.py", line 21, in <module>
    from .base_events import *
  File "c:\users\tsheo4303\appdata\roaming\python\python311\site-packages\asyncio\base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^^^^^
SyntaxError: invalid syntax
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\tsheo4303\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\tsheo4303\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\tsheo4303\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at c:\Users\tsheo4303\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at ChildProcess.c (c:\Users\tsheo4303\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment]
Try please https://github.com/platformio/platformio-core-installer/issues/3111
