### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Alfa3du30** [platformio/platformio-core-installer#3082]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.83.0
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
	at c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
	at c (c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
	at b (c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5197)
	at B (c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4312)
	at c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5253
	at new Promise (<anonymous>)
	at X (c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5232)
	at pA (c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:951058)
	at async xA.loadCoreState (c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:958106)
	at async xA.install (c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:962052)
	at async k.install (c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\dist\extension.js:1:9310)
	at async c:\Users\Nolan\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\dist\extension.js:1:45166
  ```

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core-installer/issues/3111
