### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by EnkiAnnunaki** [platformio/platformio-core-installer#3090]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.83.1
  PIO IDE: v2.5.0
  System: Linux, 6.2.0-1014-azure, x64

  %23 Exception
  ```
  Error: Could not find compatible PlatformIO Core. Please enable `platformio-ide.useBuiltinPIOCore` setting and restart IDE.
    at u.install (/home/codespace/.vscode-remote/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/installer/stages/platformio-core.js:149:13)
    at S.install (/home/codespace/.vscode-remote/extensions/platformio.platformio-ide-2.5.0/dist/webpack:/platformio-ide/src/installer/manager.js:83:19)
    at /home/codespace/.vscode-remote/extensions/platformio.platformio-ide-2.5.0/dist/webpack:/platformio-ide/src/main.js:208:20
    at k.d (/vscode/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:124:46049)
    at k.withProgress (/vscode/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:124:45912)
    at Object.vscode [as withProgress] (/vscode/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:141:31573)
    at Object.patchOSEnviron (/home/codespace/.vscode-remote/extensions/platformio.platformio-ide-2.5.0/dist/webpack:/platformio-ide/src/main.js:181:18)
    at Object.activate (/home/codespace/.vscode-remote/extensions/platformio.platformio-ide-2.5.0/dist/webpack:/platformio-ide/src/main.js:59:10)
  ```

**Comment by ivankravets** [comment]
Please update VSCode and PlatformIO IDE extension to the latest version https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide
