### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by dericpage** [platformio/platformio-core-installer#3093]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.83.1
  PIO IDE: v2.5.4
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: Error: Can not install PlatformIO Core due to a missed `distutils` package in your Python installation.
Please install this package manually using the OS package manager. For example:

$ apt-get install python3-venv

(MAY require administrator access `sudo`)
 -> Installer version: 1.1.2
Platform: Windows-10
Python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Python path: C:\Users\deric\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\deric\.platformio\penv

	at c:\Users\deric\.vscode\extensions\platformio.platformio-ide-2.5.4-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5308
	at ChildProcess.o (c:\Users\deric\.vscode\extensions\platformio.platformio-ide-2.5.4-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4691)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment]
> PIO IDE: v2.0.1

Please update VSCode and PlatformIO IDE extension to the latest versions.
