### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by enmabybella** [platformio/platformio-core-installer#3098]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.83.1
  PIO IDE: v2.5.0
  System: Darwin, 23.1.0, arm64

  %23 Exception
  ```
  Error: Error: Can not install PlatformIO Core due to a missed `distutils` package in your Python installation.
Please install this package manually using the OS package manager. For example:

$ apt-get install python3-venv

(MAY require administrator access `sudo`)
 -> Installer version: 1.1.2
Platform: macOS-14.1
Python version: 3.9.6 (default, Oct  1 2023, 17:38:10) 
[Clang 15.0.0 (clang-1500.0.40.1)]
Python path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
Creating a virtual environment at /Users/enmanuelriveradelarosa/.platformio/penv

    at cmd (/Users/enmanuelriveradelarosa/.vscode/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:187:25)
    at ChildProcess.c (/Users/enmanuelriveradelarosa/.vscode/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:177:7)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:322:12)
  ```

**Comment by ivankravets** [comment]
Please update VSCode and PlatformIO IDE extension to the latest version https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide
