### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Cedric-ndasenga** [platformio/platformio-core-installer#3104]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.83.1
  PIO IDE: v2.0.1
  System: Linux, 6.2.0-36-generic, x64

  %23 Exception
  ```
  Error: Error: Can not install PlatformIO Core due to a missed `distutils` package in your Python installation.
Please install this package manually using the OS package manager. For example:

$ apt-get install python3-distutils

(MAY require administrator access `sudo`)
 -> Installer version: 0.3.4
Platform: Linux-6.2.0-36-generic-x86_64-with-glibc2.37
Python version: 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/dric/.platformio/penv

	at /home/dric/.vscode/extensions/platformio.platformio-ide-2.0.1/node_modules/platformio-node-helpers/dist/index.js:1:4911
	at ChildProcess.c (/home/dric/.vscode/extensions/platformio.platformio-ide-2.0.1/node_modules/platformio-node-helpers/dist/index.js:1:4807)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)
  ```

**Comment by ivankravets** [comment]
> PIO IDE: v2.0.1

Please update VSCode and PlatformIO IDE extension to the latest versions.
