### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by engali20235** [platformio/platformio-core-installer#3111]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.84.2
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
    at c (c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
    at b (c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5197)
    at B (c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4312)
    at c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5253
    at new Promise (<anonymous>)
    at X (c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5232)
    at pA (c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:951058)
    at xA.loadCoreState (c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:958106)
    at xA.install (c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:962052)
    at k.install (c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\dist\webpack:\platformio-ide\src\installer\manager.js:94:57)
    at c:\Users\PC\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\dist\webpack:\platformio-ide\src\main.js:216:36
  ```

**Comment by ivankravets** [comment]
Try to remove `c:\Users\PC\.platformio` folder and restart VSCode.
