### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by mhgitwg** [platformio/platformio-core-installer#3118]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.84.2
  PIO IDE: v2.5.0
  System: Linux, 6.2.0-1016-azure, x64

  %23 Exception
  ```
  Error: Error: Can not install PlatformIO Core due to a missed `distutils` package in your Python installation.
Please install this package manually using the OS package manager. For example:

$ apt-get install python3-venv

(MAY require administrator access `sudo`)
 -> Installer version: 1.1.2
Platform: Linux-6.2.0-1016-azure-x86_64-with-glibc2.35
Python version: 3.12.0 (main, Nov 20 2023, 04:09:39) [GCC 11.4.0]
Python path: /usr/local/bin/python3
Creating a virtual environment at /home/ubuntu/.platformio/penv

    at callback (/home/ubuntu/.vscode-remote/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:184:23)
    at ChildProcess.c (/home/ubuntu/.vscode-remote/extensions/platformio.platformio-ide-2.5.0/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:157:5)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:322:12)
  ```

**Comment by ivankravets** [comment]
Please update VSCode and PlatformIO IDE extension to the latest version https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide
