### ISSUE TITLE
Error: The repository located at mirrors.aliyun.com is not a trusted or secure host

### ISSUE THREAD

**Issue by Jialonger** [platformio/platformio-core-installer#3123]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.81.1
  PIO IDE: v3.3.1
  System: Linux, 6.2.0-26-generic, x64

  %23 Exception
  ```
  Error: WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
ERROR: Could not find a version that satisfies the requirement platformio (from versions: none)
ERROR: No matching distribution found for platformio
Error: Could not install PlatformIO Core: Command '['/home/xjl/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/xjl/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/

	at /home/xjl/.vscode/extensions/platformio.platformio-ide-3.3.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5300
	at ChildProcess.c (/home/xjl/.vscode/extensions/platformio.platformio-ide-3.3.1-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1121:16)
	at Socket.<anonymous> (node:internal/child_process:479:11)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at Pipe.<anonymous> (node:net:757:14)
  ```

**Comment by ivankravets** [comment]
> Error: WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. 

Yes, please avoid using espionage Python Package repositories. Remove it. Use the official https://pypi.org/
