### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by left-win** [platformio/platformio-core-installer#3125]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.85.1
  PIO IDE: v3.3.1
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an OSError: [WinError 32] ��һ����������ʹ�ô��ļ��������޷����ʡ�: 'C:\\Users\\User\\.platformio\\penv\\Scripts\\readelf.py'
Check the permissions.

Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\User\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: Windows-10
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
Python path: C:\Users\User\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\User\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Downloading platformio-6.1.11-py3-none-any.whl.metadata (6.9 kB)
Collecting bottle==0.12.* (from platformio)
  Downloading bottle-0.12.25-py3-none-any.whl (90 kB)
     -------------------------------------- 90.2/90.2 kB 340.2 kB/s eta 0:00:00
Collecting click<=8.2,>=8.0.4 (from platformio)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting colorama (from platformio)
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting marshmallow==3.* (from platformio)
  Downloading marshmallow-3.20.1-py3-none-any.whl.metadata (7.8 kB)
Collecting pyelftools==0.29 (from platformio)
  Downloading pyelftools-0.29-py2.py3-none-any.whl (174 kB)
     ------------------------------------ 174.3/174.3 kB 953.6 kB/s eta 0:00:00
Collecting pyserial==3.5.* (from platformio)
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     ---------------------------------------- 90.6/90.6 kB 2.6 MB/s eta 0:00:00
Collecting requests==2.* (from platformio)
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting semantic-version==2.10.* (from platformio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting tabulate==0.* (from platformio)
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting ajsonrpc==1.2.* (from platformio)
  Downloading ajsonrpc-1.2.0-py3-none-any.whl (22 kB)
Collecting starlette<0.32,>=0.19 (from platformio)
  Downloading starlette-0.31.1-py3-none-any.whl.metadata (5.8 kB)
Collecting uvicorn<0.24,>=0.16 (from platformio)
  Downloading uvicorn-0.23.2-py3-none-any.whl.metadata (6.2 kB)
Collecting wsproto==1.* (from platformio)
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting packaging>=17.0 (from marshmallow==3.*->platformio)
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.*->platformio)
  Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests==2.*->platformio)
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests==2.*->platformio)
  Downloading urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests==2.*->platformio)
  Downloading certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting h11<1,>=0.9.0 (from wsproto==1.*->platformio)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ---------------------------------------- 58.3/58.3 kB 1.0 MB/s eta 0:00:00
Collecting anyio<5,>=3.4.0 (from starlette<0.32,>=0.19->platformio)
  Downloading anyio-4.2.0-py3-none-any.whl.metadata (4.6 kB)
Collecting sniffio>=1.1 (from anyio<5,>=3.4.0->starlette<0.32,>=0.19->platformio)
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Downloading platformio-6.1.11-py3-none-any.whl (416 kB)
   ---------------------------------------- 416.9/416.9 kB 1.0 MB/s eta 0:00:00
Downloading marshmallow-3.20.1-py3-none-any.whl (49 kB)
   ---------------------------------------- 49.4/49.4 kB 1.2 MB/s eta 0:00:00
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ---------------------------------------- 62.6/62.6 kB 556.7 kB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ---------------------------------------- 97.9/97.9 kB 1.4 MB/s eta 0:00:00
Downloading starlette-0.31.1-py3-none-any.whl (69 kB)
   ---------------------------------------- 69.9/69.9 kB 764.7 kB/s eta 0:00:00
Downloading uvicorn-0.23.2-py3-none-any.whl (59 kB)
   ---------------------------------------- 59.5/59.5 kB 524.5 kB/s eta 0:00:00
Downloading anyio-4.2.0-py3-none-any.whl (85 kB)
   ---------------------------------------- 85.5/85.5 kB 320.2 kB/s eta 0:00:00
Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
   -------------------------------------- 162.5/162.5 kB 814.4 kB/s eta 0:00:00
Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
Downloading idna-3.6-py3-none-any.whl (61 kB)
   ---------------------------------------- 61.6/61.6 kB 827.9 kB/s eta 0:00:00
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ---------------------------------------- 53.0/53.0 kB 392.4 kB/s eta 0:00:00
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Installing collected packages: pyserial, pyelftools, bottle, urllib3, tabulate, sniffio, semantic-version, packaging, idna, h11, colorama, charset-normalizer, certifi, ajsonrpc, wsproto, requests, marshmallow, click, anyio, uvicorn, starlette, platformio

    at c:\Users\User\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5300
    at ChildProcess.c (c:\Users\User\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4598)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
  ```

**Comment by ivankravets** [comment]
Please close all VSCode windows. Restart VSCode.
