### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ncasaleiro** [platformio/platformio-core-installer#3133]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.85.1
  PIO IDE: v3.3.2
  System: Linux, 6.1.0-16-amd64, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/home/nunocasaleiro/.platformio/.cache/tmp/get-platformio-1.2.1.py", line 71, in <module>
    main()
  File "/home/nunocasaleiro/.platformio/.cache/tmp/get-platformio-1.2.1.py", line 63, in main
    bootstrap()
  File "/home/nunocasaleiro/.platformio/.cache/tmp/get-platformio-1.2.1.py", line 49, in bootstrap
    pioinstaller.__main__.main()
  File "/home/nunocasaleiro/.platformio/.cache/tmp/.piocore-installer-kvzrvh4h/tmplpscrxk8/pioinstaller.zip/pioinstaller/__main__.py", line 133, in main
  File "/home/nunocasaleiro/.platformio/.cache/tmp/.piocore-installer-kvzrvh4h/tmplpscrxk8/pioinstaller.zip/click/core.py", line 1128, in __call__
  File "/home/nunocasaleiro/.platformio/.cache/tmp/.piocore-installer-kvzrvh4h/tmplpscrxk8/pioinstaller.zip/click/core.py", line 1053, in main
  File "/home/nunocasaleiro/.platformio/.cache/tmp/.piocore-installer-kvzrvh4h/tmplpscrxk8/pioinstaller.zip/click/core.py", line 1637, in invoke
  File "/home/nunocasaleiro/.platformio/.cache/tmp/.piocore-installer-kvzrvh4h/tmplpscrxk8/pioinstaller.zip/click/core.py", line 1395, in invoke
  File "/home/nunocasaleiro/.platformio/.cache/tmp/.piocore-installer-kvzrvh4h/tmplpscrxk8/pioinstaller.zip/click/core.py", line 754, in invoke
  File "/home/nunocasaleiro/.platformio/.cache/tmp/.piocore-installer-kvzrvh4h/tmplpscrxk8/pioinstaller.zip/click/decorators.py", line 26, in new_func
  File "/home/nunocasaleiro/.platformio/.cache/tmp/.piocore-installer-kvzrvh4h/tmplpscrxk8/pioinstaller.zip/pioinstaller/__main__.py", line 56, in cli
  File "/usr/lib/python3.11/platform.py", line 1212, in platform
    system, node, release, version, machine, processor = uname()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/platform.py", line 799, in __iter__
    (self.processor,)
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/platform.py", line 794, in processor
    return _unknown_as_blank(_Processor.get())
                             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/platform.py", line 739, in get
    return func() or ''
           ^^^^^^
  File "/usr/lib/python3.11/platform.py", line 762, in from_subprocess
    return subprocess.check_output(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nunocasaleiro/.local/python-env/lib/python3.11/site-packages/run/__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nunocasaleiro/.local/python-env/lib/python3.11/site-packages/run/__init__.py", line 121, in create_process
    shlex.split(command),
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shlex.py", line 315, in split
    return list(lex)
           ^^^^^^^^^
  File "/usr/lib/python3.11/shlex.py", line 300, in __next__
    token = self.get_token()
            ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shlex.py", line 109, in get_token
    raw = self.read_token()
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'read'
 -> Installer version: 1.2.1

	at /home/nunocasaleiro/.vscode/extensions/platformio.platformio-ide-3.3.2-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:5300
	at ChildProcess.c (/home/nunocasaleiro/.vscode/extensions/platformio.platformio-ide-3.3.2-linux-x64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
	at ChildProcess.emit (node:events:513:28)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at Pipe.<anonymous> (node:net:322:12)
  ```

**Comment by ivankravets** [comment]
It seems like an internal Python issue. Have you resolved it? Maybe, broken Python installation?
