### ISSUE TITLE
Installation Manager error

### ISSUE THREAD

**Issue by SgtBlade** [platformio/platformio-core-installer#3136]
%23 Description of problem
  Error when installing during the "installing platformIO core" phase. Using MacOS. Complete reinstall of VSCode has been attempted with removing everything of it (the hidden folders and such).

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.85.1
  PIO IDE: v3.3.2
  System: Darwin, 23.1.0, x64

  %23 Exception
  ```
  Error:   error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Collecting setuptools>=40.8.0
        Obtaining dependency information for setuptools>=40.8.0 from https://files.pythonhosted.org/packages/55/3a/5121b58b578a598b269537e09a316ad2a94fdd561a2c6eb75cd68578cc6b/setuptools-69.0.3-py3-none-any.whl.metadata
        Using cached setuptools-69.0.3-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/c7/c3/55076fc728723ef927521abaa1955213d094933dc36d4a2008d5101e1af5/wheel-0.42.0-py3-none-any.whl.metadata
        Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
      Using cached setuptools-69.0.3-py3-none-any.whl (819 kB)
      Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
      Installing collected packages: wheel, setuptools
      ERROR: Cannot set --home and --prefix together
      WARNING: There was an error checking the latest version of pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.
Error: Could not install PlatformIO Core: Command '['/Users/myname/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.1
Platform: macOS-10.16
Python version: 3.11.7 (main, Jan  5 2024, 15:06:11) [Clang 10.0.0 (clang-1000.10.44.4)]
Python path: /Users/myname/.platformio/python3/bin/python3
Creating a virtual environment at /Users/myname/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Using cached platformio-6.1.13.tar.gz (237 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

    at /Users/myname/.vscode/extensions/platformio.platformio-ide-3.3.2-darwin-x64/node_modules/platformio-node-helpers/dist/index.js:1:5300
    at ChildProcess.c (/Users/myname/.vscode/extensions/platformio.platformio-ide-3.3.2-darwin-x64/node_modules/platformio-node-helpers/dist/index.js:1:4598)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:322:12)
  ```

**Comment by ivankravets** [comment]
I can't reproduce this issue on macOS. Could you remove `/Users/myname/.platformio/penv` folder and restart VSCode?
