### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by VeereshButti** [platformio/platformio-core-installer#3146]
Error: Can not find Python Interpreter. Please install Python 3.5 or above manually at t.value (C:\Users\Guest.pulsar\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:30165) at t.value (C:\Users\Guest.pulsar\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:27975) at async Promise.all (index 3) at PlatformIOIDEPackage.startInstaller (main.js:89:7) at PlatformIOIDEPackage._asyncActivateWrapper (main.js:63:11)

**Comment by VeereshButti** [comment]
Not able to get it to work despite all required packages.
