### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Jasea** [platformio/platformio-core-installer#318]
%23 Description of problem
 I am trying to do an iniial install of Platformio and tis problem happens almost immediatly when trying to install. I have tried deleting Visual Studio and restarting the install but the problem reoccures.
  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.51.1
  PIO IDE: v2.2.1
  System: Darwin, 19.6.0, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/Users/jcrawford/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "/Users/jcrawford/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "/Users/jcrawford/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/pioinstaller/__main__.py", line 122, in main
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/click/core.py", line 829, in __call__
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/click/core.py", line 782, in main
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/click/core.py", line 1236, in invoke
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/click/core.py", line 1066, in invoke
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/click/core.py", line 610, in invoke
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/click/decorators.py", line 21, in new_func
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/pioinstaller/__main__.py", line 52, in cli
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/pioinstaller/core.py", line 72, in install_platformio_core
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/pioinstaller/penv.py", line 52, in create_core_penv
  File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-a5emaglo/tmp4_t60wad/pioinstaller.zip/pioinstaller/python.py", line 170, in find_compatible_pythons
  File "/Users/jcrawford/.platformio/python3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/jcrawford/.platformio/python3/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/jcrawford/.platformio/python3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/jcrawford/.platformio/python3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/Library/Frameworks/Python.framework/Versions/2.6/bin/python'
 -> Installer version: 0.3.5
Platform: macOS-10.15.7
Python version: 3.8.4 (default, Jul 14 2020, 15:19:59) 
[Clang 10.0.0 (clang-1000.10.44.4)]
Python path: /Users/jcrawford/.platformio/python3/bin/python3
Creating a virtual environment at /Users/jcrawford/.platformio/penv

	at /Users/jcrawford/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/Users/jcrawford/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
  ```

**Comment by Jasea** [comment]
Hardware information:  Imac 2019 Fusion HD running MacOS Catalina. I can install PlatformIO on a Macbook Air running High Sierra without any problems, except the very small screen!

**Comment by Jasea** [comment]
Problem was caused by an old version of Python, 2.6, being in the path statement. Changed the path and Platformio now installs
