### ISSUE TITLE
Installation Manager: Missing dependencies for SOCKS support

### ISSUE THREAD

**Issue by undermuz** [platformio/platformio-core-installer#3180]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.88.0
  PIO IDE: v3.3.3
  System: Windows_NT, 10.0.22631, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an OSError: Missing dependencies for SOCKS support.

WARNING: There was an error checking the latest version of pip.
ERROR: Could not install packages due to an OSError: Missing dependencies for SOCKS support.

WARNING: There was an error checking the latest version of pip.
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\HYPERPC\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.2
Platform: Windows-10
Python version: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Python path: C:\Users\HYPERPC\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\HYPERPC\.platformio\penv
Updating Python package manager (PIP) in the virtual environment
Requirement already satisfied: pip in c:\users\hyperpc\.platformio\penv\lib\site-packages (23.2.1)
Virtual environment has been successfully created!
Installing PlatformIO Core

    at c:\Users\HYPERPC\.vscode\extensions\platformio.platformio-ide-3.3.3-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5323
    at ChildProcess.i (c:\Users\HYPERPC\.vscode\extensions\platformio.platformio-ide-3.3.3-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4621)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:303:5)
  ```

**Comment by eliotcougar** [comment]
It is really annoying that the updater doesn't support proxy. It has to have pysocks preinstalled before upgrading, or at least not wipe the packages every time...
