### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by AlexCat315** [platformio/platformio-core-installer#3226]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.92.2
  PIO IDE: v3.3.3
  System: Darwin, 23.4.0, arm64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an OSError: Missing dependencies for SOCKS support.

WARNING: There was an error checking the latest version of pip.
ERROR: Could not install packages due to an OSError: Missing dependencies for SOCKS support.

WARNING: There was an error checking the latest version of pip.
Error: Could not install PlatformIO Core: Command '['/Users/mishon/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.2
Platform: macOS-14.4.1
Python version: 3.11.7 (main, Mar 26 2024, 13:16:44) [Clang 15.0.0 (clang-1500.0.40.1)]
Python path: /Users/mishon/.platformio/python3/bin/python3
Creating a virtual environment at /Users/mishon/.platformio/penv
Updating Python package manager (PIP) in the virtual environment
Requirement already satisfied: pip in /Users/mishon/.platformio/penv/lib/python3.11/site-packages (23.2.1)
Virtual environment has been successfully created!
Installing PlatformIO Core

    at /Users/mishon/.vscode/extensions/platformio.platformio-ide-3.3.3-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:5323
    at ChildProcess.i (/Users/mishon/.vscode/extensions/platformio.platformio-ide-3.3.3-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:4621)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at Pipe.<anonymous> (node:net:338:12)
  ```

**Comment by Kali-** [comment]
reinstalled requirements via command line fixed the issue
