### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by MagnareschME** [platformio/platformio-core-installer#3227]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.92.2
  PIO IDE: v3.3.3
  System: Windows_NT, 10.0.19045, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\Sebastian Mantwill\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Sebastian Mantwill\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sebastian Mantwill\.platformio\penv\lib\site-packages\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
ModuleNotFoundError: No module named 'pip._internal'
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 [WinError 2] Das System kann die angegebene Datei nicht finden
 -> Installer version: 1.2.2
Platform: Windows-10
Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\Sebastian Mantwill\AppData\Local\Programs\Python\Python310\python.exe
Creating a virtual environment at C:\Users\Sebastian Mantwill\.platformio\penv
Updating Python package manager (PIP) in the virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at c:\Users\Sebastian Mantwill\.vscode\extensions\platformio.platformio-ide-3.3.3-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5323
	at ChildProcess.i (c:\Users\Sebastian Mantwill\.vscode\extensions\platformio.platformio-ide-3.3.3-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4621)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess.emit (node:domain:488:12)
	at maybeClose (node:internal/child_process:1105:16)
	at ChildProcess._handle.onexit (node:internal/child_process:305:5)
	at Process.callbackTrampoline (node:internal/async_hooks:130:17)
  ```

**Comment by DeadBoySmile** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
