### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by TinyuZhao** [platformio/platformio-core-installer#3255]
I checked the pip source and it was not replaced.

<img width="697" alt="image" src="https://github.com/user-attachments/assets/d18901e6-17f1-4418-920e-40854f9e9bc4">

https://github.com/platformio/platformio-core-installer/issues/3129
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.95.1
  PIO IDE: v3.3.3
  System: Darwin, 23.6.0, arm64

  %23 Exception
  ```
  Error:   ERROR: HTTP error 403 while getting https://mirrors.bfsu.edu.cn/pypi/web/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl (from https://mirrors.bfsu.edu.cn/pypi/web/simple/pip/) (requires-python:>=3.8)
ERROR: Could not install requirement pip from https://mirrors.bfsu.edu.cn/pypi/web/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl because of HTTP error 403 Client Error: Forbidden for url: https://mirrors.bfsu.edu.cn/pypi/web/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl for URL https://mirrors.bfsu.edu.cn/pypi/web/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl (from https://mirrors.bfsu.edu.cn/pypi/web/simple/pip/) (requires-python:>=3.8)

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: /Users/tinyu/.platformio/penv/bin/python -m pip install --upgrade pip
  ERROR: HTTP error 403 while getting https://mirrors.bfsu.edu.cn/pypi/web/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl (from https://mirrors.bfsu.edu.cn/pypi/web/simple/pip/) (requires-python:>=3.8)

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: /Users/tinyu/.platformio/penv/bin/python -m pip install --upgrade pip
ERROR: Could not install requirement pip from https://mirrors.bfsu.edu.cn/pypi/web/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl because of HTTP error 403 Client Error: Forbidden for url: https://mirrors.bfsu.edu.cn/pypi/web/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl for URL https://mirrors.bfsu.edu.cn/pypi/web/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl (from https://mirrors.bfsu.edu.cn/pypi/web/simple/pip/) (requires-python:>=3.8)
  ERROR: HTTP error 403 while getting https://mirrors.bfsu.edu.cn/pypi/web/packages/32/a0/4b1d18da2668a37b28beff3ecdc934940516302565c31a4cd4e17661a285/platformio-6.1.16.tar.gz (from https://mirrors.bfsu.edu.cn/pypi/web/simple/platformio/) (requires-python:>=3.6)
ERROR: Could not install requirement platformio from https://mirrors.bfsu.edu.cn/pypi/web/packages/32/a0/4b1d18da2668a37b28beff3ecdc934940516302565c31a4cd4e17661a285/platformio-6.1.16.tar.gz because of HTTP error 403 Client Error: Forbidden for url: https://mirrors.bfsu.edu.cn/pypi/web/packages/32/a0/4b1d18da2668a37b28beff3ecdc934940516302565c31a4cd4e17661a285/platformio-6.1.16.tar.gz for URL https://mirrors.bfsu.edu.cn/pypi/web/packages/32/a0/4b1d18da2668a37b28beff3ecdc934940516302565c31a4cd4e17661a285/platformio-6.1.16.tar.gz (from https://mirrors.bfsu.edu.cn/pypi/web/simple/platformio/) (requires-python:>=3.6)

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: /Users/tinyu/.platformio/penv/bin/python -m pip install --upgrade pip
Error: Could not install PlatformIO Core: Command '['/Users/tinyu/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.2
Platform: macOS-14.7.1
Python version: 3.11.7 (main, Mar 26 2024, 13:16:44) [Clang 15.0.0 (clang-1500.0.40.1)]
Python path: /Users/tinyu/.platformio/python3/bin/python3
Creating a virtual environment at /Users/tinyu/.platformio/penv
Updating Python package manager (PIP) in the virtual environment
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Requirement already satisfied: pip in /Users/tinyu/.platformio/penv/lib/python3.11/site-packages (23.2.1)
Collecting pip
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Collecting pip
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Collecting platformio

    at /Users/tinyu/.vscode/extensions/platformio.platformio-ide-3.3.3-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:5261
    at ChildProcess.i (/Users/tinyu/.vscode/extensions/platformio.platformio-ide-3.3.3-darwin-arm64/node_modules/platformio-node-helpers/dist/index.js:1:4559)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at Pipe.<anonymous> (node:net:339:12)
  ```

**Comment by TinyuZhao** [comment]
I checked all my pip settings and did not find that the pip source was replaced. This is very strange. I don’t know why I used the mirror source of Tsinghua University.
