### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by darikprescott** [platformio/platformio-core-installer#3269]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.95.3
  PIO IDE: v3.3.3
  System: Windows_NT, 10.0.27758, x64

  %23 Exception
  ```
  Error:   error: subprocess-exited-with-error
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 2
  
  [37 lines of output]
  Collecting setuptools>=40.8.0
    Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
  Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
  ERROR: Exception:
  Traceback (most recent call last):
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
      status = _inner_run()
               ^^^^^^^^^^^^
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
      return self.run(options, args)
             ^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
      return func(self, options, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run
      requirement_set = resolver.resolve(
                        ^^^^^^^^^^^^^^^^^
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 179, in resolve
      self.factory.preparer.prepare_linked_requirements_more(reqs)
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\operations\prepare.py", line 554, in prepare_linked_requirements_more
      self._complete_partial_requirements(
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\operations\prepare.py", line 489, in _complete_partial_requirements
      self._prepare_linked_requirement(req, parallel_builds)
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\operations\prepare.py", line 614, in _prepare_linked_requirement
      hashes.check_against_path(file_path)
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\utils\hashes.py", line 102, in check_against_path
      return self.check_against_file(file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\utils\hashes.py", line 98, in check_against_file
      return self.check_against_chunks(read_chunks(file))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\utils\hashes.py", line 80, in check_against_chunks
      for chunk in chunks:
    File "C:\Users\Presc\.platformio\penv\Lib\site-packages\pip\_internal\utils\misc.py", line 314, in read_chunks
      chunk = file.read(size)
              ^^^^^^^^^^^^^^^
  MemoryError
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 2

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\Presc\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.2
Platform: Windows-10
Python version: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Python path: C:\Users\Presc\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\Presc\.platformio\penv
Updating Python package manager (PIP) in the virtual environment
Requirement already satisfied: pip in c:\users\presc\.platformio\penv\lib\site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl.metadata
  Downloading pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 1.8/1.8 MB 12.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-24.3.1
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Downloading platformio-6.1.16.tar.gz (239 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

    at c:\Users\Presc\.vscode\extensions\platformio.platformio-ide-3.3.3-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5261
    at ChildProcess.i (c:\Users\Presc\.vscode\extensions\platformio.platformio-ide-3.3.3-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4559)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
  ```

**Comment by darikprescott** [comment]
I'm sorry i have been attacked and a lot has happened
but  I'm here and I am fully committed and i hope we can bring users a great experience i just had to take in consideration my personal saftey and in the works to remove as much of my information as i can.
