### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ianzone** [platformio/platformio-core-installer#3276]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.96.0
  PIO IDE: v3.3.3
  System: Windows_NT, 10.0.26100, x64

  %23 Exception
  ```
  Error: WARNING: There was an error checking the latest version of pip.
  WARNING: Building wheel for platformio failed: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'd:\\.platformio\\.cache\\"d:'
WARNING: There was an error checking the latest version of pip.
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (platformio)
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['D:\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 1.2.2
Platform: Windows-10
Python version: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Python path: D:\.platformio\python3\python.exe
Creating a virtual environment at D:\.platformio\penv
Updating Python package manager (PIP) in the virtual environment
Requirement already satisfied: pip in d:\.platformio\penv\lib\site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl.metadata
  Downloading pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 1.8/1.8 MB 1.1 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-24.3.1
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Downloading platformio-6.1.16.tar.gz (239 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting bottle==0.13.* (from platformio)
  Downloading bottle-0.13.2-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting click<9,>=8.0.4 (from platformio)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting colorama (from platformio)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting marshmallow==3.* (from platformio)
  Downloading marshmallow-3.23.1-py3-none-any.whl.metadata (7.5 kB)
Collecting pyelftools<1,>=0.27 (from platformio)
  Downloading pyelftools-0.31-py3-none-any.whl.metadata (381 bytes)
Collecting pyserial==3.5.* (from platformio)
  Downloading pyserial-3.5-py2.py3-none-any.whl.metadata (1.6 kB)
Collecting requests==2.* (from platformio)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting semantic_version==2.10.* (from platformio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting tabulate==0.* (from platformio)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting ajsonrpc==1.2.* (from platformio)
  Downloading ajsonrpc-1.2.0-py3-none-any.whl.metadata (6.9 kB)
Collecting starlette<0.40,>=0.19 (from platformio)
  Downloading starlette-0.39.2-py3-none-any.whl.metadata (6.0 kB)
Collecting uvicorn<0.31,>=0.16 (from platformio)
  Downloading uvicorn-0.30.6-py3-none-any.whl.metadata (6.6 kB)
Collecting wsproto==1.* (from platformio)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Collecting packaging>=17.0 (from marshmallow==3.*->platformio)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.*->platformio)
  Downloading charset_normalizer-3.4.0-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests==2.*->platformio)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests==2.*->platformio)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests==2.*->platformio)
  Downloading certifi-2024.12.14-py3-none-any.whl.metadata (2.3 kB)
Collecting h11<1,>=0.9.0 (from wsproto==1.*->platformio)
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting anyio<5,>=3.4.0 (from starlette<0.40,>=0.19->platformio)
  Downloading anyio-4.7.0-py3-none-any.whl.metadata (4.7 kB)
Collecting sniffio>=1.1 (from anyio<5,>=3.4.0->starlette<0.40,>=0.19->platformio)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting typing_extensions>=4.5 (from anyio<5,>=3.4.0->starlette<0.40,>=0.19->platformio)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Downloading ajsonrpc-1.2.0-py3-none-any.whl (22 kB)
Downloading bottle-0.13.2-py2.py3-none-any.whl (104 kB)
Downloading marshmallow-3.23.1-py3-none-any.whl (49 kB)
Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
Downloading pyelftools-0.31-py3-none-any.whl (180 kB)
Downloading starlette-0.39.2-py3-none-any.whl (73 kB)
Downloading uvicorn-0.30.6-py3-none-any.whl (62 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading anyio-4.7.0-py3-none-any.whl (93 kB)
Downloading certifi-2024.12.14-py3-none-any.whl (164 kB)
Downloading charset_normalizer-3.4.0-cp311-cp311-win_amd64.whl (101 kB)
Downloading h11-0.14.0-py3-none-any.whl (58 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading packaging-24.2-py3-none-any.whl (65 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Building wheels for collected packages: platformio
Failed to build platformio

    at c:\Users\yihen\.vscode\extensions\platformio.platformio-ide-3.3.3-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:5261
    at ChildProcess.i (c:\Users\yihen\.vscode\extensions\platformio.platformio-ide-3.3.3-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:4559)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1104:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
  ```

**Comment by ianzone** [comment]
```powershell
Building wheels for collected packages: platformio
  WARNING: Building wheel for platformio failed: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'd:\\.platformio\\penv\\scripts\\"d:'
Failed to build platformio
WARNING: There was an error checking the latest version of pip.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in _run_module_as_main:198                                                                       │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x0000025230D85730, file                             │ │
│ │                "D:\.platformio\penv\Scripts\pip.exe\__main__.py", line 1>                    │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "D:\.platformio\penv\Scripts\pip.exe\">,                                      │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "D:\.platformio\penv\Scripts\pip.exe\">,                                      │ │
│ │                origin='D:\\.platformio\\penv\\Scripts\\pip.exe\\__main__.py'),               │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__': 'D:\\.platformio\\penv\\Scripts\\pip.exe\\__main__.py',       │ │
│ │                │   '__cached__':                                                             │ │
│ │                'D:\\.platformio\\penv\\Scripts\\pip.exe\\__pycache__\\__main__.cpython-311.… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'D:\\.platformio\\python3\\Lib\\re\\__init__.py'>,                            │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "D:\.platformio\penv\Scripts\pip.exe\">,                                      │ │
│ │                origin='D:\\.platformio\\penv\\Scripts\\pip.exe\\__main__.py')                │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ in _run_code:88                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       cached = 'D:\\.platformio\\penv\\Scripts\\pip.exe\\__pycache__\\__main__.cpython-311.… │ │
│ │         code = <code object <module> at 0x0000025230D85730, file                             │ │
│ │                "D:\.platformio\penv\Scripts\pip.exe\__main__.py", line 1>                    │ │
│ │        fname = 'D:\\.platformio\\penv\\Scripts\\pip.exe\\__main__.py'                        │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object "D:\.platformio\penv\Scripts\pip.exe\">                   │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "D:\.platformio\penv\Scripts\pip.exe\">,                                      │ │
│ │                origin='D:\\.platformio\\penv\\Scripts\\pip.exe\\__main__.py')                │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "D:\.platformio\penv\Scripts\pip.exe\">,                                      │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "D:\.platformio\penv\Scripts\pip.exe\">,                                      │ │
│ │                origin='D:\\.platformio\\penv\\Scripts\\pip.exe\\__main__.py'),               │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__': 'D:\\.platformio\\penv\\Scripts\\pip.exe\\__main__.py',       │ │
│ │                │   '__cached__':                                                             │ │
│ │                'D:\\.platformio\\penv\\Scripts\\pip.exe\\__pycache__\\__main__.cpython-311.… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'D:\\.platformio\\python3\\Lib\\re\\__init__.py'>,                            │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ D:\.platformio\penv\Lib\site-packages\pip\_internal\cli\main.py:80 in main                       │
│                                                                                                  │
│   77 │   │   logger.debug("Ignoring error %s when setting locale", e)                            │
│   78 │   command = create_command(cmd_name, isolated=("--isolated" in cmd_args))                 │
│   79 │                                                                                           │
│ ❱ 80 │   return command.main(cmd_args)                                                           │
│   81                                                                                             │
│                                                                                                  │
│ ╭──────────────────────────────────────── locals ─────────────────────────────────────────╮      │
│ │     args = ['install', '-U', 'platformio', '--debug']                                   │      │
│ │ cmd_args = ['-U', 'platformio', '--debug']                                              │      │
│ │ cmd_name = 'install'                                                                    │      │
│ │  command = <pip._internal.commands.install.InstallCommand object at 0x0000025233E124D0> │      │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────╯      │
│                                                                                                  │
│ D:\.platformio\penv\Lib\site-packages\pip\_internal\cli\base_command.py:157 in main              │
│                                                                                                  │
│   154 │   def main(self, args: List[str]) -> int:                                                │
│   155 │   │   try:                                                                               │
│   156 │   │   │   with self.main_context():                                                      │
│ ❱ 157 │   │   │   │   return self._main(args)                                                    │
│   158 │   │   finally:                                                                           │
│   159 │   │   │   logging.shutdown()                                                             │
│   160                                                                                            │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ───────────────────────────────────────╮          │
│ │ args = ['-U', 'platformio', '--debug']                                              │          │
│ │ self = <pip._internal.commands.install.InstallCommand object at 0x0000025233E124D0> │          │
│ ╰─────────────────────────────────────────────────────────────────────────────────────╯          │
│                                                                                                  │
│ D:\.platformio\penv\Lib\site-packages\pip\_internal\cli\base_command.py:231 in _main             │
│                                                                                                  │
│   228 │   │   │   │   )                                                                          │
│   229 │   │   │   │   options.cache_dir = None                                                   │
│   230 │   │                                                                                      │
│ ❱ 231 │   │   return self._run_wrapper(level_number, options, args)                              │
│   232                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ always_enabled_features = set()                                                              │ │
│ │                    args = ['platformio']                                                     │ │
│ │            level_number = 20                                                                 │ │
│ │                 options = <Values at 0x25234a3b390: {'help': None, 'debug_mode': True,       │ │
│ │                           'isolated_mode': False, 'require_venv': False, 'python': None,     │ │
│ │                           'verbose': 0, 'version': None, 'quiet': 0, 'log': None,            │ │
│ │                           'no_input': False, 'keyring_provider': 'auto', 'proxy': '',        │ │
│ │                           'retries': 5, 'timeout': 15, 'exists_action': [], 'trusted_hosts': │ │
│ │                           [], 'cert': None, 'client_cert': None, 'cache_dir':                │ │
│ │                           'd:\\.platformio\\penv\\scripts\\"d:\\.pip\\cache"',               │ │
│ │                           'disable_pip_version_check': False, 'no_color': False,             │ │
│ │                           'no_python_version_warning': False, 'features_enabled': [],        │ │
│ │                           'deprecated_features_enabled': [], 'requirements': [],             │ │
│ │                           'constraints': [], 'ignore_dependencies': False, 'pre': False,     │ │
│ │                           'editables': [], 'dry_run': False, 'target_dir': None,             │ │
│ │                           'platforms': None, 'python_version': None, 'implementation': None, │ │
│ │                           'abis': None, 'use_user_site': False, 'root_path': None,           │ │
│ │                           'prefix_path': None, 'src_dir': 'D:\\.platformio\\penv\\src',      │ │
│ │                           'upgrade': True, 'upgrade_strategy': 'only-if-needed',             │ │
│ │                           'force_reinstall': None, 'ignore_installed': None,                 │ │
│ │                           'ignore_requires_python': None, 'build_isolation': True,           │ │
│ │                           'use_pep517': None, 'check_build_deps': False,                     │ │
│ │                           'override_externally_managed': None, 'config_settings': None,      │ │
│ │                           'global_options': None, 'compile': True, 'warn_script_location':   │ │
│ │                           True, 'warn_about_conflicts': True, 'format_control':              │ │
│ │                           FormatControl(set(), set()), 'prefer_binary': False,               │ │
│ │                           'require_hashes': False, 'progress_bar': 'on', 'root_user_action': │ │
│ │                           'warn', 'index_url': 'https://pypi.org/simple',                    │ │
│ │                           'extra_index_urls': [], 'no_index': False, 'find_links': [],       │ │
│ │                           'json_report_file': None, 'no_clean': False}>                      │ │
│ │                    self = <pip._internal.commands.install.InstallCommand object at           │ │
│ │                           0x0000025233E124D0>                                                │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ D:\.platformio\penv\Lib\site-packages\pip\_internal\cli\base_command.py:102 in _run_wrapper      │
│                                                                                                  │
│    99 │   │                                                                                      │
│   100 │   │   if options.debug_mode:                                                             │
│   101 │   │   │   rich_traceback.install(show_locals=True)                                       │
│ ❱ 102 │   │   │   return _inner_run()                                                            │
│   103 │   │                                                                                      │
│   104 │   │   try:                                                                               │
│   105 │   │   │   status = _inner_run()                                                          │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   _inner_run = <function Command._run_wrapper.<locals>._inner_run at 0x000002523480D800>     │ │
│ │         args = ['platformio']                                                                │ │
│ │ level_number = 20                                                                            │ │
│ │      options = <Values at 0x25234a3b390: {'help': None, 'debug_mode': True, 'isolated_mode': │ │
│ │                False, 'require_venv': False, 'python': None, 'verbose': 0, 'version': None,  │ │
│ │                'quiet': 0, 'log': None, 'no_input': False, 'keyring_provider': 'auto',       │ │
│ │                'proxy': '', 'retries': 5, 'timeout': 15, 'exists_action': [],                │ │
│ │                'trusted_hosts': [], 'cert': None, 'client_cert': None, 'cache_dir':          │ │
│ │                'd:\\.platformio\\penv\\scripts\\"d:\\.pip\\cache"',                          │ │
│ │                'disable_pip_version_check': False, 'no_color': False,                        │ │
│ │                'no_python_version_warning': False, 'features_enabled': [],                   │ │
│ │                'deprecated_features_enabled': [], 'requirements': [], 'constraints': [],     │ │
│ │                'ignore_dependencies': False, 'pre': False, 'editables': [], 'dry_run':       │ │
│ │                False, 'target_dir': None, 'platforms': None, 'python_version': None,         │ │
│ │                'implementation': None, 'abis': None, 'use_user_site': False, 'root_path':    │ │
│ │                None, 'prefix_path': None, 'src_dir': 'D:\\.platformio\\penv\\src',           │ │
│ │                'upgrade': True, 'upgrade_strategy': 'only-if-needed', 'force_reinstall':     │ │
│ │                None, 'ignore_installed': None, 'ignore_requires_python': None,               │ │
│ │                'build_isolation': True, 'use_pep517': None, 'check_build_deps': False,       │ │
│ │                'override_externally_managed': None, 'config_settings': None,                 │ │
│ │                'global_options': None, 'compile': True, 'warn_script_location': True,        │ │
│ │                'warn_about_conflicts': True, 'format_control': FormatControl(set(), set()),  │ │
│ │                'prefer_binary': False, 'require_hashes': False, 'progress_bar': 'on',        │ │
│ │                'root_user_action': 'warn', 'index_url': 'https://pypi.org/simple',           │ │
│ │                'extra_index_urls': [], 'no_index': False, 'find_links': [],                  │ │
│ │                'json_report_file': None, 'no_clean': False}>                                 │ │
│ │         self = <pip._internal.commands.install.InstallCommand object at 0x0000025233E124D0>  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ D:\.platformio\penv\Lib\site-packages\pip\_internal\cli\base_command.py:96 in _inner_run         │
│                                                                                                  │
│    93 │   def _run_wrapper(self, level_number: int, options: Values, args: List[str]) -> int:    │
│    94 │   │   def _inner_run() -> int:                                                           │
│    95 │   │   │   try:                                                                           │
│ ❱  96 │   │   │   │   return self.run(options, args)                                             │
│    97 │   │   │   finally:                                                                       │
│    98 │   │   │   │   self.handle_pip_version_check(options)                                     │
│    99                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    args = ['platformio']                                                                     │ │
│ │ options = <Values at 0x25234a3b390: {'help': None, 'debug_mode': True, 'isolated_mode':      │ │
│ │           False, 'require_venv': False, 'python': None, 'verbose': 0, 'version': None,       │ │
│ │           'quiet': 0, 'log': None, 'no_input': False, 'keyring_provider': 'auto', 'proxy':   │ │
│ │           '', 'retries': 5, 'timeout': 15, 'exists_action': [], 'trusted_hosts': [], 'cert': │ │
│ │           None, 'client_cert': None, 'cache_dir':                                            │ │
│ │           'd:\\.platformio\\penv\\scripts\\"d:\\.pip\\cache"', 'disable_pip_version_check':  │ │
│ │           False, 'no_color': False, 'no_python_version_warning': False, 'features_enabled':  │ │
│ │           [], 'deprecated_features_enabled': [], 'requirements': [], 'constraints': [],      │ │
│ │           'ignore_dependencies': False, 'pre': False, 'editables': [], 'dry_run': False,     │ │
│ │           'target_dir': None, 'platforms': None, 'python_version': None, 'implementation':   │ │
│ │           None, 'abis': None, 'use_user_site': False, 'root_path': None, 'prefix_path':      │ │
│ │           None, 'src_dir': 'D:\\.platformio\\penv\\src', 'upgrade': True,                    │ │
│ │           'upgrade_strategy': 'only-if-needed', 'force_reinstall': None, 'ignore_installed': │ │
│ │           None, 'ignore_requires_python': None, 'build_isolation': True, 'use_pep517': None, │ │
│ │           'check_build_deps': False, 'override_externally_managed': None, 'config_settings': │ │
│ │           None, 'global_options': None, 'compile': True, 'warn_script_location': True,       │ │
│ │           'warn_about_conflicts': True, 'format_control': FormatControl(set(), set()),       │ │
│ │           'prefer_binary': False, 'require_hashes': False, 'progress_bar': 'on',             │ │
│ │           'root_user_action': 'warn', 'index_url': 'https://pypi.org/simple',                │ │
│ │           'extra_index_urls': [], 'no_index': False, 'find_links': [], 'json_report_file':   │ │
│ │           None, 'no_clean': False}>                                                          │ │
│ │    self = <pip._internal.commands.install.InstallCommand object at 0x0000025233E124D0>       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ D:\.platformio\penv\Lib\site-packages\pip\_internal\cli\req_command.py:67 in wrapper             │
│                                                                                                  │
│    64 │   │   │   configure_tempdir_registry(self.tempdir_registry)                              │
│    65 │   │                                                                                      │
│    66 │   │   try:                                                                               │
│ ❱  67 │   │   │   return func(self, options, args)                                               │
│    68 │   │   except PreviousBuildDirError:                                                      │
│    69 │   │   │   # This kind of conflict can occur when the user passes an explicit             │
│    70 │   │   │   # build directory with a pre-existing folder. In that case we do               │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                       args = ['platformio']                                                  │ │
│ │ configure_tempdir_registry = <function with_cleanup.<locals>.configure_tempdir_registry at   │ │
│ │                              0x0000025234A225C0>                                             │ │
│ │                       func = <function InstallCommand.run at 0x0000025234A22520>             │ │
│ │                    options = <Values at 0x25234a3b390: {'help': None, 'debug_mode': True,    │ │
│ │                              'isolated_mode': False, 'require_venv': False, 'python': None,  │ │
│ │                              'verbose': 0, 'version': None, 'quiet': 0, 'log': None,         │ │
│ │                              'no_input': False, 'keyring_provider': 'auto', 'proxy': '',     │ │
│ │                              'retries': 5, 'timeout': 15, 'exists_action': [],               │ │
│ │                              'trusted_hosts': [], 'cert': None, 'client_cert': None,         │ │
│ │                              'cache_dir':                                                    │ │
│ │                              'd:\\.platformio\\penv\\scripts\\"d:\\.pip\\cache"',            │ │
│ │                              'disable_pip_version_check': False, 'no_color': False,          │ │
│ │                              'no_python_version_warning': False, 'features_enabled': [],     │ │
│ │                              'deprecated_features_enabled': [], 'requirements': [],          │ │
│ │                              'constraints': [], 'ignore_dependencies': False, 'pre': False,  │ │
│ │                              'editables': [], 'dry_run': False, 'target_dir': None,          │ │
│ │                              'platforms': None, 'python_version': None, 'implementation':    │ │
│ │                              None, 'abis': None, 'use_user_site': False, 'root_path': None,  │ │
│ │                              'prefix_path': None, 'src_dir': 'D:\\.platformio\\penv\\src',   │ │
│ │                              'upgrade': True, 'upgrade_strategy': 'only-if-needed',          │ │
│ │                              'force_reinstall': None, 'ignore_installed': None,              │ │
│ │                              'ignore_requires_python': None, 'build_isolation': True,        │ │
│ │                              'use_pep517': None, 'check_build_deps': False,                  │ │
│ │                              'override_externally_managed': None, 'config_settings': None,   │ │
│ │                              'global_options': None, 'compile': True,                        │ │
│ │                              'warn_script_location': True, 'warn_about_conflicts': True,     │ │
│ │                              'format_control': FormatControl(set(), set()), 'prefer_binary': │ │
│ │                              False, 'require_hashes': False, 'progress_bar': 'on',           │ │
│ │                              'root_user_action': 'warn', 'index_url':                        │ │
│ │                              'https://pypi.org/simple', 'extra_index_urls': [], 'no_index':  │ │
│ │                              False, 'find_links': [], 'json_report_file': None, 'no_clean':  │ │
│ │                              False}>                                                         │ │
│ │                       self = <pip._internal.commands.install.InstallCommand object at        │ │
│ │                              0x0000025233E124D0>                                             │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ D:\.platformio\penv\Lib\site-packages\pip\_internal\commands\install.py:434 in run               │
│                                                                                                  │
│   431 │   │   │   )                                                                              │
│   432 │   │   │                                                                                  │
│   433 │   │   │   if build_failures:                                                             │
│ ❱ 434 │   │   │   │   raise InstallationError(                                                   │
│   435 │   │   │   │   │   "ERROR: Failed to build installable wheels for some "                  │
│   436 │   │   │   │   │   "pyproject.toml based projects ({})".format(                           │
│   437 │   │   │   │   │   │   ", ".join(r.name for r in build_failures)  # type: ignore          │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                                   _ = []                                                     │ │
│ │                                args = ['platformio']                                         │ │
│ │                      build_failures = [                                                      │ │
│ │                                       │   <InstallRequirement object: platformio from        │ │
│ │                                       https://files.pythonhosted.org/packages/32/a0/4b1d18d… │ │
│ │                                       editable=False>                                        │ │
│ │                                       ]                                                      │ │
│ │                       build_tracker = <pip._internal.operations.build.build_tracker.BuildTr… │ │
│ │                                       object at 0x0000025234A59010>                          │ │
│ │                           directory = <repr-error 'Attempted to access deleted path:         │ │
│ │                                       C:\\Users\\yihen\\AppData\\Local\\Temp\\pip-install-r… │ │
│ │                              finder = <pip._internal.index.package_finder.PackageFinder      │ │
│ │                                       object at 0x0000025234A78910>                          │ │
│ │                      global_options = []                                                     │ │
│ │ installing_into_current_environment = True                                                   │ │
│ │                       modifying_pip = False                                                  │ │
│ │                             options = <Values at 0x25234a3b390: {'help': None, 'debug_mode': │ │
│ │                                       True, 'isolated_mode': False, 'require_venv': False,   │ │
│ │                                       'python': None, 'verbose': 0, 'version': None,         │ │
│ │                                       'quiet': 0, 'log': None, 'no_input': False,            │ │
│ │                                       'keyring_provider': 'auto', 'proxy': '', 'retries': 5, │ │
│ │                                       'timeout': 15, 'exists_action': [], 'trusted_hosts':   │ │
│ │                                       [], 'cert': None, 'client_cert': None, 'cache_dir':    │ │
│ │                                       'd:\\.platformio\\penv\\scripts\\"d:\\.pip\\cache"',   │ │
│ │                                       'disable_pip_version_check': False, 'no_color': False, │ │
│ │                                       'no_python_version_warning': False,                    │ │
│ │                                       'features_enabled': [], 'deprecated_features_enabled': │ │
│ │                                       [], 'requirements': [], 'constraints': [],             │ │
│ │                                       'ignore_dependencies': False, 'pre': False,            │ │
│ │                                       'editables': [], 'dry_run': False, 'target_dir': None, │ │
│ │                                       'platforms': None, 'python_version': None,             │ │
│ │                                       'implementation': None, 'abis': None, 'use_user_site': │ │
│ │                                       False, 'root_path': None, 'prefix_path': None,         │ │
│ │                                       'src_dir': 'D:\\.platformio\\penv\\src', 'upgrade':    │ │
│ │                                       True, 'upgrade_strategy': 'only-if-needed',            │ │
│ │                                       'force_reinstall': None, 'ignore_installed': None,     │ │
│ │                                       'ignore_requires_python': None, 'build_isolation':     │ │
│ │                                       True, 'use_pep517': None, 'check_build_deps': False,   │ │
│ │                                       'override_externally_managed': None,                   │ │
│ │                                       'config_settings': None, 'global_options': None,       │ │
│ │                                       'compile': True, 'warn_script_location': True,         │ │
│ │                                       'warn_about_conflicts': True, 'format_control':        │ │
│ │                                       FormatControl(set(), set()), 'prefer_binary': False,   │ │
│ │                                       'require_hashes': False, 'progress_bar': 'on',         │ │
│ │                                       'root_user_action': 'warn', 'index_url':               │ │
│ │                                       'https://pypi.org/simple', 'extra_index_urls': [],     │ │
│ │                                       'no_index': False, 'find_links': [],                   │ │
│ │                                       'json_report_file': None, 'no_clean': False}>          │ │
│ │                            preparer = <pip._internal.operations.prepare.RequirementPreparer  │ │
│ │                                       object at 0x0000025234B198D0>                          │ │
│ │                                 req = <InstallRequirement object: platformio editable=False> │ │
│ │                                reqs = [                                                      │ │
│ │                                       │   <InstallRequirement object: platformio             │ │
│ │                                       editable=False>                                        │ │
│ │                                       ]                                                      │ │
│ │                       reqs_to_build = [                                                      │ │
│ │                                       │   <InstallRequirement object: platformio from        │ │
│ │                                       https://files.pythonhosted.org/packages/32/a0/4b1d18d… │ │
│ │                                       editable=False>                                        │ │
│ │                                       ]                                                      │ │
│ │                     requirement_set = <RequirementSet object; 23 requirement(s):             │ │
│ │                                       ajsonrpc==1.2.*, anyio<5,>=3.4.0, bottle==0.13.*,      │ │
│ │                                       certifi>=2017.4.17, charset-normalizer<4,>=2,          │ │
│ │                                       click<9,>=8.0.4, colorama, h11<1,>=0.9.0,              │ │
│ │                                       idna<4,>=2.5, marshmallow==3.*, packaging>=17.0,       │ │
│ │                                       platformio, pyelftools<1,>=0.27, pyserial==3.5.*,      │ │
│ │                                       requests==2.*, semantic_version==2.10.*, sniffio>=1.1, │ │
│ │                                       starlette<0.40,>=0.19, tabulate==0.*,                  │ │
│ │                                       typing_extensions>=4.5, urllib3<3,>=1.21.1,            │ │
│ │                                       uvicorn<0.31,>=0.16, wsproto==1.*>                     │ │
│ │                            resolver = <pip._internal.resolution.resolvelib.resolver.Resolver │ │
│ │                                       object at 0x0000025234B19B50>                          │ │
│ │                                self = <pip._internal.commands.install.InstallCommand object  │ │
│ │                                       at 0x0000025233E124D0>                                 │ │
│ │                             session = <pip._internal.network.session.PipSession object at    │ │
│ │                                       0x0000025234A4B790>                                    │ │
│ │                       target_python = <pip._internal.models.target_python.TargetPython       │ │
│ │                                       object at 0x0000025234AE5600>                          │ │
│ │                     target_temp_dir = None                                                   │ │
│ │                target_temp_dir_path = None                                                   │ │
│ │                    upgrade_strategy = 'only-if-needed'                                       │ │
│ │                         wheel_cache = <pip._internal.cache.WheelCache object at              │ │
│ │                                       0x0000025234B18D10>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
InstallationError: ERROR: Failed to build installable wheels for some pyproject.toml based projects (platformio)
```

**Comment by ianzone** [comment]
When I deleted ~/pip/pip.ini, it works.

the setting is
```
[global]
cache-dir = "D:\\.pip\\cache"
```
