### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by mf-1** [platformio/platformio-core-installer#328]
Maybe this is relevant?

Using Ubuntu 20.04.1 LTS ... Last update pushed Atom to 1.53.0 ... maybe the reason?

```
Error: /home/markus/.platformio/penv/bin/python: No module named pip.main; 'pip' is a package and cannot be directly executed Error: Could not install PlatformIO Core: Command '['/home/markus/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1 -> Installer version: 0.3.4 Platform: Linux-5.4.0-54-generic-x86_64-with-glibc2.29 Python version: 2.7.17 (default, Nov 7 2019, 10:07:09) [GCC 9.2.1 20191008] Python path: /home/markus/bin/python Creating a virtual environment at /home/markus/.platformio/penv Updating Python package manager (PIP) in a virtual environment Virtual environment has been successfully created! Installing PlatformIO Core

at /home/markus/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5004
at ChildProcess.c (/home/markus/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4900)
at ChildProcess.emit (events.js:200:13)
at maybeClose (internal/child_process.js:1021:16)
at Socket.<anonymous> (internal/child_process.js:430:11)
at Socket.emit (events.js:200:13)
at Pipe.<anonymous> (net.js:586:12)
```

**Comment by mf-1** [comment]
Have updated internal plugins ... after some Atom restarts PIO was also upgrading ... now it works ...
