### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Wummeke** [platformio/platformio-core-installer#329]
%23 Description of problem
  Platform IO won't start. it is stuck at updating/installing. Worked fine before.
After the issue occured for the first time, I removed PlatformIO from VSCode, Restarted VSCode, and tried to add PlatformIO again, without success.

  %23 Configuration

  VSCode: 1.51.1
  PIO IDE: v2.2.1
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  Error: ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Wummeke\.platformio\penv\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
    status = self.run(options, args)
  File "C:\Users\Wummeke\.platformio\penv\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "C:\Users\Wummeke\.platformio\penv\lib\site-packages\pip\_internal\commands\install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "C:\Users\Wummeke\.platformio\penv\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "C:\Users\Wummeke\.platformio\penv\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 391, in _resolve_one
    dist = abstract_dist.get_pkg_resources_distribution()
  File "C:\Users\Wummeke\.platformio\penv\lib\site-packages\pip\_internal\distributions\wheel.py", line 29, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "C:\Users\Wummeke\.platformio\python3\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "C:\Users\Wummeke\.platformio\python3\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\Wummeke\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 2.
 -> Installer version: 0.3.5
Platform: Windows-10
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Python path: C:\Users\Wummeke\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\Wummeke\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Processing c:\users\wummeke\appdata\local\pip\cache\wheels\f3\f2\de\ce14a5bdca580cdf556c88054ef8fe428c06963f3fe4f91d3c\platformio-5.0.3-py3-none-any.whl

	at c:\Users\Wummeke\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\index.js:1:879275
	at ChildProcess.c (c:\Users\Wummeke\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.cp.emit (c:\Users\Wummeke\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by Wummeke** [comment]
I tried this fix: https://github.com/platformio/platformio-core-installer/issues/221 and also running VSCode as Administrator, but both didn't help.

**Comment by Wummeke** [comment]
I think I got it fixed, but I still don't understand why it got broken.

I cleared this folder: C:\Users\Wummeke\AppData\Local\pip\cache
I updated pip:

```
PS C:\Users\Wummeke> cd .\.platformio\python3\
PS C:\Users\Wummeke\.platformio\python3> .\python.exe -m pip install -U pip
```
And then restarted VSCode. That solved it for me. Hopefully someone else has a better understanding of how the installer works and can tell what went wrong.

**Comment by Wummeke** [comment]
Ehrm... Thanks for your outstanding support.
