### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by JakobHuesken** [platformio/platformio-core-installer#333]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.50.1
  PIO IDE: v2.2.1
  System: Linux, 4.15.0-54-generic, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/delli2/.platformio/penv/lib/python2.7/site-packages/pip/__main__.py", line 23, in <module>
    from pip._internal.cli.main import main as _main  %23 isort:skip %23 noqa
  File "/home/delli2/.platformio/penv/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/delli2/.platformio/penv/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/delli2/.platformio/penv/lib/python2.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/delli2/.platformio/penv/lib/python2.7/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/home/delli2/.platformio/penv/lib/python2.7/site-packages/pip/_internal/cli/progress_bars.py", line 8, in <module>
    from pip._vendor.progress.bar import Bar, FillingCirclesBar, IncrementalBar
ImportError: No module named progress.bar
Error: Could not install PlatformIO Core: Command '['/home/delli2/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1
 -> Installer version: 0.3.5
Platform: Linux-4.15.0-54-generic-x86_64-with-glibc2.9
Python version: 3.5.2 (default, Oct  7 2020, 17:19:02) 
[GCC 5.4.0 20160609]
Python path: /usr/bin/python3
Creating a virtual environment at /home/delli2/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at /home/delli2/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/home/delli2/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by JakobHuesken** [comment]
saw dublicate
