### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Jasea** [platformio/platformio-core-installer#343]
Error: Traceback (most recent call last): File "/Users/jcrawford/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 69, in main() File "/Users/jcrawford/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 61, in main bootstrap() File "/Users/jcrawford/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 47, in bootstrap pioinstaller.main.main() File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/pioinstaller/main.py", line 122, in main File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/click/core.py", line 829, in call File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/click/core.py", line 782, in main File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/click/core.py", line 1236, in invoke File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/click/core.py", line 1066, in invoke File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/click/core.py", line 610, in invoke File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/click/decorators.py", line 21, in new_func File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/pioinstaller/main.py", line 52, in cli File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/pioinstaller/core.py", line 72, in install_platformio_core File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/pioinstaller/penv.py", line 52, in create_core_penv File "/Users/jcrawford/.platformio/.cache/tmp/.piocore-installer-6mh3cny6/tmpwxg6ohjb/pioinstaller.zip/pioinstaller/python.py", line 170, in find_compatible_pythons File "/Users/jcrawford/.platformio/python3/lib/python3.8/subprocess.py", line 411, in check_output return run(popenargs, stdout=PIPE, timeout=timeout, check=True, File "/Users/jcrawford/.platformio/python3/lib/python3.8/subprocess.py", line 489, in run with Popen(popenargs, **kwargs) as process: File "/Users/jcrawford/.platformio/python3/lib/python3.8/subprocess.py", line 854, in init self._execute_child(args, executable, preexec_fn, close_fds, File "/Users/jcrawford/.platformio/python3/lib/python3.8/subprocess.py", line 1702, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) OSError: [Errno 86] Bad CPU type in executable: '/Library/Frameworks/Python.framework/Versions/2.6/bin/python' -> Installer version: 0.3.5 Platform: macOS-10.15.7 Python version: 3.8.4 (default, Jul 14 2020, 15:19:59) [Clang 10.0.0 (clang-1000.10.44.4)] Python path: /Users/jcrawford/.platformio/python3/bin/python3 Creating a virtual environment at /Users/jcrawford/.platformio/penv

at /Users/jcrawford/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5004
at ChildProcess.s (/Users/jcrawford/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4900)
at ChildProcess.emit (events.js:200:13)
at maybeClose (internal/child_process.js:1021:16)
at Socket.<anonymous> (internal/child_process.js:430:11)
at Socket.emit (events.js:200:13)
at Pipe.<anonymous> (net.js:586:12)

I am stilltrying to install PlatformIO on a Mac, having failed to install with Visual Studio I have just tried using Atom but still no success. Anyone have any ideas?

**Comment by Jasea** [comment]
The problem was caused by having an old level of Python, 2.6, in the path statemnet. Changing the path statement fixed the problem
