### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Lemmah** [platformio/platformio-core-installer#351]
%23 Description of problem
I have installed PlatformIO from the VS Code extensions explorer. I am getting this error.

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.51.1
  PIO IDE: v2.2.1
  System: Darwin, 20.1.0, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/Users/scholar/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "/Users/scholar/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "/Users/scholar/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/pioinstaller/__main__.py", line 122, in main
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/click/core.py", line 829, in __call__
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/click/core.py", line 782, in main
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/click/core.py", line 1236, in invoke
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/click/core.py", line 1066, in invoke
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/click/core.py", line 610, in invoke
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/click/decorators.py", line 21, in new_func
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/pioinstaller/__main__.py", line 52, in cli
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/pioinstaller/core.py", line 72, in install_platformio_core
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/pioinstaller/penv.py", line 75, in create_core_penv
  File "/Users/scholar/.platformio/.cache/tmp/.piocore-installer-fs1i0r7m/tmpk_bakuq7/pioinstaller.zip/pioinstaller/penv.py", line 143, in add_state_info
  File "/Users/scholar/.platformio/python3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/scholar/.platformio/python3/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/scholar/.platformio/python3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/scholar/.platformio/python3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/scholar/.platformio/penv/bin/python'
 -> Installer version: 0.3.5
Platform: macOS-10.16
Python version: 3.8.4 (default, Jul 14 2020, 15:19:59) 
[Clang 10.0.0 (clang-1000.10.44.4)]
Python path: /Users/scholar/.platformio/python3/bin/python3
Creating a virtual environment at /Users/scholar/.platformio/penv

    at cmd (/Users/scholar/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:148:25)
    at ChildProcess.c (/Users/scholar/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:138:7)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
  ```

**Comment by Lemmah** [comment]
Resolved by reinstalling PlatformIO VS Code extension.
