### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by SinglWolf** [platformio/platformio-core-installer#378]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.51.1
  PIO IDE: v2.2.1
  System: Linux, 4.19.0-13-amd64, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO executable not found in `/home/developer/.platformio/penv/bin`

	at /home/developer/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/home/developer/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Please remove `~/.platformio/penv` folder and restart VSCode.
