### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Warpeas** [platformio/platformio-core-installer#384]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.51.1
  PIO IDE: v2.2.1
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 0.3.5
Platform: Windows-10
Python version: 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]
Python path: C:\Users\Hunter\miniconda3\python.exe
Creating a virtual environment at C:\Users\Hunter\.platformio\penv

    at c:\Users\Hunter\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:145:23
    at ChildProcess.c (c:\Users\Hunter\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:131:5)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.cp.emit (c:\Users\Hunter\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Sorry, we dropped support for conda to avoid a ton of issues that we had with it. Please install the latest Python 3 and restart VSCode.
