### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by BiggSmiles** [platformio/platformio-core-installer#386]
%23 Description of problem
  Leave a comment...
How to I get past this issue.
  I try to search for my issue, but no luck.
any help will be greatly appreciated,
Roy

![vscode_platformio](https://user-images.githubusercontent.com/21009964/102096078-4b525900-3df2-11eb-9cbc-d30e2b92b052.GIF)

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.0
  PIO IDE: v2.2.1
  System: Windows_NT, 10.0.18363, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 0.3.5
Platform: Windows-10
Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
Python path: C:\Python27\python.exe
Creating a virtual environment at C:\Users\Roy\.platformio\penv

    at c:\Users\Roy\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:145:23
    at ChildProcess.c (c:\Users\Roy\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:131:5)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.cp.emit (c:\Users\Roy\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Please install the latest Python 3 version https://docs.platformio.org/en/latest/faq.html#install-python-interpreter and restart VSCode.
