### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Zenquan** [platformio/platformio-core-installer#390]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.0
  PIO IDE: v2.2.1
  System: Darwin, 19.6.0, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an EnvironmentError: Could not find a suitable TLS CA certificate bundle, invalid path: /Users/zenquan/.platformio/penv/lib/python3.8/site-packages/pip/_vendor/certifi/cacert.pem

Error: Could not install PlatformIO Core: Command '['/Users/zenquan/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 0.3.5
Platform: macOS-10.15.6
Python version: 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]
Python path: /usr/local/opt/python@3.8/bin/python3.8
Creating a virtual environment at /Users/zenquan/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Using cached platformio-5.0.3.tar.gz (213 kB)

    at /Users/zenquan/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:145:23
    at ChildProcess.c (/Users/zenquan/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:131:5)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at Pipe.<anonymous> (net.js:664:12)
  ```

**Comment by ivankravets** [comment]
Please remove `/Users/zenquan/.platformio/penv` folder and restart VSCode.
