### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by abebars** [platformio/platformio-core-installer#400]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Darwin, 19.6.0, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/Users/abebars/.platformio/penv/lib/python3.8/site-packages/platformio-5.0.3.dist-info/INSTALLER9srmwv0s.tmp'

Error: Could not install PlatformIO Core: Command '['/Users/abebars/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 0.3.5
Platform: macOS-10.15.7
Python version: 3.8.4 (default, Jul 14 2020, 15:19:59) 
[Clang 10.0.0 (clang-1000.10.44.4)]
Python path: /Users/abebars/.platformio/python3/bin/python3
Creating a virtual environment at /Users/abebars/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Downloading platformio-5.0.3.tar.gz (213 kB)
Collecting bottle<0.13
  Downloading bottle-0.12.19-py3-none-any.whl (89 kB)
Collecting click<8,>=5
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting marshmallow>=2
  Downloading marshmallow-3.10.0-py2.py3-none-any.whl (46 kB)
Collecting pyelftools<1,>=0.25
  Downloading pyelftools-0.27-py2.py3-none-any.whl (151 kB)
Collecting pyserial!=3.3,<4,>=3
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting requests<3,>=2.4.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting semantic_version<3,>=2.8.1
  Downloading semantic_version-2.8.5-py2.py3-none-any.whl (15 kB)
Collecting tabulate<1,>=0.8.3
  Downloading tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: platformio
  Building wheel for platformio (setup.py): started
  Building wheel for platformio (setup.py): finished with status 'done'
  Created wheel for platformio: filename=platformio-5.0.3-py3-none-any.whl size=330400 sha256=762cf142bc32f67cdee901fd3ed5ce2a2789a5324e6bba7564dacc804b9e6f1c
  Stored in directory: /Users/abebars/Library/Caches/pip/wheels/0d/e2/9e/b21bb5d35bfb22c51670c59111f93a49a8c10fee4a3d70c45c
Successfully built platformio
Installing collected packages: urllib3, idna, chardet, certifi, tabulate, semantic-version, requests, pyserial, pyelftools, marshmallow, colorama, click, bottle, platformio

	at /Users/abebars/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/Users/abebars/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.EventEmitter.emit (domain.js:475:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at Pipe.<anonymous> (net.js:664:12)
  ```

**Comment by ivankravets** [comment]
Have you resolved this issue?
