### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by be-engineer** [platformio/platformio-core-installer#405]
%23 Description of problem
  When I install pio in code-server,I got this error message.

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.51.1
  PIO IDE: v2.2.1
  System: Linux, 4.19.0-6.ucloud, x64

  %23 Exception
  ```
  Error: EACCES: permission denied, mkdir '/home/coder/.platformio/.cache'
	at Object.mkdirSync (fs.js:921:3)
	at v (/home/coder/.local/share/code-server/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:2926)
	at Object.e.getTmpDir (/home/coder/.local/share/code-server/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:1124)
	at a (/home/coder/.local/share/code-server/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:8870)
	at e.callInstallerScript (/home/coder/.local/share/code-server/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:8128)
	at d.value (/home/coder/.local/share/code-server/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:870466)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async t.default.install (/home/coder/.local/share/code-server/extensions/platformio.platformio-ide-2.2.1/dist/extension.js:1:6459)
	at async /home/coder/.local/share/code-server/extensions/platformio.platformio-ide-2.2.1/dist/extension.js:1:12444
  ```

**Comment by ivankravets** [comment]
Have you resolved this issue?
