### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by kfine100** [platformio/platformio-core-installer#406]
Dear PlatformIO

I constantly get this error during an upgrade. Do I have a setting wrong somewhere?

Thanks, Kevin

 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Linux, 5.4.0-58-generic, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO installed using another platform `Linux-5.4.0-58-generic-x86_64-with-glibc2.10`. Your platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.29

	at /home/kevin/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/home/kevin/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Please remove `~/.platformio/penv` folder and restart VSCode.
