### ISSUE TITLE
Cannot install VS Code Platform.io IDE on MACBook Air using Catalina or Big Sur

### ISSUE THREAD

**Issue by windy54** [platformio/platformio-core-installer#412]
I have been trying to install platform.io IDE on my MacBook using
OS Catalina or Big Sur

for several months.

I have removed the .platformio folder and started again.
The following error is generated:

`Error: Traceback (most recent call last): File "/Users/stevengale/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 69, in <module> main() File "/Users/stevengale/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 61, in main bootstrap() File "/Users/stevengale/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 47, in bootstrap pioinstaller.__main__.main() File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/pioinstaller/__main__.py", line 122, in main File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/click/core.py", line 829, in __call__ File "/Users/ste...`

When I open the console window, there are lots of errors reported, I have copied the first few lines, please let me know if you need anymore.

`Error: PlatformIO Core has not been installed yet!	at d.value (/Users/stevengale/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:869828)	at async t.default.check (/Users/stevengale/.vscode/extensions/platformio.platformio-ide-2.2.1/dist/extension.js:1:6383)	at async /Users/stevengale/.vscode/extensions/platformio.platformio-ide-2.2.1/dist/extension.js:1:11856
t.log @ console.ts:112
console.ts:137 [Extension Host] runCommand /Users/stevengale/.platformio/python3/bin/python3 Array(2) Object
console.ts:137 [Extension Host] runCommand /Users/stevengale/.platformio/python3/bin/python3 Array(1) Object
notificationsAlerts.ts:40 Error: Traceback (most recent call last):   File "/Users/stevengale/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 69, in <module>     main()   File "/Users/stevengale/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 61, in main     bootstrap()   File "/Users/stevengale/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 47, in bootstrap     pioinstaller.__main__.main()   File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/pioinstaller/__main__.py", line 122, in main   File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/click/core.py", line 829, in __call__   File "/Users/ste...
onDidChangeNotification @ notificationsAlerts.ts:36
console.ts:137 [Extension Host] Error: Traceback (most recent call last):  File "/Users/stevengale/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 69, in <module>    main()  File "/Users/stevengale/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 61, in main    bootstrap()  File "/Users/stevengale/.platformio/.cache/tmp/get-platformio-0.3.5.py", line 47, in bootstrap    pioinstaller.__main__.main()  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/pioinstaller/__main__.py", line 122, in main  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/click/core.py", line 829, in __call__  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/click/core.py", line 782, in main  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/click/core.py", line 1236, in invoke  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/click/core.py", line 1066, in invoke  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/click/core.py", line 610, in invoke  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/click/decorators.py", line 21, in new_func  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/pioinstaller/__main__.py", line 52, in cli  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/pioinstaller/core.py", line 72, in install_platformio_core  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/pioinstaller/penv.py", line 52, in create_core_penv  File "/Users/stevengale/.platformio/.cache/tmp/.piocore-installer-_k9fvkza/tmphgfooxn4/pioinstaller.zip/pioinstaller/python.py", line 170, in find_compatible_pythons  File "/Users/stevengale/.platformio/python3/lib/python3.8/subprocess.py", line 411, in check_output    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,  File "/Users/stevengale/.platformio/python3/lib/python3.8/subprocess.py", line 489, in run    with Popen(*popenargs, **kwargs) as process:  File "/Users/stevengale/.platformio/python3/lib/python3.8/subprocess.py", line 854, in __init__    self._execute_child(args, executable, preexec_fn, close_fds,  File "/Users/stevengale/.platformio/python3/lib/python3.8/subprocess.py", line 1702, in _execute_child    raise child_exception_type(errno_num, err_msg, err_filename)OSError: [Errno 86] Bad CPU type in executable: '/usr/local/bin/python2' -> Installer version: 0.3.5Platform: macOS-10.16Python version: 3.8.4 (default, Jul 14 2020, 15:19:59) [Clang 10.0.0 (clang-1000.10.44.4)]Python path: /Users/stevengale/.platformio/python3/bin/python3Creating a virtual environment at /Users/stevengale/.platformio/penv	at /Users/stevengale/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275	at ChildProcess.c (/Users/stevengale/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)	at ChildProcess.emit (events.js:223:5)	at maybeClose (internal/child_process.js:1021:16)	at Socket.<anonymous> (internal/child_process.js:430:11)	at Socket.emit (events.js:223:5)	at Pipe.<anonymous> (net.js:664:12)
t.log @ console.ts:112
console.ts:137 [Extension Host] rejected promise not handled within 1 second: RangeError: Maximum call stack size exceeded`

**Comment by windy54** [comment]
Got there thanks to the community, I had somehow installed several versions of python, removing that let me install it. Then I had a problem building, issues with isnan and other time functions not being defined in std namespace.
Was to,d to delete the frameworks, update platform io and then do a build. This reinstalled all the frameworks and can now build the code. So hopefully can now look at some issues.
