### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Auravendill** [platformio/platformio-core-installer#413]
%23 Description of problem
  Whenever I start  VS Code, it tries to install the latest version and fails as shown below. I installed platformio later manually via conda, but that didn't change anything either, but at least it is usable this way (but extremely annoying, of course)

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Linux, 4.19.0-13-amd64, x64

  %23 Exception
  ```
  Error: /home/daniel/.platformio/penv/bin/python: No module named pip
Error: Could not install PlatformIO Core: Command '['/home/daniel/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 0.3.5
Platform: Linux-4.19.0-13-amd64-x86_64-with-glibc2.10
Python version: 3.7.8 | packaged by conda-forge | (default, Nov 17 2020, 23:45:15) 
[GCC 7.5.0]
Python path: /home/daniel/Programme/miniconda3/bin/python3
Creating a virtual environment at /home/daniel/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

    at cmd (/home/daniel/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:148:25)
    at ChildProcess.c (/home/daniel/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/webpack:/platformio-node-helpers/src/proc.js:138:7)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Sorry, we dropped support for conda to avoid a ton of issues that we had with it. Please install the latest Python 3 and restart VSCode.
