### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by hugoferreira** [platformio/platformio-core-installer#418]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Darwin, 20.2.0, x64

  %23 Exception
  ```
  Error: Fatal Python error: _PyInterpreterState_Get(): no current thread state
Python runtime state: unknown


	at /Users/bytter/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/Users/bytter/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by hugoferreira** [comment]
This error is happening a lot in the past months. I'm not sure if I should blame Big Sur, VSCode, or Platform.IO, but one workaround for this is to install Platform.IO independently in the command line, and add the CLI tools to the path before attempting to install the plugin in VSCode.
