### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Sherman-c** [platformio/platformio-core-installer#421]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: 
	at c:\Users\Sherman\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\index.js:1:879275
	at ChildProcess.c (c:\Users\Sherman\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.cp.emit (c:\Users\Sherman\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by Sherman-c** [comment]
Hi Ivan

Sorry for the late reply, no the issue still remains.

Regards
Sherman
.

**Comment by ivankravets** [comment]
Do you use 3rd party antivirus tools in a system?

**Comment by Sherman-c** [comment]
Hi Ivan,

Yes i do have antivirus software, comodo, but i tried disabled antivirus,
before installing vscode and platformio, the result were the same,  it
seems something wrong on the environment variable setup.

Regards,
Sherman
