### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by wangzhiqing1993** [platformio/platformio-core-installer#422]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 0.3.5
Platform: Windows-10
Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Python path: D:\Program\Python\Miniconda\python.exe
Creating a virtual environment at C:\Users\wangz\.platformio\penv

    at cmd (c:\Users\wangz\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:148:25)
    at ChildProcess.c (c:\Users\wangz\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:138:7)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.cp.emit (c:\Users\wangz\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
yes, we don't support anaconda. Please install the latest official Python 3 https://docs.platformio.org/en/latest/faq.html#install-python-interpreter and restart installer
