### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by AxelWol** [platformio/platformio-core-installer#441]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Windows_NT, 10.0.21292, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\axelwol\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "C:\Users\axelwol\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "C:\Users\axelwol\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 45, in bootstrap
    import pioinstaller.__main__
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\axelwol\.platformio\.cache\tmp\.piocore-installer-6z900ozw\tmpy5f7k3qp\pioinstaller.zip\pioinstaller\__init__.py", line 15, in <module>
  File "C:\Python38\lib\logging\config.py", line 30, in <module>
    import logging.handlers
  File "C:\Python38\lib\logging\handlers.py", line 26, in <module>
    import logging, socket, os, pickle, struct, time, re
  File "C:\Python38\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed while importing _socket: The specified module could not be found.

    at cmd (c:\Users\axelwol\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:148:25)
    at ChildProcess.c (c:\Users\axelwol\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:138:7)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at ChildProcess.cp.emit (c:\Users\axelwol\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
You have broken Python at C:\Python38

Please uninstall it and restart VSCode. PlatformIO IDe has built-in Python.
