### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Sya0** [platformio/platformio-core-installer#451]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Linux, 5.4.0-64-generic, x64

  %23 Exception
  ```
  Error: ERROR: Could not install packages due to an EnvironmentError: Could not find a suitable TLS CA certificate bundle, invalid path: /home/sukruuzun/.platformio/penv/lib/python3.8/site-packages/pip/_vendor/certifi/cacert.pem

Error: Could not install PlatformIO Core: Command '['/home/sukruuzun/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 -> Installer version: 0.3.5
Platform: Linux-5.4.0-64-generic-x86_64-with-glibc2.29
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/sukruuzun/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Collecting platformio
  Downloading platformio-5.0.4.tar.gz (213 kB)

	at /home/sukruuzun/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/home/sukruuzun/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Are you from China? Bad guys removed genuine certificates from `certifi` package.

How to avoid them? Could you try VPN?

Try to remove `/home/sukruuzun/.platformio/penv` folder and restart
