### ISSUE TITLE
hay hi i need help

### ISSUE THREAD

**Issue by Aditya00712** [platformio/platformio-core-installer#452]
i wamt trying to install PlatformIO on my computer and i am getting this error, I am totally noob in this stuff please help

%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  Error: The system cannot find the path specified.
Error: spawn PLATFORMIO_HOME_DIR\python3\python.exe ENOENT
    at cmd (c:\Users\adity\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:148:25)
    at completed (c:\Users\adity\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:138:7)
    at ChildProcess.<anonymous> (c:\Users\adity\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:124:9)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.cp.emit (c:\Users\adity\.vscode\extensions\platformio.platformio-ide-2.2.1\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
  ```

**Comment by ivankravets** [comment]
Please remove `PLATFORMIO_HOME_DIR` env varaible from your system
