### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by dhkabayel** [platformio/platformio-core-installer#455]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.52.1
  PIO IDE: v2.2.1
  System: Darwin, 20.2.0, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO executable not found in `/Users/dogukabayel/.platformio/penv/bin`

	at /Users/dogukabayel/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/Users/dogukabayel/.vscode/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.EventEmitter.emit (domain.js:475:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at Pipe.<anonymous> (net.js:664:12)
  ```

**Comment by ivankravets** [comment]
Please remove `/Users/dogukabayel/.platformio/penv` folder and restart VSCode.
