### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by AstroKiste** [platformio/platformio-core-installer#476]
Hello,

installing platformio on atom.io gives me the following error:
Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues -> Installer version: 0.3.5 Platform: Darwin-15.6.0 Python version: 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] Python path: /usr/bin/python Creating a virtual environment at /Users/mk/.platformio/penv

at /Users/mk/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5004
at ChildProcess.s (/Users/mk/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4900)
at ChildProcess.emit (events.js:200:13)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

not sure if I am doing the right thing here but I am very new to all of this.
Any suggestions?

best regards

**Comment by AstroKiste** [comment]
Installing python 3.x solved the issue. 
best regards
