### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Dilexan** [platformio/platformio-core-installer#49]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.45.1
  PIO IDE: v2.0.0-beta.1
  System: Windows_NT, 10.0.18363, x64

  %23 Exception
  ```
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.dirname (path.js:583:5)
	at t.value (c:\Users\User\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.1\node_modules\platformio-node-helpers\dist\index.js:1:29833)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async t.value (c:\Users\User\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.1\node_modules\platformio-node-helpers\dist\index.js:1:28808)
	at async Promise.all (index 0)
	at async c:\Users\User\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.1\dist\extension.js:1:5927
  ```

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please upgrade PlatformIO IDE for VSCode to the latest version.
