### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ChrisisZann** [platformio/platformio-core-installer#502]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.54.0-insider
  PIO IDE: v2.2.1
  System: Darwin, 20.3.0, arm64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO executable not found in `/Users/yippee/.platformio/penv/bin`

	at /Users/yippee/.vscode-insiders/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879275
	at ChildProcess.c (/Users/yippee/.vscode-insiders/extensions/platformio.platformio-ide-2.2.1/node_modules/platformio-node-helpers/dist/index.js:1:879169)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)
  ```

**Comment by ChrisisZann** [comment]
cannot install under apple m1
