### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by antiguaMob** [platformio/platformio-core-installer#54]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.47.3
  PIO IDE: v2.0.0-beta.5
  System: Windows_NT, 10.0.18363, x64

  %23 Exception
  ```
  Error: c:\users\antigua\appdata\local\temp\tmph26vgv\pioinstaller.zip\urllib3\util\ssl_.py:387: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html%23ssl-warnings
c:\users\antigua\appdata\local\temp\tmph26vgv\pioinstaller.zip\urllib3\util\ssl_.py:142: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html%23ssl-warnings
c:\users\antigua\appdata\local\temp\tmph26vgv\pioinstaller.zip\urllib3\util\ssl_.py:142: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html%23ssl-warnings
c:\users\antigua\appdata\local\temp\tmph26vgv\pioinstaller.zip\urllib3\util\ssl_.py:142: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html%23ssl-warnings
c:\users\antigua\appdata\local\temp\tmph26vgv\pioinstaller.zip\urllib3\util\ssl_.py:142: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html%23ssl-warnings
c:\users\antigua\appdata\local\temp\tmph26vgv\pioinstaller.zip\urllib3\util\ssl_.py:142: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html%23ssl-warnings
Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 0.3.2
Platform: Windows-8
Python version: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
Python path: C:\Python27\python.exe
Creating a virtual environment at C:\Users\antigua\.platformio\penv

	at c:\Users\antigua\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\node_modules\platformio-node-helpers\dist\index.js:1:4882
	at ChildProcess.c (c:\Users\antigua\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\node_modules\platformio-node-helpers\dist\index.js:1:4778)
	at ChildProcess.emit (events.js:203:13)
	at ChildProcess.EventEmitter.emit (domain.js:476:20)
	at ChildProcess.cp.emit (c:\Users\antigua\.vscode\extensions\platformio.platformio-ide-2.0.0-beta.5\node_modules\platformio-node-helpers\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Fixed in the latest release. Please upgrade PlatfromIO IDE to the latest version.
