### ISSUE TITLE
Getting this issue, have tried all the "fixes"

### ISSUE THREAD

**Issue by williamrehndell** [platformio/platformio-core-installer#554]
`Error: Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp\.piocore-installer-2gel0nxd\tmpadobqd_i\pioinstaller.zip\pioinstaller\python.py", line 170, in find_compatible_pythons
  File "C:\.platformio\python3\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\.platformio\python3\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\William\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe', 'C:\\.platformio\\.cache\\tmp\\get-platformio-1.0.0.py', '--no-shutdown-piohome', 'check', 'python']' returned non-ze...`

**Comment by tazman19** [comment]
I have the same exact error, same lines, but slightly different file names:
.piocore-installer-s674c8wi
instead of 
.piocore-installer-2gel0nxd
