### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Hydrosys4** [platformio/platformio-core-installer#557]
%23 Description of problem
  Ubuntu 20.04 

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.54.1
  PIO IDE: v2.3.0
  System: Linux, 5.4.0-66-generic, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not import PlatformIO module. Error: Traceback (most recent call last):
  File "<string>", line 12, in <module>
Exception: Unsupported Python version: 2.7.18. Minimum supported Python version is 3.6 or above.


	at /home/anona/.vscode/extensions/platformio.platformio-ide-2.3.0/node_modules/platformio-node-helpers/dist/index.js:1:930873
	at ChildProcess.c (/home/anona/.vscode/extensions/platformio.platformio-ide-2.3.0/node_modules/platformio-node-helpers/dist/index.js:1:930767)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:483:12)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
  ```

**Comment by Hydrosys4** [comment]
Solved by assigning the python 3.8 as default with the following command in ubuntu terminal:
sudo update-alternatives  --set python /usr/bin/python3.6
removed the folder .platformio and reinstalled the platformio from the IDE.
