### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by kergaradec** [platformio/platformio-core-installer#558]
Problème d'installation de l’extension PlatformIO en version 2.3.0 avec vscode en version 1.54.1.
Par contre si j'installe le version 1.10 de l'extension alors je n'ai plus de problème.

****

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.54.1
  PIO IDE: v2.3.0
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
	at validateString (internal/validators.js:120:11)
	at Object.dirname (path.js:583:5)
	at E.value (c:\Users\frede\.vscode\extensions\platformio.platformio-ide-2.3.0\node_modules\platformio-node-helpers\dist\index.js:1:924600)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async E.value (c:\Users\frede\.vscode\extensions\platformio.platformio-ide-2.3.0\node_modules\platformio-node-helpers\dist\index.js:1:923268)
	at async t.default.install (c:\Users\frede\.vscode\extensions\platformio.platformio-ide-2.3.0\dist\extension.js:1:6509)
	at async c:\Users\frede\.vscode\extensions\platformio.platformio-ide-2.3.0\dist\extension.js:1:12420
  ```

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core-installer/issues/533
