### ISSUE TITLE
ERREUR INSTALLATION Platformio 

### ISSUE THREAD

**Issue by PPHIL972** [platformio/platformio-core-installer#579]
Issue Type: <b>Bug</b>

Bonjour, j'ai lancé l'installation de l'IDE Platformio et celle-ci est avortée avec le message d'erreur suivant: Error: Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp\.piocore-installer-1cj23ff2\tmpyqr7svd6\pioinstaller.zip\pioinstaller\python.py", line 170, in find_compatible_pythons
  File "C:\.platformio\python3\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\.platformio\python3\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\philp\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe', 'C:\\.platformio\\.cache\\tmp\\get-platformio-1.0.0.py', '--no-shutdown-piohome', 'check', 'python']' returned non-zero...

In y a 3 solutions proposées qui ne fonctionnent pas. Merci de votre aide.

Extension version: 2.3.0
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (10.49GB free)|
|Process Argv|--crash-reporter-id 3dd9f669-7f77-408d-8a61-4c76a2ea9ca4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by bbyku** [comment]
Hi 
I have same issue.It helped when i was inside vscode in TERMINAL just type PYTHON it should open windows store and install it from there then restart VSCODE and should work
GOOD LUCK
