### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by morgift** [platformio/platformio-core-installer#587]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.54.2
  PIO IDE: v2.3.0
  System: Linux, 4.15.0-124-generic, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 1.0.0
Platform: Linux-4.15.0-124-generic-x86_64-with-glibc2.25
Python version: 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/ofer/.platformio/penv

	at /home/ofer/.vscode/extensions/platformio.platformio-ide-2.3.0/node_modules/platformio-node-helpers/dist/index.js:1:930873
	at ChildProcess.c (/home/ofer/.vscode/extensions/platformio.platformio-ide-2.3.0/node_modules/platformio-node-helpers/dist/index.js:1:930767)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:483:12)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:443:11)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:483:12)
	at Pipe.<anonymous> (net.js:674:12)
  ```

**Comment by ivankravets** [comment]
Could you open the system terminal and run the installer manually? Please DO NOT USE `sudo`. 

See instruction here https://docs.platformio.org/en/latest/core/installation.html#super-quick-mac-linux

Does it work now?
