### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Huell-Howitzer** [platformio/platformio-core-installer#60]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.48.2
  PIO IDE: v2.0.0
  System: Linux, 3.10.0-1127.18.2.el7.x86_64, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 0.3.4
Platform: Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-glibc2.2.5
Python version: 2.7.5 (default, Apr  2 2020, 13:16:51) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Python path: /usr/bin/python
Creating a virtual environment at /home/ryan.howell/.platformio/penv

	at /home/ryan.howell/.vscode/extensions/platformio.platformio-ide-2.0.0/node_modules/platformio-node-helpers/dist/index.js:1:4911
	at ChildProcess.c (/home/ryan.howell/.vscode/extensions/platformio.platformio-ide-2.0.0/node_modules/platformio-node-helpers/dist/index.js:1:4807)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Minimum supported Python is 2.7.9. Could you install Python 3 and restart VSCode?

**Comment by ivankravets** [comment]
Please reopen if you still need help
