### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by takurx** [platformio/platformio-core-installer#632]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.53.2
  PIO IDE: v2.3.0
  System: Linux, 5.8.0-45-generic, x64

  %23 Exception
  ```
  Error: Error: Could not install PlatformIO Core: [Errno 2] No such file or directory: '/home/chiya/.platformio/penv/bin/python'
 -> Installer version: 1.0.0
Platform: Linux-5.8.0-45-generic-x86_64-with-glibc2.29
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
Python path: /usr/bin/python3
Creating a virtual environment at /home/chiya/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core

	at /home/chiya/.vscode/extensions/platformio.platformio-ide-2.3.0/node_modules/platformio-node-helpers/dist/index.js:1:930873
	at ChildProcess.c (/home/chiya/.vscode/extensions/platformio.platformio-ide-2.3.0/node_modules/platformio-node-helpers/dist/index.js:1:930767)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:483:12)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
  ```

**Comment by ivankravets** [comment]
Please remove `/home/chiya/.platformio/penv` folder and restart VSCode.
