### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by danielelec1** [platformio/platformio-core-installer#650]
Hi,

I need your help, I can´t install install platformio in ATOM because the program tells me to install python 3 but it is already installed on the computer. I assign the folder where Python 3 is located but it tells me to install it.

**Comment by danielelec1** [comment]
Thats the problem

Error: Can not find Python Interpreter. Please install Python 3.5 or above manually at t.value (C:\Users\user.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:30165) at processTicksAndRejections (internal/process/task_queues.js:89:5) at t.value (C:\Users\user.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:27975) at async Promise.all (index 3)
