### ISSUE TITLE
Can't seem to be able to install PlatformIO on my windows machine

### ISSUE THREAD

**Issue by GunZi200** [platformio/platformio-core-installer#654]
I am using a machine from work and am not sure if it is my problem. I cannot seem to install PlatformIO in Visual Studio Code it fails. Would appreciate any help on this.

I then tried to  follow this instruction:

![image](https://user-images.githubusercontent.com/8218499/112751575-52c2fa00-8fbe-11eb-86ac-1574576dc0f1.png)

but I get the following error:

This is my terminal's output on Windows 10:
```bash
Microsoft Windows [Version 10.0.19042.870]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\gudnigi\Downloads\platformio-core-installer>python.exe get-platformio.py
Installer version: 1.0.1
Platform: Windows-10
Python version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Python path: C:\Program Files\Python39\python.exe
Creating a virtual environment at C:\Users\gudnigi\.platformio\penv
Traceback (most recent call last):
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\pioinstaller\python.py", line 199, in find_compatible_pythons
  File "C:\Program Files\Python39\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\gudnigi\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe', 'C:\\Users\\gudnigi\\Downloads\\platformio-core-installer\\get-platformio.py', '--no-shutdown-piohome', 'check', 'python']' returned non-zero exit status 9009.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\get-platformio.py", line 68, in <module>
    main()
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\get-platformio.py", line 60, in main
    bootstrap()
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\get-platformio.py", line 46, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\pioinstaller\__main__.py", line 131, in main
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\click\core.py", line 829, in __call__
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\click\core.py", line 782, in main
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\click\core.py", line 1236, in invoke
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\click\core.py", line 1066, in invoke
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\click\core.py", line 610, in invoke
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\click\decorators.py", line 21, in new_func
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\pioinstaller\core.py", line 67, in install_platformio_core
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\pioinstaller\core.py", line 95, in _install_platformio_core
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\pioinstaller\penv.py", line 52, in create_core_penv
  File "C:\Users\gudnigi\Downloads\platformio-core-installer\.piocore-installer-cfaqla37\tmpthanhj3n\pioinstaller.zip\pioinstaller\python.py", line 220, in find_compatible_pythons
UnboundLocalError: local variable 'error' referenced before assignment

C:\Users\gudnigi\Downloads\platformio-core-installer>
```

When I try to install using Visual Studio Code (by installing the plugin) I get these errors:

![image](https://user-images.githubusercontent.com/8218499/112751893-cfa2a380-8fbf-11eb-8e0c-0eacd9f56ea0.png)

![image](https://user-images.githubusercontent.com/8218499/112751931-04165f80-8fc0-11eb-9c26-edce71c851ec.png)

![image](https://user-images.githubusercontent.com/8218499/112751939-11334e80-8fc0-11eb-9a45-71f3e3c92974.png)

![image](https://user-images.githubusercontent.com/8218499/112751975-3627c180-8fc0-11eb-8da7-8b1a4427c7ba.png)

**Comment by GunZi200** [comment]
Fixed the issue by installing the Python 3.9 from Microsoft Store. Seems to work 🤷‍♂️
