### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by mcislo** [platformio/platformio-core-installer#664]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.55.0
  PIO IDE: v2.3.1
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\cislom\.platformio\.cache\tmp\get-platformio-1.0.1.py", line 69, in <module>
    main()
  File "C:\Users\cislom\.platformio\.cache\tmp\get-platformio-1.0.1.py", line 61, in main
    bootstrap()
  File "C:\Users\cislom\.platformio\.cache\tmp\get-platformio-1.0.1.py", line 47, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\pioinstaller\__main__.py", line 131, in main
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\click\core.py", line 829, in __call__
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\click\core.py", line 782, in main
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\click\core.py", line 1259, in invoke
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\click\core.py", line 1259, in invoke
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\click\core.py", line 1066, in invoke
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\click\core.py", line 610, in invoke
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\click\decorators.py", line 21, in new_func
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\pioinstaller\__main__.py", line 112, in core_check
  File "C:\Users\cislom\.platformio\.cache\tmp\.piocore-installer-4k2fvcvx\tmpw5c1ipef\pioinstaller.zip\pioinstaller\core.py", line 214, in check
  File "C:\Users\cislom\.platformio\python3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\cislom\.platformio\python3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\cislom\.platformio\python3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\cislom\.platformio\python3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

	at c:\Users\cislom\.vscode\extensions\platformio.platformio-ide-2.3.1\node_modules\platformio-node-helpers\dist\index.js:1:931162
	at ChildProcess.o (c:\Users\cislom\.vscode\extensions\platformio.platformio-ide-2.3.1\node_modules\platformio-node-helpers\dist\index.js:1:931056)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:483:12)
	at ChildProcess.cp.emit (c:\Users\cislom\.vscode\extensions\platformio.platformio-ide-2.3.1\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
  ```

**Comment by mcislo** [comment]
I uninstalled a different Python compiler and uninstalled the .platformio folder and reinstalled - get the same error.

**Comment by mcislo** [comment]
FIX - for me at least.  

I had turned off my Antivirus, but forgot that I had Acronis running - this has some "safety" issue that prevents access to some files.  Once I turned that off I was able to complete the installation.

Thanks!

**Comment by mcislo** [comment]
FIX - for me at least.

I had turned off my Antivirus, but forgot that I had Acronis running - this has some "safety" issue that prevents access to some files. Once I turned that off I was able to complete the installation.

Thanks!
