### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by sabbathin** [platformio/platformio-core-installer#676]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.55.0
  PIO IDE: v2.3.1
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\qaval\.platformio\.cache\tmp\get-platformio-1.0.1.py", line 69, in <module>
    main()
  File "C:\Users\qaval\.platformio\.cache\tmp\get-platformio-1.0.1.py", line 61, in main
    bootstrap()
  File "C:\Users\qaval\.platformio\.cache\tmp\get-platformio-1.0.1.py", line 45, in bootstrap
    import pioinstaller.__main__
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\qaval\.platformio\.cache\tmp\.piocore-installer-h3xo0e6e\tmprwcjuiss\pioinstaller.zip\pioinstaller\__init__.py", line 15, in <module>
  File "C:\Users\qaval\.platformio\python3\lib\logging\config.py", line 30, in <module>
    import logging.handlers
  File "C:\Users\qaval\.platformio\python3\lib\logging\handlers.py", line 26, in <module>
    import logging, socket, os, pickle, struct, time, re
  File "C:\Users\qaval\.platformio\python3\lib\socket.py", line 51, in <module>
    import _socket
ModuleNotFoundError: No module named '_socket'

    at cmd (c:\Users\qaval\.vscode\extensions\platformio.platformio-ide-2.3.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:188:25)
    at ChildProcess.o (c:\Users\qaval\.vscode\extensions\platformio.platformio-ide-2.3.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:178:7)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at ChildProcess.cp.emit (c:\Users\qaval\.vscode\extensions\platformio.platformio-ide-2.3.1\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
  ```

**Comment by abdset** [comment]
I had same issue with different lines numbers in errors codes and i solved it by doing this assuming you are at the point where the installation did not work (broken) but still there (not uninstalled):
- Click on the settings gear next to PlatformIO IDE module.
- Choose Install another version.
-  Pick 1.10.0 version.
- Click on Reload (Small blue button).
- Restart VSCode (Just in case).

PS: In the attempt to use cmd to install it i go an error saying that the acces is denied, so maybe devs should consider fixing permission code for version 2 cz right now only version 1 seems to be working (At least for me).
