### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by 79994350** [platformio/platformio-core-installer#745]
Installation Manager

Error: Can not find Python Interpreter. Please install Python 3.5 or above manually at t.value (C:\Users\pc.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:30165) at t.value (C:\Users\pc.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:27975) at async Promise.all (index 3)

**Comment by 79994350** [comment]
Installation Manager

Error: Can not find Python Interpreter. Please install Python 3.5 or above manually at t.value (C:\Users\pc.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:30165) at t.value (C:\Users\pc.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:27975) at async Promise.all (index 3)
