### ISSUE TITLE
PlatformIO Core version 5.0.4 does not match version requirements >=5.1. 

### ISSUE THREAD

**Issue by Alive24** [platformio/platformio-core-installer#781]
%23 Description of problem
  Attempting to install platformIO in VSCode as extension.
  Tried removing ~\.vscode\extensions\platformio.platformio-ide-2.3.2 manually.
  Tried removing ~\.platformio manually.
  Proxies checked as it pings normally from China.
  Attempted to use `pio upgrade` and `platformio upgrade` but prompts `Error: Can not retrieve the latest PlatformIO version`

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.56.1
  PIO IDE: v2.3.2
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO Core version 5.0.4 does not match version requirements >=5.1.

	at c:\Users\xct24\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\platformio-node-helpers\dist\index.js:1:931376
	at ChildProcess.a (c:\Users\xct24\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\platformio-node-helpers\dist\index.js:1:931270)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:467:12)
	at ChildProcess.cp.emit (c:\Users\xct24\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by Alive24** [comment]
Potentially information logs from VSCode developer tools.

```
[Extension Host] runCommand C:\Users\xct24\.platformio\python3\python.exe (2) ["-c", "import sys;assert sys.version_info >= (3, 6);print(sys.executable)"] {spawnOptions: {…}, _id: "C:\Users\xct24\.platformio\python3\python.exe-0.6670166021293562"}
```
```
[Extension Host] runCommand C:\Users\xct24\.platformio\python3\python.exe ["C:\Users\xct24\.platformio\.cache\tmp\get-platformio-1.0.2.py"] {spawnOptions: {…}, _id: "C:\Users\xct24\.platformio\python3\python.exe-0.07438784827795097"}
```
```
[Extension Host] Installer version: 1.0.2
Platform: Windows-10
Python version: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Python path: C:\Users\xct24\.platformio\python3\python.exe
Creating a virtual environment at C:\Users\xct24\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
PIP has been successfully updated!
Virtual environment has been successfully created!
Installing PlatformIO Core
Looking in indexes: https://mirrors.163.com/pypi/simple/
Collecting platformio
  Using cached https://mirrors.163.com/pypi/packages/b8/f0/4e9941349c3450838667d323545b256d91b723a4685a1e056f01642b851e/platformio-5.1.1.tar.gz (215 kB)
Collecting bottle==0.12.*
  Using cached https://mirrors.163.com/pypi/packages/e9/39/2bf3a1fd963e749cdbe5036a184eda8c37d8af25d1297d94b8b7aeec17c4/bottle-0.12.18-py3-none-any.whl (89 kB)
Collecting click!=7.1,!=7.1.1,<8,>=5
  Using cached https://mirrors.163.com/pypi/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting colorama
  Using cached https://mirrors.163.com/pypi/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting marshmallow<4,>=2
  Using cached https://mirrors.163.com/pypi/packages/57/06/87c14302f51d76a94945ae08da449baccb91f4d710c339fd1a1499209c45/marshmallow-3.11.1-py2.py3-none-any.whl (46 kB)
Collecting platformio
  Using cached https://mirrors.163.com/pypi/packages/b2/68/63ed6a16eb5338ee81ff0e32697a4c5f4840c3c684f62373c2ae8e9cf734/platformio-5.1.0.tar.gz (214 kB)
  Using cached platformio-5.0.4-py3-none-any.whl
Collecting pyserial!=3.3,<4,>=3
  Using cached https://mirrors.163.com/pypi/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting requests<3,>=2.4.0
  Using cached https://mirrors.163.com/pypi/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pyelftools<1,>=0.25
  Using cached https://mirrors.163.com/pypi/packages/bb/2f/bf41f3c3867d6707fa9b872658bb23088a64d0e522e8979f54c694b8cbe1/pyelftools-0.26-py2.py3-none-any.whl (136 kB)
Collecting semantic-version<3,>=2.8.1
  Using cached https://mirrors.163.com/pypi/packages/a5/15/00ef3b7888a10363b7c402350eda3acf395ff05bebae312d1296e528516a/semantic_version-2.8.5-py2.py3-none-any.whl (15 kB)
Collecting tabulate<1,>=0.8.3
  Using cached https://mirrors.163.com/pypi/packages/c4/f4/770ae9385990f5a19a91431163d262182d3203662ea2b5739d0fcfc080f1/tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting certifi>=2017.4.17
  Using cached https://mirrors.163.com/pypi/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached https://mirrors.163.com/pypi/packages/23/fc/8a49991f7905261f9ca9df5aa9b58363c3c821ce3e7f671895442b7100f2/urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Collecting idna<3,>=2.5
  Using cached https://mirrors.163.com/pypi/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Using cached https://mirrors.163.com/pypi/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Installing collected packages: urllib3, idna, chardet, certifi, tabulate, semantic-version, requests, pyserial, pyelftools, marshmallow, colorama, click, bottle, platformio
Successfully installed bottle-0.12.18 certifi-2020.12.5 chardet-3.0.4 click-7.1.2 colorama-0.4.4 idna-2.10 marshmallow-3.11.1 platformio-5.0.4 pyelftools-0.26 pyserial-3.5 requests-2.25.1 semantic-version-2.8.5 tabulate-0.8.7 urllib3-1.26.3

PlatformIO Core has been successfully installed into an isolated environment `C:\Users\xct24\.platformio\penv`!

The full path to `platformio.exe` is `C:\Users\xct24\.platformio\penv\Scripts\platformio.exe`

If you need an access to `platformio.exe` from other applications, please install Shell Commands
(add PlatformIO Core binary directory `C:\Users\xct24\.platformio\penv\Scripts` to the system environment PATH variable):

See https://docs.platformio.org/page/installation.html#install-shell-commands

```
```
[Extension Host] runCommand C:\Users\xct24\.platformio\python3\python.exe (2) ["-c", "import sys;assert sys.version_info >= (3, 6);print(sys.executable)"] {spawnOptions: {…}, _id: "C:\Users\xct24\.platformio\python3\python.exe-0.3606478450214172"}
```
```
[Extension Host] runCommand C:\Users\xct24\.platformio\python3\python.exe (8) ["C:\Users\xct24\.platformio\.cache\tmp\get-platformio-1.0.2.py", "check", "core", "--no-auto-upgrade", "--version-spec", ">=5.1", "--dump-state", "C:\Users\xct24\.platformio\.cache\tmp\core-dump-16612.json"]0: "C:\Users\xct24\.platformio\.cache\tmp\get-platformio-1.0.2.py"1: "check"2: "core"3: "--no-auto-upgrade"4: "--version-spec"5: ">=5.1"6: "--dump-state"7: "C:\Users\xct24\.platformio\.cache\tmp\core-dump-16612.json"length: 8__proto__: Array(0) {spawnOptions: {…}, _id: "C:\Users\xct24\.platformio\python3\python.exe-0.19142881400507927"}
```
```
Error: Error: Compatible PlatformIO Core not found. Reason: PlatformIO Core version 5.0.4 does not match version requirements >=5.1.  	at c:\Users\xct24\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\platformio-node-helpers\dist\index.js:1:931376 	at ChildProcess.a (c:\Users\xct24\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\platformio-node-helpers\dist\index.js:1:931270) 	at ChildProcess.emit (events.js:315:20) 	at ChildProcess.EventEmitter.emit (domain.js:467:12) 	at ChildProcess.cp.emit (c:\Users\xct24\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\cross-spawn\lib\enoent.js:34:29) 	at maybeClose (internal/child_process.js:1048:16) 	at...
```
```
console.ts:137 [Extension Host] Error: Error: Compatible PlatformIO Core not found.
Reason: PlatformIO Core version 5.0.4 does not match version requirements >=5.1.
	at c:\Users\xct24\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\platformio-node-helpers\dist\index.js:1:931376	at ChildProcess.a (c:\Users\xct24\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\platformio-node-helpers\dist\index.js:1:931270)	at ChildProcess.emit (events.js:315:20)	at ChildProcess.EventEmitter.emit (domain.js:467:12)	at ChildProcess.cp.emit (c:\Users\xct24\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\cross-spawn\lib\enoent.js:34:29)	at maybeClose (internal/child_process.js:1048:16)	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by Alive24** [comment]
Seems fixed in the latest update. Closing.
