### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by PanwarParamveer** [platformio/platformio-core-installer#79]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.48.2
  PIO IDE: v2.0.1
  System: Windows_NT, 10.0.18363, x64

  %23 Exception
  ```
  Error: Error: Compatible PlatformIO Core not found.
Reason: Could not run `C:\Users\HP\.platformio\penv\Scripts\platformio.exe --version`.
Error: Traceback (most recent call last):

  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\Python38\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "C:\Users\HP\.platformio\penv\Scripts\platformio.exe\__main__.py", line 4, in <module>

  File "c:\users\hp\.platformio\penv\lib\site-packages\platformio\__main__.py", line 19, in <module>

    import click

ModuleNotFoundError: No module named 'click'



	at c:\Users\HP\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\platformio-node-helpers\dist\index.js:1:4911
	at ChildProcess.c (c:\Users\HP\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\platformio-node-helpers\dist\index.js:1:4807)
	at ChildProcess.emit (events.js:203:13)
	at ChildProcess.cp.emit (c:\Users\HP\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Please remove `C:\Users\HP\.platformio\penv` folder and restart VSCode.
