### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by taherrera** [platformio/platformio-core-installer#797]
%23 Description of problem
I select the option "I have python" and add the path /usr/bin/python3.6 to the textbar

which python3.6
/usr/bin/python3.6
Python 3.6.13 (default, Feb 20 2021, 21:42:50) 

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.53.2
  PIO IDE: v2.3.2
  System: Linux, 4.15.0-52-generic, x64

  %23 Exception
  ```
  Error: Can not find Python Interpreter. Please install Python 3.6 or above manually
	at y.value (/home/tom/.vscode/extensions/platformio.platformio-ide-2.3.2/node_modules/platformio-node-helpers/dist/index.js:1:925223)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async y.value (/home/tom/.vscode/extensions/platformio.platformio-ide-2.3.2/node_modules/platformio-node-helpers/dist/index.js:1:923750)
	at async t.default.install (/home/tom/.vscode/extensions/platformio.platformio-ide-2.3.2/dist/extension.js:1:6693)
	at async /home/tom/.vscode/extensions/platformio.platformio-ide-2.3.2/dist/extension.js:1:12650
  ```

**Comment by taherrera** [comment]
I installed python3.7 however the problem persists.

**Comment by taherrera** [comment]
I installed python 3.7.10, however, the problem persists

**Comment by taherrera** [comment]
Installing Python 3.9.4 does not solve the problem either.
