### ISSUE TITLE
Installation Manager problem while installing

### ISSUE THREAD

**Issue by UtkarshChandel** [platformio/platformio-core-installer#811]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.56.2
  PIO IDE: v2.2.0
  System: Windows_NT, 10.0.19043, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\perso\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 69, in <module>
    main()
  File "C:\Users\perso\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 61, in main
    bootstrap()
  File "C:\Users\perso\.platformio\.cache\tmp\get-platformio-0.3.5.py", line 45, in bootstrap
    import pioinstaller.__main__
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\perso\.platformio\.cache\tmp\.piocore-installer-bapq8jvc\tmp4btr2fx0\pioinstaller.zip\pioinstaller\__init__.py", line 15, in <module>
  File "C:\Users\perso\AppData\Local\Programs\Python\Python38\lib\logging\config.py", line 30, in <module>
    import logging.handlers
  File "C:\Users\perso\AppData\Local\Programs\Python\Python38\lib\logging\handlers.py", line 26, in <module>
    import logging, socket, os, pickle, struct, time, re
  File "C:\Users\perso\AppData\Local\Programs\Python\Python38\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed while importing _socket: The specified module could not be found.

	at c:\Users\perso\.vscode\extensions\platformio.platformio-ide-2.2.0\node_modules\platformio-node-helpers\dist\index.js:1:879275
	at ChildProcess.c (c:\Users\perso\.vscode\extensions\platformio.platformio-ide-2.2.0\node_modules\platformio-node-helpers\dist\index.js:1:879169)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.cp.emit (c:\Users\perso\.vscode\extensions\platformio.platformio-ide-2.2.0\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
  ```

**Comment by TattlingElk** [comment]
Got the same problem:



%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.55.0
  PIO IDE: v2.3.2
  System: Windows_NT, 10.0.19042, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\tomva\.platformio\.cache\tmp\get-platformio-1.0.2.py", line 69, in <module>
    main()
  File "C:\Users\tomva\.platformio\.cache\tmp\get-platformio-1.0.2.py", line 61, in main
    bootstrap()
  File "C:\Users\tomva\.platformio\.cache\tmp\get-platformio-1.0.2.py", line 45, in bootstrap
    import pioinstaller.__main__
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\tomva\.platformio\.cache\tmp\.piocore-installer-vchnxg44\tmpcdkien92\pioinstaller.zip\pioinstaller\__init__.py", line 15, in <module>
  File "C:\Users\tomva\.platformio\python3\lib\logging\config.py", line 30, in <module>
    import logging.handlers
  File "C:\Users\tomva\.platformio\python3\lib\logging\handlers.py", line 26, in <module>
    import logging, socket, os, pickle, struct, time, re
  File "C:\Users\tomva\.platformio\python3\lib\socket.py", line 51, in <module>
    import _socket
ImportError: Module use of python38.dll conflicts with this version of Python.

	at c:\Users\tomva\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\platformio-node-helpers\dist\index.js:1:931376
	at ChildProcess.a (c:\Users\tomva\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\platformio-node-helpers\dist\index.js:1:931270)
	at ChildProcess.emit (events.js:315:20)
	at ChildProcess.EventEmitter.emit (domain.js:483:12)
	at ChildProcess.cp.emit (c:\Users\tomva\.vscode\extensions\platformio.platformio-ide-2.3.2\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
  ```
