### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by Theremingenieur** [platformio/platformio-core-installer#874]
%23 Description of problem
  PlatformIO-IDE install fails in code-server on Ubuntu 18
  It complains about **can't open file '~/.platformio/.cache/tmp/get-platformio-1.0.2.py': [Errno 2] No such file or directory** and more, see below. But the file is there. I can launch the pio core install manually on the CLI without problems, doing 
```
python3 ~/.platformio/.cache/tmp/get-platformio-1.0.2.py 
```
or even with quotes but full path
```
python3 '/root/.platformio/.cache/tmp/get-platformio-1.0.2.py'
```
But when I put the quotes as in the error message, typing
```
python3 '~/.platformio/.cache/tmp/get-platformio-1.0.2.py' 
```
I have the same error message on the CLI: **can't open file '~/.platformio/.cache/tmp/get-platformio-1.0.2.py': [Errno 2] No such file or directory**

What can I do to work around this?

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.56.1
  PIO IDE: v2.3.2
  System: Linux, 4.15.0-136-generic, x64

  %23 Exception
  ```
  Error: /usr/bin/python3: can't open file '~/.platformio/.cache/tmp/get-platformio-1.0.2.py': [Errno 2] No such file or directory

	at /var/lib/code-server/extensions/platformio.platformio-ide-2.3.2/node_modules/platformio-node-helpers/dist/index.js:1:931314
	at ChildProcess.a (/var/lib/code-server/extensions/platformio.platformio-ide-2.3.2/node_modules/platformio-node-helpers/dist/index.js:1:931208)
	at ChildProcess.emit (events.js:314:20)
	at ChildProcess.EventEmitter.emit (domain.js:483:12)
	at maybeClose (internal/child_process.js:1022:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
  ```

**Comment by Theremingenieur** [comment]
Hello, is anyone reading or investigating this? 

I made the effort to describe the problem in a way which allows to reproduce it. And I can actually neither finalise the configuration nor use my development server.
Although I can install the PlatformIO cli manually, it doesn't work within code server (VS-code). The pio home server is also not started.

**Comment by Theremingenieur** [comment]
That‘s extremely bad style to automatically close an issue without any feedback from developer side, as if these simply didn‘t care… Apparently, they have no interest in having happy users. I feel disgusted!
