### ISSUE TITLE
Can't install PlatformIO IDE

### ISSUE THREAD

**Issue by thefat32** [platformio/platformio-core-installer#88]
### Description of problem
VS Code fails to install Platform IDE Extension with weir
ModuleNotFoundError: No module named '_socket' exception in a python script
### Configuration

  VSCode: 1.49.0
  PIO IDE: v2.0.1
  System: Windows_NT, 10.0.19041, x64

### Exception
  ```
  Error: Traceback (most recent call last):
  File "C:\Users\Lucas\.platformio\.cache\tmp\get-platformio-0.3.4.py", line 69, in <module>
    main()
  File "C:\Users\Lucas\.platformio\.cache\tmp\get-platformio-0.3.4.py", line 61, in main
    bootstrap()
  File "C:\Users\Lucas\.platformio\.cache\tmp\get-platformio-0.3.4.py", line 45, in bootstrap
    import pioinstaller.__main__
  File "C:\Users\Lucas\.platformio\.cache\tmp\.piocore-installer-s_oot6qq\tmpvfe066mb\pioinstaller.zip\pioinstaller\__init__.py", line 15, in <module>
  File "C:\Users\Lucas\.platformio\python3\lib\logging\config.py", line 30, in <module>
    import logging.handlers
  File "C:\Users\Lucas\.platformio\python3\lib\logging\handlers.py", line 26, in <module>
    import logging, socket, os, pickle, struct, time, re
  File "C:\Users\Lucas\.platformio\python3\lib\socket.py", line 49, in <module>
    import _socket
ModuleNotFoundError: No module named '_socket'

	at c:\Users\Lucas\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\platformio-node-helpers\dist\index.js:1:4911
	at ChildProcess.c (c:\Users\Lucas\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\platformio-node-helpers\dist\index.js:1:4807)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.cp.emit (c:\Users\Lucas\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\cross-spawn\lib\enoent.js:34:29)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by thefat32** [comment]
Wiping "C:\Users\%USERNAME%\.platformio fixed
