### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by xavico10** [platformio/platformio-core-installer#928]
Hi. I hope you can help me with this problem.

I had used platformio with Atom since 8 or 9 months ago to program my ESP32. But I will continue my proyect but when platformio finish show me a message about Python. I installed the last version of it the first time and today i installed a old version to try, but the error is the same.

at C:\Users\xbges\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5004
at ChildProcess.s (C:\Users\xbges\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4900)
at ChildProcess.emit (events.js:223:5)
at ChildProcess.cp.emit (C:\Users\xbges\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by xavico10** [comment]
I forgoten, I am using Windows 10.
