### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by ioiomi** [platformio/platformio-core-installer#950]
Hello, My name is Sergio. My installation of PlatformIO have an error.

Error: Traceback (most recent call last): File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\pioinstaller\python.py", line 170, in find_compatible_pythons File "C:.platformio\python3\lib\subprocess.py", line 424, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "C:.platformio\python3\lib\subprocess.py", line 528, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['C:\Users\Sergio\AppData\Local\Microsoft\WindowsApps\python3.exe', 'C:\.platformio\.cache\tmp\get-platformio-0.3.5.py', '--no-shutdown-piohome', 'check', 'python']' returned non-zero exit status 9009.

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "C:.platformio.cache\tmp\get-platformio-0.3.5.py", line 69, in main() File "C:.platformio.cache\tmp\get-platformio-0.3.5.py", line 61, in main bootstrap() File "C:.platformio.cache\tmp\get-platformio-0.3.5.py", line 47, in bootstrap pioinstaller.main.main() File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\pioinstaller__main__.py", line 122, in main File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\click\core.py", line 829, in call File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\click\core.py", line 782, in main File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\click\core.py", line 1236, in invoke File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\click\core.py", line 1066, in invoke File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\click\core.py", line 610, in invoke File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\click\decorators.py", line 21, in new_func File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\pioinstaller__main__.py", line 52, in cli File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\pioinstaller\penv.py", line 52, in create_core_penv File "C:.platformio.cache\tmp.piocore-installer-169p5ni0\tmp0enctdfn\pioinstaller.zip\pioinstaller\python.py", line 191, in find_compatible_pythons UnboundLocalError: local variable 'error' referenced before assignment -> Installer version: 0.3.5 Platform: Windows-10 Python version: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:30:23) [MSC v.1928 32 bit (Intel)] Python path: C:.platformio\python3\python.exe Creating a virtual environment at C:.platformio\penv

at C:\Users\Sergio\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5004
at ChildProcess.s (C:\Users\Sergio\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4900)
at ChildProcess.emit (events.js:223:5)
at ChildProcess.cp.emit (C:\Users\Sergio\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core-installer/pull/949
