### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by alensali** [platformio/platformio-core-installer#955]
%23 Description of problem
Getting below mentioned error after installing the extension. Python3 version is 3.6.13. Tried the solution with installing zlib1g-dev, but the same error is shown every time I boot up VS Code.
Do you know what could be the issue or what else can I try?

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.58.2
  PIO IDE: v2.3.2
  System: Linux, 5.4.0-77-generic, x64

  %23 Exception
  ```
  Error: Traceback (most recent call last):
  File "/home/alen-sali/.platformio/.cache/tmp/get-platformio-1.0.2.py", line 69, in <module>
    main()
  File "/home/alen-sali/.platformio/.cache/tmp/get-platformio-1.0.2.py", line 61, in main
    bootstrap()
  File "/home/alen-sali/.platformio/.cache/tmp/get-platformio-1.0.2.py", line 45, in bootstrap
    import pioinstaller.__main__
zipimport.ZipImportError: can't decompress data

**Comment by alensali** [comment]
Hello, anyone managed to check this?

**Comment by alensali** [comment]
Found the solution for my problem at https://stackoverflow.com/questions/12344970/building-python-from-source-with-zlib-support
