### ISSUE TITLE
Could not create PIO Core Virtual Environment

### ISSUE THREAD

**Issue by odiewan** [platformio/platformio-core-installer#98]
%23 Description of problem
  Leave a comment...

  BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
  - https://github.com/platformio/platformio-vscode-ide/issues%3Fq=is%3Aissue 

  %23 Configuration

  VSCode: 1.49.0
  PIO IDE: v2.0.1
  System: Windows_NT, 10.0.19041, x64

  %23 Exception
  ```
  Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues
 -> Installer version: 0.3.4
Platform: Windows-10
Python version: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]
Python path: C:\Users\Odie\AppData\Local\Programs\Python\Python38-32\python.exe
Creating a virtual environment at C:\Users\Odie\.platformio\penv

    at c:\Users\Odie\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:138:23
    at ChildProcess.c (c:\Users\Odie\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\platformio-node-helpers\dist\webpack:\platformio-node-helpers\src\proc.js:124:5)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.cp.emit (c:\Users\Odie\.vscode\extensions\platformio.platformio-ide-2.0.1\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  ```

**Comment by ivankravets** [comment]
Please run the next command in your system terminal and provide an output of:

```
C:/Users/Odie/.platformio/python3/python.exe C:/Users/Odie/.platformio/.cache/tmp/get-platformio-0.3.4.py --verbose
```
